### ISSUE TITLE
event not triggering  (bluetooth)

### ISSUE THREAD

**Issue by algritz** [henrichg/PhoneProfilesPlus#1]
Hello,

I created an event that would switch profile when a specific Bluetooth device is connected  (car radio).

For some reason,  even if the phone is connected,  the event doesn't triggered,  it still shows as paused.

I have a Samsung Galaxy S4 running lollipop 5.0.2

**Comment by henrichg** [comment]
Fixed: commit https://github.com/henrichg/PhoneProfilesPlus/commit/959e8a9472c89f4fdab6ec369f865866667c8596

**Comment by algritz** [comment]
Nice, quick fix!

Do you know when this will be made available on the play store ?

**Comment by henrichg** [comment]
Check your email ;-)
