### ISSUE TITLE
Template conflict with hardware

### ISSUE THREAD

**Issue by temp20230326** [henrichg/PhoneProfilesPlus#100]
Cosmetic note: about imported settings or templates that has conflict with hardware configuration.

For example, the event template "Night call" cannot be fixed and made to work if there device has no SIM slot.

Event preferences has red note: "Check also sensor parameters flagged with red color" although there are no such flagged parameters because some sensors are disabled (grayed out) because "no hardware"

**Comment by henrichg** [comment]
But you can insert SIM card or delete Call sensor.

**Comment by henrichg** [comment]
Ok, ok, I know what you means. :-)
Added is check for Call, SMS, Roaming sensor and these will be disabled after restore of PPP data.
Will be in next version.
