### ISSUE TITLE
Problem with phone alarm since 6.1

### ISSUE THREAD

**Issue by dadaz** [henrichg/PhoneProfilesPlus#102]
Since 6.1 version, when I set an alarm in clock app (Android 13 on Pixel 6), alarm quicksetting show wrong hour, for exemple 6:29 instead of 6:30. Same on lockscreen.
And when I click on quicksetting, it opens Phoneprofilesplus instead of clock app.

When I disable alarm, it stays like if it was enable on quicksetting, notification icon and lockscreen.

No problem in 6.0.1

Thanks

**Comment by henrichg** [comment]
You have nabled in PPP Settings/System/"Use alarm clock"? If yes, then it is alarm from PPP. For exmple for "Time sensor". PPP only ADDS its own alarms, it does not change alarms from other applications.

**Comment by dadaz** [comment]
Nope, it's disabled. I don't use that.

Some screens to illustrate

I have this on stock android 13 rom (rooted or not) and on custom roms too

![Screenshot_20230407-101648_PhoneProfilesPlus](https://user-images.githubusercontent.com/5988669/230571719-d0352eef-88d4-4c14-8d99-15cbd30f4893.png)
![Screenshot_20230407-101725_Lawnchair](https://user-images.githubusercontent.com/5988669/230571725-417b0933-87f5-46f5-b9f9-eb9c37268923.png)
![Screenshot_20230407-101714_Horloge](https://user-images.githubusercontent.com/5988669/230571726-ef4e3234-7b03-4c6c-bb8d-6b356db151d7.png)

**Comment by henrichg** [comment]
Then I do not know. Maybe bug in your Pixel?
I'm checked source code of PPP and in all is used alarm clock only when "Use alarm clock" is enabled.

Snd me your PPP settings. For this use Editor menu / Support / E-mail settings to author.

**Comment by dadaz** [comment]
Just send it now.
Note that I have issue with default conf just after install.

And I had the same issue on my old phone.

**Comment by dadaz** [comment]
Sorry.

Just have send by the proper way.

**Comment by henrichg** [comment]
OK, your data: all events are disabled. And not any event uses Time sensor with time 9:59, 10:00. Hm, hm.

Restart of device do not helps? Uninstall PPP and again install+restore settings not helps?

When you enable alarms in Clock application. "10:00", in quick tile stays 9:59?

In my Pixel 6, after restore of your settings, is in Alarm quick tile "No alarm set".

**Comment by henrichg** [comment]
"It appears as soon as I install Phoneprofilesplus. If I set an alarm, it shows the hour minus 1 mn. And stays for ever. Even after restart !"

After fresh install of PPP, but without alarm set in Clock app, time in quick tile is also displayed?

**Comment by henrichg** [comment]
You do not have any events configured? Because table "events" in your backup is empty.

**Comment by henrichg** [comment]
I'm found this:

```
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(alarmTime);

        Calendar alarmCalendar = Calendar.getInstance();
        alarmCalendar.set(Calendar.HOUR_OF_DAY, calendar.get(Calendar.HOUR_OF_DAY));
        alarmCalendar.set(Calendar.MINUTE, calendar.get(Calendar.MINUTE));
        alarmCalendar.set(Calendar.DAY_OF_MONTH, calendar.get(Calendar.DAY_OF_MONTH));
        alarmCalendar.set(Calendar.MONTH, calendar.get(Calendar.MONTH));
        alarmCalendar.set(Calendar.YEAR, calendar.get(Calendar.YEAR));
        alarmCalendar.set(Calendar.MILLISECOND, 0);
        alarmCalendar.set(Calendar.SECOND, 0);

        // removed 5 seconds, because of:
        // - normally is alarmTime for future
        // - when is reached (boradcasted is ACTION_ALARM_CLOCK_BROADCAST_RECEIVER),
        //   received from system is again NextAlarmClockBroadcastReceiver with alarmTime = now time
        // - and with this situation must be be alarmCalendar < now time
        //   this prevents to configure alarm again
        alarmCalendar.add(Calendar.SECOND, -5);

```

Yes substract 5 seconds = from 10:00  (from Clock application) to 9:59. 

But:
`alarmManager.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, alarmCalendar.getTimeInMillis(), pendingIntent);
`

This do not use setAlarmClock(), but setExactAndAllowWhileIdle() and this alarm must not be accessible from Clock application. Bug in your Pixel 6, Clock app?

I;m tested this in my Pixel 6, Google rom (beta QPR3 v 2.1) and after set alarm in Clock application to 9:00 is displayed 9:00, not 8:59.

**Comment by dadaz** [comment]
Hmm, maybe a bug in clock app. It's google one.

**Comment by henrichg** [comment]
Then upgrade to latest, if is possible. In my Pixel 6 is version 7.4. Updated 16.3.2023.

**Comment by dadaz** [comment]
It's already in 7.4
Nevermind. I'll stay in 6.0.1 of ppp

**Comment by henrichg** [comment]
By me, displayed time 9:59 in quick tile is not problem. Because alarm will be started at 10:00. Test it.

**Comment by dadaz** [comment]
Yes you're right, it's just a cosmetic issue. It just disturbs me

**Comment by dadaz** [comment]
Just one more question.
What's the difference between 6.0.1 and 6.1 with alarm stuffs as there is no problem with 6.0.1 ?

Just to know.

**Comment by henrichg** [comment]
Added is Clock alarm time - 5 seconds. It must be for avoid Android system "feature" which causes problems in PPP. Problem with "Alarm clock sensor" is reported by another user.

Others is not changed.

**Comment by m1t4** [comment]
Hi

I have the exact same issue on my Xiaomi POCO X3 Pro and it also started with PPP version 6.1.
I'm running LineageOS 19.1, which is based on Android 12.

The behavior is similar to what is described by the topic starter.
Some additional observations: it seems that an additional alarm is added, which is off by 1 minute. It never goes off, only the one that I manually set. But in the system tray I have two alarm icons.
After the main alarm goes off, the "extra" alarm appears to stay on for another 10 minutes, before disappearing. 
10 minutes is accidentally is the duration of my snooze setting, don't know if it is related or not.

**Comment by henrichg** [comment]
Maybe first icon is from your Alarm clock application, second from PPP. PPP uses AlarmManager API. Maybe your alarm clock displays its own icon.

**Comment by m1t4** [comment]
> Maybe first icon is from your Alarm clock application, second from PPP. PPP uses AlarmManager API. Maybe your alarm clock displays its own icon.

Hi

Thanks for the reply.
Yes, that is probably the reason for two icons.
The reason I mentioned this is to confirm that this annoying issue emerged with 6.1 version and it is not unique to specific user, phone model or Android version.
Appreciate if something can be done to fix this.

Thank you

**Comment by henrichg** [comment]
Please istall and test this beta version:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

Maybe in it is fixed this.

**Comment by dadaz** [comment]
Thanks !
It fixes my issue !
Great job.
