### ISSUE TITLE
Latest version in Galaxy Store

### ISSUE THREAD

**Issue by chris2001jm** [henrichg/PhoneProfilesPlus#103]
Hello, when will the latest version be available from the Galaxy Store?  I have configured my phone so it does not install from "Unknown" sources and while I trust GitHub, I prefer not to configure this setting to allow installations.  I am very happy with this application as well as the "Extender" and would like to continue to support it.  Only I would prefer to do that from the Galaxy Store.  Thanks for your response.

**Comment by henrichg** [comment]
Few days. Currently is version 6.2 in GitHub only.

**Comment by henrichg** [comment]
Is up: https://galaxystore.samsung.com/detail/sk.henrichg.phoneprofilesplus
Check in device Galaxy Store.

**Comment by chris2001jm** [comment]
Thank You!  I successfully updated the application.  I will reach out to you if I have any issues.  Great app by the way.  I love it.
________________________________
