### ISSUE TITLE
Dotaz na polohu při změně profilu

### ISSUE THREAD

**Issue by happyBOY78** [henrichg/PhoneProfilesPlus#106]
![Screenshot_2023-05-16-08-10-21-88](https://github.com/henrichg/PhoneProfilesPlus/assets/6315249/92f75b46-b379-4758-bc61-36b685b6d468)
Od poslední aktualizace mi začala vyskakovat hláška, viz screenshot. Polohu povolenou mám, stejně tak i oprávnění pro PPP, na povolit vždy. Dělá mi to při změně profilu na jiný.

**Comment by henrichg** [comment]
No toto je velmi zvlastne.
Od poslednej aktualizacie coho? PPP alebo firmware v mobile? Lebo tato hlaska vypada byt zo systemu, nema nic s PPP.
Co je to vlastne za mobila s akou verziou Androidu?

**Comment by happyBOY78** [comment]
Od poslední aktualizace PPP. Jak jsem psal, v systému mám polohu zapnutou, v režimu vysoká přesnost (tedy kromě gps je zapnutá i lokalizace pomocí wifi a bt). 
Žádná jiná aplikace si "nestěžuje", u PPP je to pouze při pokusu o přepnutí profilu.
Veškerá požadovaná povolení mám udělena, včetně ADB. Mám root.
A jedná se o Realme C3, android 10.

**Comment by happyBOY78** [comment]
Stává se mi to u všech. Mám jich ale jenom pár.
Nastavení jsem vyexportoval a poslal na Váš email.

**Comment by henrichg** [comment]
No, vidim, ze okrem profilu Spanek na kazdom mate nastavene "(G1) Location mode"="Highh accuracy". To by ohlo na vasom mobile robit problemy. Skuste to bez tohoto parametra.

Ale vobec netusim, ze preco to robi ten parameter. Ten len zapisuje hodnotu do Settings.Secure.LOCATION_MODE.

**Comment by henrichg** [comment]
Testol som to v Android Studio emulatore a robilo mi to to iste. Ale ked som v nastaveniach polohy to vypol a zapol, potom to uz nerobila aktivacia profilu. Tak skuste.

**Comment by henrichg** [comment]
Nakoniec som mozno chybu nasiel. Ak chcete, testnite tuto beta verziu:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by happyBOY78** [comment]
Omlouvám se za pozdní reakci (pracovní důvody). Po nainstalování beta verze se zdá vše v pořádku a ta otravná hláška se už nezobrazuje. I přesto, že jsem svoje nastavení ponechal, jak bylo a neměnil jsem ho podle Vašeho doporučení. Jste skvělý a děkuju za rychlou pomoc 🙂👍

**Comment by henrichg** [comment]
Super. ;-)
