### ISSUE TITLE
Why not to outsorce Samsung special Functions?

### ISSUE THREAD

**Issue by just-Nob** [henrichg/PhoneProfilesPlus#110]
Hi,

nice to see a powerful automation tool for current Android devices!

Anyway, giving such a powerful tool so many rights on the phone is a question of trust.
Unfortunately, PhoneProfilesPlus depends on non-free libraries - as far as I can see, these are the Samsung API libs.

Since PhoneProfilePlus is obviously designed for supporting plugins, why not to outsource every special Samsung related functionality into a plugin?
This was to keep the main program free of non open source dependencies, and every user of a Samsung device would be free to enhance PhoneProfilePlus' functionality, if wanted or needed.

**Comment by henrichg** [comment]
Only non-free library in PPP is Samsung Look for Edge panel. All other libraries are open-sources: Android API and libraries from GitHub.

PPP do not supports plugins. Only 2 applications: PhoneProfilesplusExtender and PPPPutSettings. These are not plugins, but standalone Android applicaitons. But yes, working only with PPP.

Which Samsung API you want to support in PPP?

**Comment by just-Nob** [comment]
Thanks - no I don't wonna see any Samsung API support - I don't have a Samsung Phone at all! 😉

The only intention I had was to keep the main app clean from any non-free lib dependencies (I.e. free from closed source parts).

In addition, I guess that most people aren't an owner of a Samsung device, so my thought was it's OK to outsource the Samsung API related functions in a separate plugin/addon-app (for don't having closed source dependencies in the mail app).

And yes, I thought that PhoneProfilesPlusExtender and PPPPutSettings would have been plugins.

Feel free to close this issue of you don't agree (or if the effort of implementation is too high).

**Comment by henrichg** [comment]
Samsung Look is free of charge. Is downloaded from Samsung SDK web site.
Is only non-opensource.

Dwonloaded from this:
https://developer.samsung.com/galaxy-edge/download.html

**Comment by just-Nob** [comment]
OK, got it - thxa lot for the explanation.
So I guess this issue can be closed.
