### ISSUE TITLE
Profile templates

### ISSUE THREAD

**Issue by mvitaly2003** [henrichg/PhoneProfilesPlus#111]
There are situations or locations when one needs multiple profiles with same parameters, e.g. I use same volume settings for both home and work profile. Currently one have to duplicate same sets of parameters in all profiles where they needed.

It would be great to be able in a profile to inherit parameters from other profile(s) that would contain only basic parameters, to set some common parameters in one place only and use in dependent profiles. Either there should be abstract template profiles that may not be activated directly but only inherited or you can support inheritance for normal profiles and override their parameters in a dependent profile.

Perhaps most common example is different basic volume profiles (vibration only, silent, normal, loud) and some situation-specific profiles that use same volume parameters (home, street, work, meeting etc), also there may be some other settings like sound schemes, wallpapers etc.

**Comment by henrichg** [comment]
Each profile an also event in Editor list has menu (3-dot icon) and inn it is "Duplicate..." function.
![Screenshot_20230818_102053_PhoneProfilesPlus.png](https://github.com/henrichg/PhoneProfilesPlus/assets/4045914/a18151b9-a873-4013-a65e-1be5b56fab26)

**Comment by mvitaly2003** [comment]
And what if I duplicate a profile and then modify it? I'll have to transfer these changes to all duplicates?

**Comment by henrichg** [comment]
Hm, yes. Changes in duplicated profile do not change original profile.

But sorry, templates will not be implemented. 

Why it is needed? You using a lot profiles and in it a lot parameters?
I'm using in my device 14 profiles and each has different parameters (because each is for different situation), they do not repeat.

Also you do not needed to confiure all profile parameters, only these, which must be changed by profile activation.
Several users configure a lot parameters in each profile. Why? It is not needed. I have configured max. 5 parameters in my profiles.

**Comment by mvitaly2003** [comment]
Currently my profiles change mostly volume settings, and I have duplicated these parameters in some profiles, but it is annoying that I need to modify same settings in all profiles where I set them.

**Comment by henrichg** [comment]
Sorry, this functionality is not planned. Is complicated to implement it. Adding spinner "it is template" in profile parameters is not complicated. But usage of teplates is complicated in GUI (displaying it in Activator, Editor, widgets, dialogs with list of profiles, ...) and  profile activation. Also data implementation and usage in profile activation.

**Comment by mvitaly2003** [comment]
Perhaps I don't try to change too many parameters to reduce number of manual copy-paste operations. If there were templates, one could switch themes by attaching another template. But I understand that it isn't too easy to implement. Thanks for quick response anyway.

**Comment by henrichg** [comment]
Sorry, this functionality is not planned.
