### ISSUE TITLE
Link to cell names in mobile cell sensor instead of fixed list of IDs

### ISSUE THREAD

**Issue by mvitaly2003** [henrichg/PhoneProfilesPlus#112]
Currently every event has its own list of related mobile cell IDs, and it is hard to use same list for multiple events, but there may be situations when different events mush work in same location (e.g. standard and sound sound profiles for day and night at home), or an event must work outside of anothere event's location. Also often a new cell appears in a location that has its event and this event fails to activate related profile. Currently I don't know if event's mobile cell sensor list shows really all cells that the app seen, and I don't properly know if the app names new cells automatically without active scanning or not.

It would be great to be able to match cells by name instead, and to review known cells in common place, not related to a specific event. One could start scanning for new cells there, and the only effect would be in assigning given name for found cells, so these cells would be automatically bound to all events where this name was mentioned. Also all faced cells should be logged here to let user name them.

PS. There is an outdated Llama app for Android that has mentioned experience related to mobile cells.

**Comment by henrichg** [comment]
"Cell registration" requires to set cell name and each new cell will by named with this.

"Show notification for detection of not used mobile cells" in "Mobile cell scanning" Settings section: Click to notification about detected cell displays dialog and user must select events for which will be this event be selected. And also named it is required. I button in dialog for this.

**Comment by mvitaly2003** [comment]
Thanks for the answer.

Does "Select by cell name" action modify cell list for the event once or it will automatically handle new cells with same name later? The idea is that you have multiple events related to same group of cells matched by name and avoid modifying all these events when a new cell is added with this name...

**Comment by henrichg** [comment]
"Does "Select by cell name" action modify cell list for the event once or it will automatically handle new cells with same name later?"

No. It is not possible, because: which cells you want to select in which event? 
PPP has global database of mobile cells. Event uses only selected cells from this database. In PPP is not separated cells database for each event.

"Show notification for detection of not used mobile cells" has pseudo-automatic functionality, but user must click notification, select for which events will be detected cell selected and click "OK" diaog button.

How to working Llama for this?

**Comment by mvitaly2003** [comment]
> No. It is not possible, because: which cells you want to select in which event?
That's what I'm talking about. If some events will use same cell name as a cell matcher instead of fixed list of cell IDs, they all will automatically support new cells with same name.

> "Show notification for detection of not used mobile cells" ...
I've tried notifications but they are annoying then there are many new cells, it would be more convenient to name new cells at once.

> How to working Llama for this?
In Llama, there are three tabs: profiles, events and mobile cells, every new found cell is displayed ordered by time, and it is easy to name it (add to a named group). And events only refer to cell names, so all events for the same location support newly added or removed cells automatically when you change cell names. Since PPP already has names for cells, it shouldn't be hard to add support for using cell groups in events instead of cell lists.

**Comment by henrichg** [comment]
Mobile cells have its names in PPP. 

Problem with mobile cells is: for which event will be used this cell? For running event? But when is detected new cell, all running events with "Mobile cells sensor" ends, because this new cell id is not selected in events. And: how, when more then one event is running? How to automatically name cell id?

Mobile cells are detected by system. Returned is from system only cell id, not name. Naming cells must PPP.

**Comment by mvitaly2003** [comment]
As I understand, events are not running constantly, they only execute their actions when all conditions are met. So when you check if some event's conditions are met, you check if currently connected cell is known to PPP and has matched name, or maybe it will be easier to have a method to get current cell's name within PPP for easier match.

What PPP does when it detects cell change? Same activity should be performed, the only difference is that cell matching should be done not by checking event's ID list but by checking if the cell has given name. And when a cell is named, it should match all events with this cell name, in addition to currently supported events with fixed cell ID lists.

New cells in such case are just appear without names, and may be named at any time in Cells dialog.

**Comment by henrichg** [comment]
LLama:
"And events only refer to cell names, so all events for the same location support newly added or removed cells automatically when you change cell names."

Llamma has functionality for location of detected cell ids?. 
Yes system allows to get cell location, but this must be supported by BTS. Not all operators allows BTS location.
And how Llama check it? Is set by each cell name also location radius and this is used in location check?

In PPP is possible to display list of all cells. In "Cells dialog" is at top filter button. 
In filter is:
- [Selected] - all selected cells in event
- [Without name] - all cells without name, selected and also not/selected
- [New (N)] - all newly detected cells, selected and also not/selected
- [All] - all cells in database, selected and also not/selected
- <cell names> - cells by cell name, selected and also not/selected

Also exists sort (sort icon at top-right of dialog):
- By cell name
- By connected time

**Comment by mvitaly2003** [comment]
> Llamma has functionality for location of detected cell ids?.

Llama detects cells just by their IDs, like PPP, and you manually name them for adding to groups. If phone gets connected to a new cell, an event's condition failed. And you see mobile cell condition as red in all events that use it just like any other failed condition of any event. And you should name new cell to enable events for this location (i.e. group of cells with this name).

**Comment by henrichg** [comment]
OK, then:

1. "Mobile cells sensor" must using cell groups, not selected cell ids.
2. Newly detected cell id must be set to group (maybe more then one) by user and after that, event will working with this new cell id.

Is this correct?

This means completely redoing mobile cells sensor. Hm, hm. Not good.

**Comment by henrichg** [comment]
This:

"I've tried notifications but they are annoying then there are many new cells, it would be more convenient to name new cells at once."

And in Llama may be also be detected more and more new cell ids. Then how do you know which cell id belongs to which cell group? :-)

**Comment by mvitaly2003** [comment]
1. There should be an option to match cells by fixed list (as it is now) or by name. I think it will be even easier to check cell name because you will need to compare just one string instead of searching current cell ID in event's cell list. :)

2. I don't think that multiple names should be supported for a cell, just one (as it is now). Cells may be named by user or by scanning. And yes, when it gives name, it should match all events with "mobile cell name is xxx" condition.

> And in Llama may be also be detected more and more new cell ids. Then how do you know which cell id belongs to which cell group? :-)

Same problem exists in PPP too, it is hard to auto-assign cell to a group, but you should know if you were at that place at that time to decide that the cell should be added to the group, or you can just ignore a cell if you don't sure that it must be added to a group (e.g. if you went out for a dinner from your office at that time). E.g. if a cell is detected in the night, I add it to Home group, if it is detected at working hours, I add it to Work...

Due to cell radius events may be triggered not only at required locations but also nearby, just like new cell may cause event to fail even at required location, but this should be expected by anyone who decides to trigger events by cells.

**Comment by henrichg** [comment]
For first. In Llama exists cell name and cell group? By me only cell group. In PPP exists cell name. Cell group in Llama is group of cells, it is not name of cells. Group. In PPP each cell id has it name. 

In PPP and also in Llama is "fixed" list. But:
- in PPP is cell name, multiple cells may be named with the same name
- in Llama is cell group

In PPP you can select, in mobile cell sensor, all cells by cell name. This is the same as add cell to group in Llama.

Maybe in Llama is also cell name, but for events is important cell group. In PPP is only cell name.

Only problem with PPP is: User must select cells in mobile cells sensor. Cell name may be used  with "Change selection".

"E.g. if a cell is detected in the night, I add it to Home group, if it is detected at working hours, I add it to Work..."
This is possible also in PPP. When notification from "Show notification for detection of not used mobile cells" is ignored, cell is not added to database.

**Comment by mvitaly2003** [comment]
In Llama you have named areas and add cell IDs into them, in PPP you have cell names - in both cases effect is the same: you can refer to any location by its name (either group name or cell name).

> Only problem with PPP is: User must select cells in mobile cells sensor. Cell name may be used with "Change selection".

This is currently the only problem, event can't match any currently known cell by its name, they can only match cell by checking if its ID is in fixed list.

> When notification from "Show notification for detection of not used mobile cells" is ignored, cell is not added to database.
What does mean "not added to database"? Such cell won't be visible anywhere? Or it will be visible later in Cells dialog with no name? It would be useful to see such cells to be able to name them manually.

**Comment by henrichg** [comment]
"I would be happy with just tagged cells, as it is now in PPP, it provides same usability as named non-intersecting groups of cells as was in Llama. I only need to be able to match cells by names in mobile cells sensor."

Then you want to use in "Cells" dialog filter "[Selected]". This displays only cells selected in event.

"I don't think that multiple names needed, if you have 2 zones around one cell, it is hard to detect which event should be triggered."
No multiple names. The user would use one of the existing events and use its name for the cell.

**Comment by mvitaly2003** [comment]
> Then you want to use in "Cells" dialog filter "[Selected]". This displays only cells selected in event (mobile cells sensor).

But it doesn't allow sharing same list of cells between multiple events...

**Comment by henrichg** [comment]
Rename in source event all selected cells to the same name (result: all cells in source event will be with the same name) and in destination event select cells with this new name.

**Comment by henrichg** [comment]
Again, again again. :-(

Each new detected cell must be named. And how to select it in all related events? 
This is possible only in "Show notification for detection of not used mobile cells".

Cell groups will not be implemented. This completelly replaces "mobile cells sensor" functionality and must by implemented also transfer of old functionality to new, during PPP upgrade. But I do not know how. 
Maybe:
- generate group for each event (with name from event)
- add all selected cells form event to this group.

Then detection of new cells (by mobile cells scanner, mobile cells registration, "Show notification for detection of not used mobile cells"). 
How with this?

**Comment by mvitaly2003** [comment]
As I understand, PPP has global list of known cells, and it stores last timestamp and optional name for every cell, right?

And when PPP detects cell change, it should somehow check which events use cell sensor and have new cell's ID in list, isn't it?

It should be pretty easy to add new cells without names to global cell list when PPP gets new cell information from phone.

Also it is already easy to manually name these unnamed cells via Cells dialog if new cell notifications are disabled.

And it should be easy to get current cell name from this global list to match it with name in events where matching by name is requested. No need in storing fixed list of IDs in such events. Just comparing two strings...

> Then detection of new cells (by mobile cells scanner, mobile cells registration, "Show notification for detection of not used mobile cells").

If every event uses its own group name, how it can be reused by another event?

**Comment by mvitaly2003** [comment]
> Currently you must manually type event name when you name cell. 

Not only event name but any name may be used for cells.

> Dialog for cell names displays only existing cell names, not event names (but will be added).

I don't see any sense in associating every cell with an event, because multiple events may refer to same location (area) which is defined by a set of cells.

Is it so hard for your sensor to check if current phone cell is known to PPP and get its name if assigned? If it is done within PPP, it should be very simple... Sensor gets cell ID, finds cell name by ID in global cell list and checks this name

**Comment by henrichg** [comment]
Yes cell name is possible to get from cell id but? How to use this cell name?

You want to configure in sensor only cell names? Not cell ids?

Then how to associate cell name with newly detected cell id? Adding another dialog to configure cell names for cell ids? In PPP Settings/"Monile cells scanning"?
In this dialog must be displayed cell ids without name and user must name it?
And in it must be possible also adding new celll names?

**Comment by mvitaly2003** [comment]
> You want to configure in sensor only cell names? Not cell ids?

Exactly. To avoid editing events when new cells are added to the related location.

> Then how to associate cell name with newly detected cell id?

You can just add them to global list with no names and let user manually name them via Cells dialog. Or user can start scanning for new cells and provide the name for them. PPP can't decide itself if a cell belongs to the area or not.

> And problem with old configuration persists. How to reconfigure old data to new?

Can you just support both modes in configurations? To let user choose between current behaviour and matching by name w/o fixed list of IDs?

**Comment by henrichg** [comment]
Hm, then complete reimplementation of Mobile cell scanning and Mobile cell sensor. 

- In sensor: only list of cell names and user select cell names for sensor. Removing "Cell registration", Reimplementing (or remove?) "Show notification for detection of not used mobile cells".
- In scanning preference: adding new preference with dialog for editing cell names.
- In scanner: from cell names in sensor get cell ids and check it with detected connected cell id.

Maybe will by implemented. Maybe. :-)

**Comment by mvitaly2003** [comment]
It is sad that such large work is required. Hope you'll make it. :)

Notifications may be useful sometimes, so it is better to keep them as is, optional.

**Comment by henrichg** [comment]
OK, implemented. Maybe it is good.

- In Mobile cells sensor are used cell names instead cell ids. New parameter "Cell names". You can select more than one cell name in it.
- Added is "Mobile cells editor". It is in PPP Settings in "Mobile cells scanning", but is accessible also from event "Mobile cell sensor". It is the same dialog as in old version "Mobile cell sensor"/"Cells". In it you can configure cell ids and its names.
- "Cells registration" is moved to PPP Settings "Mobile cells scanning", but is accessible also from event "Mobile cell sensor".
- "Show notification for detection of new mobile cells" stays in PPP Settings "Mobile cell scanning", removed is events support from it, because in not needed.
- During upgrade of PPP is reconfigured old "Mobile cell sensor"/"Cells" to "Cell names". All selected cells in it are changed to cell names, grouped by cell name.

If you want, install and test this beta version:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by mvitaly2003** [comment]
Wow, that was fast, thank you!:)
I'll try to test it soon...

It's nice that multiple cell names may be specified for an event.

Perhaps with such changes "name" term for cells may be replaced by "area", "zone" or "location" in UI...

**Comment by henrichg** [comment]
"Cell name" is a term used for a long time in old version (with cell ids in "Cells"), then by me, is not good to change it.

**Comment by mvitaly2003** [comment]
I've tried this beta version, looks good. The thing that may be improved: you can now display "Cell name: NAME1, NAME2, ..." instead of "Selected 1" in event details, under "Mobile cell sensor" entry in event properties, and under its "Cell names" option. There were lots of cell IDs so it was useless to show tens of IDs in these places but since there are now just one or some cell names, it would be better to see exact names instead of just count.

**Comment by henrichg** [comment]
1. Summary in preference screen has a limited size. :-( For this reason, PPP displays for one selected value its value (contact name, application name, ...). For more than one value, displayed is only "Selected: XXX".
2. Yes in "Cell names" is forced "Selected: XXX" (a remnant of when it was "Cells"). I can change it. How? For values: 1 or 2 or 3 values (cell names) and for more "Selected: XXX"? Is this ok for you?

**Comment by mvitaly2003** [comment]
I understand that there is a limit of screen space. Of course, it will be much better to see at least one cell name, two or three would be even better. BTW I think you could also limit total number of displayed names by maximum length of comma separated list of names. Some cell names may be long enough to show even two, some may bee quite short to show three. Perhaps you could use same helper function for formatting all such lists: you pass array, max number of items and max length, and it shows something like: Item1, Item2, ... (7 total).

**Comment by henrichg** [comment]
Install and test this beta (6973):
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

In it is displayed max 3 names, more as "Selected: XXX".
Also some bug fixes.

**Comment by mvitaly2003** [comment]
I've tried this beta, thanks, that's better! Perhaps quoting is not really necessary here, but I'm currently have simple one-word names (Home, Work), and maybe long names really look better with quotes.

**Comment by just-Nob** [comment]
Finally, I have found some time to familiarize myself a little with PPP, at least some first steps.

I especially have taken a look at the Cell ID handling, because I liked that feature a lot in Llama and Easer (it was always one of my favorites).

The current way of naming groups of cell IDs in the settings for accessing them in the events looks good at first sight (i.e. as far as I got it).
But I wasn't able to detect how to edit an already created group; I would have expected it somewhere in [Settings]→[Application Settings]→[Mobile Cells Scanning]→[Mobile Cells Editor], but wasn't successful. Although I was able to select the one I already created when tapping on [Cell name] at the editor's bottom, selecting it doesn't show the Cell IDs being part of that group.

The background why I like to see and edit that group is that sometimes cell IDs in a given area (e.g. "Home") sometimes changes, maybe due to new or exchanged cell towers. That's what I observed when using Llama and Easer.
So I need the possibility to adopt any group of cell IDs when they are changing in a particular region.

But maybe I have just overlooked the possibility or have not yet understood it properly.

**Comment by henrichg** [comment]
For first: In PPP are not cell groups. Each cell has "cell name". In "Mobile cells sensor" user select cell names (in latest beta in deployed 6.2 are used cell ids).

In Cells Editor are several buttons and clickable icons (orange).

At top is Filter button:
![CallsEditor_01](https://github.com/henrichg/PhoneProfilesPlus/assets/4045914/24d35b19-4245-4b91-b679-d6a2d7010402)

You can change filter of displayed cells to:
- [ New (N) ] - detected by this Cells registration and by Mobile cells scanning (when is enabled notification abount detected cells).
- [ Without name ] - all cells without name
- [ Selected ] - all selected cells - in Cell Editor you must select cell to change its name
- [ All ]- all cells in database
- cell_name - all cells with this cell_name
![CellsEditor_02](https://github.com/henrichg/PhoneProfilesPlus/assets/4045914/6bc07604-5bf8-41ff-ab3a-d4f4d1422f37)

**Comment by henrichg** [comment]
How to use Cells editor:

1. Set filter to cell name, which you want to edit. Maybe you want to edit New cells (marked with (N)). After close of Cells editor all (N) cells will be changed to "not-new" (without (N).
2. Cells, which you want to edit, must be selected (checkbox at start of cell in cell list).
3. You can change selection by middle icon at bototm of dialog
4. Change name with button "Cell nane" at bototm left of dialog. This name will not be used. It is only for configuring, which name will be used for change
5. At bottom, first icon (pen) is for change name. Select which cells you want to change its name. Changed will be only visible cells in cells list. Used  will be name in "Cell name" button:
  - New (N)
  - Selected 
  - All visible
6. You can delete cell. Each cell in list has 3-dot menu. Use it for delete cells: 
  - Delete - to delete cell for which id this menu displayed
  - Delete all selected - from visible cells
  - Delete all nselected - from visible cells
7. You can add new cell by click plus icon at end of connected cell (it is displayed at bottom of cells list).

**Comment by just-Nob** [comment]
Thanks for the explanations.

I was in home office the latest few days, so the number of cells nearby was very limited.
I'll be in the official office tomorrow, so I hope I will have the chance for some more intensive tests with more cell towers nearby, just to get a better understanding of the implemented way of usage and functionality.

Regarding cell groups:
As far as I understood, all cells are basically identified by their cell ID, which makes a lot of sense.
If I like to use them (in latest beta), I have to give them a name, which makes also a lot of sense.
But if I got it right, I'm able to name multiple cells identically (i.e. to give them the same name), so I'm able to build cell groups by name.
Isn't that correct?

I find it a little confusing that the "Cell name" button have a double functionality, although it makes sense from the economic point of view referring to the used space in GUI.
I'll keep an I on this tomorrow and will maybe write my thoughts about that in more detail tomorrow.

Anyway, is j d. xdjjjx way to add a cell ID to a cell name by directly entering the ID number?
HonestlyI think that's a rare case where this makes sense.

**Comment by henrichg** [comment]
Cell ID is from the system. The cell name is from PPP. More than one cell ID can have the same cell name. And yes, a cell name can be represented as a cell group.
Therefore, cell names are now used in "Mobile cells sensor". One cell name = X cell ids.

"Cell name" button: Is used not only for renaming cells, but also for selecting cells.
- Renaming: "pen" icon at bootom of dialog
- Selecting "select" icon at bototm of dialog
In both situations is used name in "Cell name" button.

"Anyway, is j d. xdjjjx way to add a cell ID to a cell name by directly entering the ID number?"
Not. And why is this needed? Cell ID is just a number. Can you identify from this number which BTS this cell is from? :-)

**Comment by just-Nob** [comment]
«In both situations is used name in "Cell name" button.»:

Yes, after your first explanation given yesterday that was already clear to me, but I don't find that very intuitive.

A second point is that I hadn't had the idea that the "tick" icon may be for selecting - my idea was some kind of confirmation button, an "OK".
The following are some alternative suggestions that I personally find more intuitive:

![11347359.png](https://github.com/henrichg/PhoneProfilesPlus/assets/25401767/f3c464bf-fb5e-48b5-88a2-d3f5ad083341)

![2756186.png](https://github.com/henrichg/PhoneProfilesPlus/assets/25401767/f63e3dc4-3375-42e3-b215-ca2b1f6bc803)

![2767163.png](https://github.![3601998.png](https://github.com/henrichg/PhoneProfilesPlus/assets/25401767/0954e6ce-e5a0-47ff-a984-24ff2951a402)

/assets/25401767/ba8a3dfc-2ea3-42c0-9961-d8f8f401dc94)

![Uploading 3601998.png …]()

**Comment by just-Nob** [comment]
«And why is this needed? Cell ID is just a number. Can you identify from this number from which BTS this cell is? :-)»

Yes, indeed, that's possible!

On the one hand, I have the cell IDs being collected for the locations being personally relevant for me.
If PPP had the option to enter cell IDs by their numbers, that would be a possibility to "import" them into PPP by copy & paste. 😇

On the other hand, you are able to access maps on the internet, showing the cell towers positions and IDs, e.g.:
[Open Cell ID](https://opencellid.org/),
[https://www.cellmapper.net/](CellMapper)

**Comment by henrichg** [comment]
@just-Nob
"The following are some alternative suggestions that I personally find more intuitive:"

"select" icon is from Adroid Asset studio: https://romannurik.github.io/AndroidAssetStudio/.
It is clippart with name "check_circle". Yes exists also "check_box", maybe this is better, because in cell list are used checkboxes.

About adding manually cell ids: Maybe will be implented, bus as separate ptreference in "Mobile cell scanning". maybe in it will be aslo impleneted import cells from file.


@mvitaly2003
I will looking for better GUI of "Mobile cells editor" for adding, selecting, deleting cells.

**Comment by henrichg** [comment]
How about this:

1. "Cell name" button will be removed.
2. Connected cell, displayed at bottom of cell list: Displayed will be [N] when is not in database, and [ Without name ], when has not name. 
3. "plus" icon at end of connected cell: will be enabled only when cell id is not in database. Click displays "Cell names" dialog and in it will be possible to select existing name in db or write name in edit line. This name will be used.
4. "pen" icon will be changed to "Rename cells" button. Also will be displayed "Cell names" dialog to configure cell name for rename.
5. "select" icon: for "Select by cell name" will be displayed "Cell names" dialog to configure cell name for select.

Better?

**Comment by mvitaly2003** [comment]
If I got it right, you suggest to move all renaming to a sub-dialog and always affect sells selected in list, that's nice.
Connected cell info and "plus" button for naming new cells with selecting names looks good too. However I don't currently understand which cells are "new" and when they become just "without name" and not "new". If you remember, I've asked to automatically add all new cells to the database without names to let user name them later, and for me these cells are both "new" and "without name".

> About adding manually cell ids: Maybe will be implemented, but as separate preference in "Mobile cell scanning". Maybe in it will be aslo implemented import cells from file.
I think it should be good enough to provide a multiline edit field to enter cell IDs, one per line, so one could paste list from clipboard.

**Comment by henrichg** [comment]
A new cell is a cell that is not in the database and device is connected to it. 
Each new cell is without name, but maybe exists also cell in db without name. This is possible especially for cells added into db in old PPP version (in which the cell name was not required).

**Comment by mvitaly2003** [comment]
So I have to enable "Notification about detection of new cells" to make PPP add new cells to the database?
What if I want new cells to be added but without notification? I see "Detection of not used mobile cell" in PPP notification settings, does disabling it solve my problem?

**Comment by henrichg** [comment]
When you disable this notification, new cells will not be added to database.

Because when will added, by mobile cells scanner, each detected cell without notification, will be added more and more and more cells without name. Especially when your device is moving (in car, for example). And by me, it is not good. I'm tested it. Also some users send me e-mail about this, where did they refer me to it.
 
If notification is displayed, user must click to notification and add cell in displayed dialog. If user click "Cancel" button in dialog or close dialog, co cancel notification, cell is not added.

Currently is not possible to add cell without its name. Only in old PPP versions.

**Comment by mvitaly2003** [comment]
Perhaps you're right, many cells are not interesting to a user, only when he is in some specific locations.

**Comment by henrichg** [comment]
Changed. If you want, install and test this beta:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by just-Nob** [comment]
Had a look at the new beta, and it looks good to me.
In my opinion, it's now much more intuitive and understandable.

I also agree that it's not really useful to collect every cell ID to which you're your phone is collected to, because later on it's hard to decide which cell have to be assigned to which location (= name in PPP) - that only is a mess of data filling your phone's flash memory. 😉
@mvitaly2003: Anyway, of you like to collect every tower / cell ID your phone was connected to over a long period of time, you can do so by activating the _Cell Registration_ (up to one day) and choose a new name to which new cells should be assigned to.

**Comment by just-Nob** [comment]
There's one topic where I which a little improvement referring to the function "_Show notification for detection of new mobile cells_".

In general, it's very nice that this functions offers the possibility to add a new cell (i.e. cell ID) to any name, simply by clicking on the notification by what a floating window opens where you can enter your choice.
The disadvantage is that if you miss that chance by any reason (maybe by accidentally clicking near the shown window, which let's the floating window disappear), you get no second chance.

Maybe there's the possibility to add this action to the history, with the chance to open the floating window one more time out of the history when tapping on the associated entry?

**Comment by henrichg** [comment]
Dialog for  "Show notification for detection of new mobile cells":
Fixed with disabling close of it when user click outside of dialog or use back gesture/click back navigation button. 
When user use Up gesture/click Home navigation button, is possible to go back to dialog in Recents screen.

By me, this is more better then implementing history of notifications.

**Comment by mvitaly2003** [comment]
You could just add a cell ID to "new" list without a name in such case, when notification is enabled but user didn't react on it.

**Comment by henrichg** [comment]
In current (yesterday) implemntation, it won't happen. Is not possible to be closed dialog, when user click outside of dialog or when use back, home navigation.

**Comment by just-Nob** [comment]
The "add cell ID to 'new' list may also a good ID, maybe optionally, but should be limited to the latest _x_ hours (x = parameter, e.g. 24 hours) to not flooding the data base.
But in that case, a time stamp would be great to make an assignment between the location (because often I know where I was at what time) and the collected cell IDs.

**Comment by henrichg** [comment]
By me, better is using "Cell registration" for time limited detection of new cells.

**Comment by mvitaly2003** [comment]
Well, I've meant that only when notifications are enabled, cells should be added to "new" list, otherwise no. Though it would be really nice to have some temporary list with latest N cells, or cells during e.g. last 24 hours.

**Comment by mvitaly2003** [comment]
It seems that I somehow renamed all my home cells to "Work", or something else weird happened... That's probably because of non-transparent managing cells in previous versions. I'll try latest beta now, and most probably purge all cells because of this mess.

**Comment by mvitaly2003** [comment]
Currently detection of unused cell requires too much actions to be handled: 1. tap on notification, 2. tap on name selection button. 3. tap on name. 4. tap OK in name selection dialog. 5. tap OK to confirm naming the cell... When there are many new cells, it is very annoying to repeat this process for every cell... It would be great to simplify naming detected unused cells.

**Comment by henrichg** [comment]
OK, but user must select name from existing names or write new specific name.
How? Displaing names list directly in notificaiton dialog + edit line for set new name?
Or you want to not name cell? Write to db flagged as (N) but without name? Then this cell will not by autoamtically used by event, because cell is without name.

**Comment by mvitaly2003** [comment]
When I open notification, I want to name the cell, and it may be one of known names (perhaps most probably) or a new one (rare). I think you can show list of known names in notification dialog directly, and a button 'new name' below to give new name.

**Comment by mvitaly2003** [comment]
BTW it is quite boring to go to mobile cells settings to enable/disable notifications or to start scanning. It would be nice to have a faster access to these settings. E.g. you could hide untouched settings in events by default and show a special item for unhiding them... Or remember scroll position for every event's settings and app settings, so user wouldn't have to scroll large list of settings to previously used position.

**Comment by just-Nob** [comment]
Although I think that accessing the "scan cells" function is a more seldom task after PPP's setup is established, it is correct that it's used more often when setting it up.

What's about configurable widgets or quick access tiles?
Configuration parameters: Cell name, scan duration. So you could create multiple widgets or tiles:
One for 6h @work,
one for 2h @home,
one for opening the "scan cells" dialogue
etc. ...

**Comment by mvitaly2003** [comment]
Well, I agree, widgets for quick access to settings is also a nice option.

But I think caching scroll positions could be a nice feature anyway, and shouldn't be hard to implement.

**Comment by henrichg** [comment]
Scrolling caching is problem, because PPP has sub preferences not one list with all prefetences.
By me, add option to hide/unhide not used sensors in event preferences is better and is possible to implement it.
In profile preferences mat be problem wiyth identifiing whis sub preference is configured. But  maybe is possible to implement it, i will looing on it.
I app Settings this will not be implemented.
It is ok?
And please, add new issue abut this. It is not relevant to mobile cells sensor.

**Comment by mvitaly2003** [comment]
I've created #114 with more details regarding every idea.

**Comment by henrichg** [comment]
Notification for detection of unused cell: Chnaged, lost of cell names is in dialog, and also added is Edit line form set specific name. 
If you want, istall and test it:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by mvitaly2003** [comment]
I tried last beta, removed some cells to see notification dialog faster, looks very good and convenient!

If I swipe notification, cancel dialog or switch to another app from it without confirming, the cell won't be added to the database, correct?

**Comment by henrichg** [comment]
"If I swipe notification, cancel dialog or switch to another app from it without confirming, the cell won't be added to the database, correct?"

Yes, only click OK button in dialog save cell.
