### ISSUE TITLE
Instruction Manual / Operating Instructions / Guideline for PPP ?

### ISSUE THREAD

**Issue by just-Nob** [henrichg/PhoneProfilesPlus#113]
Hi Henrich,

first of all, thx for that nice tool!
I'm currently familiarizing myself with it, and so some questions comes up from time to time.
Before I'm either investigating lot of times for finding out things that are already described or annoying you with silly questions, I like to ask if there's an official description about the tool's concept, possibilities, handling, parameters... - just am instruction manual, guideline or something similar! 😉
Or just a place where to discuss such "basic stuff"?

To say it in advance, in not totally inexperienced in such tools, I formerly used Llama (RIP), Easer (in early stage, no progress since about one year), and Automation (not that powerful), but reach of them has a different concept behind and different possibilities.

Of there's no instruction manual / guideline, I could offer to write one, if you like to (but may take time), in English and German.

**Comment by henrichg** [comment]
In PPP exists in Editor at top bar "question-mark" icon = "Important information".
In it are:
- Important information
- Help with GUI items

Important information:
In it are two tabs:
- Important information - help about special functionality in PPP. In it are also "News". For "News" is also generated notification after each upgrade of PPP. It is separated to 3 sub groups: System, Profiles, Events.
- Quick guide: basic guide about PPP.

Help with GUI items:
If user enable it, it displays bubbles in Editor for several GUI items.

App "Imporrtant information" is transalted to several languages (translator mus translate it in https://crowdin.com/project/phoneprofilesplus

Another informations are in GitHub in README.md (only english):
https://github.com/henrichg/PhoneProfilesPlus/blob/master/README.md

Exists also Wiki in GitHub, but it is very verv very outdated. Please, do not read it. :-)

**Comment by just-Nob** [comment]
Thx... - I'll take a look about all of this.
But... - can't promise not to read Wiki in github! 😉
