### ISSUE TITLE
Are the ringtone of sim card 1 and sim 2 can set respectively?

### ISSUE THREAD

**Issue by elsns** [henrichg/PhoneProfilesPlus#118]
Could you please add a function: In the ringtone setting the ringtone of sim card 1 and sim 2 can be set respectively. That will be very helpful. thanks a lot.

**Comment by elsns** [comment]
can't find that setting, am I in the wrong place?
![Screenshot_20231203_100434](https://github.com/henrichg/PhoneProfilesPlus/assets/62682950/4a0c2788-00e2-49ac-be63-36c12ef20afe)

**Comment by elsns** [comment]
and my phone is iqoo11

**Comment by henrichg** [comment]
Iqoo is not supported. Sorry.
I do not own iqoo device. And for this reason is not possible to find setting parameter names for change sim 1, 2 ringtone.

**Comment by henrichg** [comment]
Please install: https://www.f-droid.org/packages/io.github.muntashirakon.setedit/

Run it, at top bar in left, change to System table and at top bar in right use menu/Save as JSON.
Then email me this json file.
Thanks.

**Comment by henrichg** [comment]
Please install: https://www.f-droid.org/packages/io.github.muntashirakon.setedit/

Run it, at top bar in left, change to System table and at top bar in right use menu/Save as JSON.
Then email me this json file.
Thanks.

**Comment by elsns** [comment]
This is the json file from my IQOO11.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "henrichg/PhoneProfilesPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 晚上11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [henrichg/PhoneProfilesPlus] Are the ringtone of sim card 1 and sim 2 can set respectively? (Issue #118)





 
Please install: https://www.f-droid.org/packages/io.github.muntashirakon.setedit/
 
Run it, at top bar in left, change to System table and at top bar in right use menu/Save as JSON.
 Then email me this json file.
 Thanks.

**Comment by elsns** [comment]
I have sent the file to your email, if need more please let me know.

**Comment by henrichg** [comment]
E-mail with json file is not received. Send it again. henrich.gron@gmail.com.

**Comment by henrichg** [comment]
OK, Change ringotne for sim 1 working?
Not working only for SIM 2?

In your device settings is (from json file):

"ringtone": "content:\/\/0@media\/external\/audio\/media\/1000085207?title=01A%20%E7%88%B1%E5%9C%A8%E8%A5%BF%E5%85%83%E5%89%8D&canonical=1",
"ringtone_set": "1",
"ringtone_sim2_set": "1",

For sim 1 is parameter "ringtone" and this is set.
For sim 2 exists only "ringtone_sim2_set". But is not saved, which ringtone.

In PPP:
For Samsung sim 2 ringtone parameter is "ringtone_2", For Huawei "ringtone2", for Xiaomi "ringtone_sound_slot_2", for OnePlus "ringtone_sim2". Other devices are not supported.

Is possible to set ringtone for sim 2 in your iqoo device, in device Settings?

**Comment by elsns** [comment]
only can change the ringtone for sim1 and there's no operation for dual sim card in the app sound setting. In my iqoo device setting   
both ringtone and  message tone can be set for sim1 and sim2.

**Comment by henrichg** [comment]
An you changed ringtone in device settings for sim 2? Another from sim 1? Because in system table (from json file) is not saved tone for sim 2. Only in "ringtone" parameter, which is used when only one sim is inserted or for sim slot 1 when both are inserted.

**Comment by elsns** [comment]
under device setting, I can set both sound of two sim cards. I have two sim in the phone.

**Comment by elsns** [comment]
and when I set ringtone in phone profile app only card CMCC in my phone changed.

**Comment by henrichg** [comment]
Hm then not saved to system settings and for this reason not possible to change it from PPP. PPP change tone directly in system table.

What is CMCC and CUCC?

**Comment by elsns** [comment]
short for 2 mobile operaters, China Mobile
Communications Corporation and China Unicom Communications Corporation. 
it's a pity that I can't use the function, PPP is  realy good for me.  and yes iqoo and vivo sometimes are different compare with other phone.

**Comment by henrichg** [comment]
Hm, sorry, not possible from PPP change it. Because your device do not use system table for this. 😥
