### ISSUE TITLE
Location sensor on Samsung Galaxy S24

### ISSUE THREAD

**Issue by tpcol** [henrichg/PhoneProfilesPlus#120]
Hello, I switched from a Galaxy Note 9 to a Galaxy S24 (Android 14). On the new Phone the location sensor function does not work. The app show, that I am in the location, but the profiles shown those sensor as not true.

**Comment by tpcol** [comment]
Sorry, you have right: events. The location sensor is not passed (blue), but I am in the array.

**Comment by henrichg** [comment]
In Location editor screen is sensor location (orange circle) in blue circle of actual location?

**Comment by tpcol** [comment]
That could be the reason. In the settings I have given a radius of 100m. When the smaller blue (!) circle is complete in the orange circle, the sensor passed, but when the blue circle is not complete in or greater as the orange circle (maybe 90 % of the array overlays), the sensor is not passed. When I change the radius, it is change the orange circle. The location pin is allways in both circles.

**Comment by henrichg** [comment]
Blue circle must be completely in orange circle to set sensor passed.

Increase accuracy in location. Check device Settings/Location/Locatio servcies/Implrove acuracy. Set both Bluetooth and Wi-Fi enabled.

Also if in your location is not Wi-Fi, mobile network, used is GPS. But GPS has good accuracy only in outdoor.

**Comment by tpcol** [comment]
Thank you. I will tomorrow test the settings.Viele Grüße aus KölnThomas PosseltGesendet von einem Smartphone

**Comment by tpcol** [comment]
Good Morning, I testet the settings this morning. Now I am since approx. 30 Minutes in my office. There is no blue cricle shown until yet.

**Comment by henrichg** [comment]
Then location in your device not working? Blue circle with mark in its center is from device location system. Is Location enabled in device?

**Comment by tpcol** [comment]
I have checked the permissions. Location is allowed for PPP and in Google Maps the correct position of my device is shown. WIFI and mobile network is enabled.

**Comment by henrichg** [comment]
Location permission is enabled to "All the time"? It must, because PPP working in background.

**Comment by tpcol** [comment]
Yes, it is.Viele Grüße aus KölnThomas PosseltGesendet von einem SmartphoneVon: Henrich Gron ***@***.***>Gesendet: Dienstag, Februar 13, 2024 10:07:59 AMAn: henrichg/PhoneProfilesPlus ***@***.***>Cc: tpcol ***@***.***>; Author ***@***.***>Betreff: Re: [henrichg/PhoneProfilesPlus] Location sensor on Samsung Galaxy S24 (Issue #120)
Location permission is enabled to "All the time"? It must, because PPP working in background.

**Comment by tpcol** [comment]
Now I am really confused. My position ist outside of all my three defined for working locations, but the event show the sensor in green.Viele Grüße aus KölnThomas PosseltGesendet von einem Smartphone

**Comment by henrichg** [comment]
Hm. Send me PPP settings. For this use Editor menu / Support / Email settings to author.

**Comment by henrichg** [comment]
OK, 3 events with Location sensor. All 3 are with the same location "zuhause".

I do not know, why location sensor not priperly working. By me, problem is with location accuracy.

One event: "Werktags" has 3 locations in sensor.

Warning: Location sensor has set interval 15 minutes. And for this reason, is  sensor passed/not pased by last Location scanning. Then location in Location editor is not the same as last scanned location by sensor. In edtir is immediate location, in sensor is location from last scaaning.

Question: why you do not use only Wi-Fi sensor with Connection type="Nearby"? Because in 3 events (except "Werktags") is the same SSID "TPCOL", but Connection type ="Connected".
Use only Wi-Fi sensor with connection type="Nearby" and remove Location sensor.

For event "Werktags", remove location sensor and add Wi-Fi sensor with Connection type="Not nearby" and SSID "TPCOL".

**Comment by tpcol** [comment]
Hello,

 

thanks für your analyse. 

 

Of Course for the three events with the location „zuhause“ (German for „at home“) I could only use the WIFI connection and remove the location sensor. That there the location sensor additionally is, is that I have used a LTE-WIFI-Converter for my notebook in the past.

 

For the event „Werktags“ (German for „Business days“ (Monday till Friday)) I can not use WIFI. I work for a company with our department at 3 different locations. In the offices are no WIFI witch I could use for private divices. 

 

Von: Henrich Gron ***@***.***> 
Gesendet: Dienstag, 13. Februar 2024 16:41
An: henrichg/PhoneProfilesPlus ***@***.***>
Cc: tpcol ***@***.***>; Author ***@***.***>
Betreff: Re: [henrichg/PhoneProfilesPlus] Location sensor on Samsung Galaxy S24 (Issue #120)

 

OK, 3 events with Location sensor. All 3 are with the same location "zuhause".

I do not know, why location sensor not priperly working. By me, problem is with location accuracy.

One event: "Werktags" has 3 locations in sensor.

Warning: Location sensor has set interval 15 minutes. And for this reason, is sensor passed/not pased by last Location scanning. Then location in Location editor is not the same as last scanned location by sensor. In edtir is immediate location, in sensor is location from last scaaning.

Question: why you do not use only Wi-Fi sensor with Connection type="Nearby"? Because in 3 events (except "Werktags") is the same SSID "TPCOL", but Connection type ="Connected".
Use only Wi-Fi sensor with connection type="Nearby" and remove Location sensor.

For event "Werktags", remove location sensor and add Wi-Fi sensor with Connection type="Not nearby" and SSID "TPCOL".

**Comment by henrichg** [comment]
Then sorry. Maybe bug in S24 or One UI 6.1.

In my s23 is not One UI 6.1. but maybe in march update will be.

**Comment by henrichg** [comment]
Check Settings / Location scanning, parameter "Use GPS when not in Power Save mode". Disable it.

**Comment by tpcol** [comment]
Hello and sorry for the late response. I worked the last days only from home. After a full reset of my S24 PPP works fine.
