### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [henrichg/PhoneProfilesPlus#121]
MY scanner got a big overhaul in January, and with today's release of PPP reported:

```
! repo/sk.henrichg.phoneprofilesplus_7110.apk declares sensitive permission(s):
 android.permission.READ_EXTERNAL_STORAGE android.permission.ACCESS_COARSE_LOCATION
 android.permission.ACCESS_FINE_LOCATION android.permission.ACCESS_BACKGROUND_LOCATION
 android.permission.READ_PHONE_STATE android.permission.READ_CONTACTS
 android.permission.SYSTEM_ALERT_WINDOW android.permission.CAMERA android.permission.RECORD_AUDIO
! repo/sk.henrichg.phoneprofilesplus_7110.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Several of them I was able to find the reason for (e.g. by searching issues and code), but some I couldn't find:

![image](https://github.com/henrichg/PhoneProfilesPlus/assets/6781438/0ea8432f-ec64-41ea-9998-e3be1167defb)

Could you please 1) check if I got the reasons mentioned right and 2) help me clarify the left-over "chocolate"? 3) you're of course welcome to fill the other gaps :wink:

Oh, and that `DEPENDENCY_INFO_BLOCK` is easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by henrichg** [comment]
Permissions:

- android.permission.READ_EXTERNAL_STORAGE -> for read and write PPP Settings backups to internal storage
- android.permission.ACCESS_COARSE_LOCATION -> for event "Wi-Fi sensor", "Mobile cells sensor", "Locaton sensor"
- android.permission.ACCESS_FINE_LOCATION -> for event "Wi-Fi sensor", "Mobile cells sensor", "Locaton sensor"
- android.permission.ACCESS_BACKGROUND_LOCATION -> for event "Wi-Fi sensor", "Mobile cells sensor", "Locaton sensor"
- android.permission.READ_PHONE_STATE -> for read state of phone calls for event "Call sensor",  "Radios sensor"
- android.permission.READ_CONTACTS -> for fill contact cache, required in event "Call sensor", "SMS sensor"
- android.permission.SYSTEM_ALERT_WINDOW -> for non-visible views displayed at top of screen as overlay, required is for profile parameter "Screen brightness", "Screen timeout", "Keep screen on"
- android.permission.CAMERA -> for profile parameter "Camera flash"

- android.permission.RECORD_AUDIO -> for set profile "Airplane mode" via Assistant.
I'm received email from Google wiht this text:
"We recently uncovered a highly visible user-facing issue where your app (sk.henrichg.phoneprofilesplus) causes the Android RecognitionService to break, which is potentially affecting all of your users on Android 11 or earlier.
Specifically, when a user on Android 11 or earlier sets your assistant application as the default assistant for the phone, it is expected to provide RecognitionService (speech to text) functionality to other applications on the same device as well. However, if another app requests the RecognitionService functionality and does not receive it from your assistant app, the requesting app will immediately crash. The Android RecognitionService functionality is a widely used service. To fix the issue as soon as possible, please review the below recommendation."
Result: implented in PPP. And this is reason for permision android.permission.RECORD_AUDIO requirement.

DependenciesInfo:
If I add it to gradle file, will be possible to read dependencies from apk file? Is possible to use it only in relase version of apk?

**Comment by IzzySoft** [comment]
Thanks! Adjusted (though I had to "compress" it a little to fit into the limits).

> If I add it to gradle file, will be possible to read dependencies from apk file?

By whom? That blob can only be read by Google anyway, as it's encrypted with one of their public keys. Nothing else changes by that.

> Is possible to use it only in relase version of apk?

I mostly care for the APK that goes to my repo. I cannot control what Google does on its PlayStore anyway. But there are POCs that one can hide payload in those "signing block blobs"; in our tests we were able to hide an EICAR sample there which almost no malware engine reported, or an ELF binary that went totally unnoticed. We put that into a signed APK we didn't have the signing key for, and the signature was NOT broken. Which means that opaque blobs (like here: an encrypted binary block) in general might pose danger, and thus better should not be there at all. Google of course can read their `DEPENDENCY_INFO_BLOB` as they hold the private key to decrypt it – but I'd rather not trust a monopolist to not abuse that.

So I scan for that and, on the occasion having contact with the corresponding developer, mention it along. Currently it's shown as "info" (I already have enough to do clarifying all the other details my scanner now reports). I'll probably raise it to "warning" once I have time to care for it. I hope having reduced their numbers until then by mentioning them already now…

**Comment by henrichg** [comment]
Added DependenciesInfo.

If you want, check it in this apk:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

And if is good in PPP, I will add it aslo into PhoneProfilesPlusExtender and PPPPutSettings.

**Comment by henrichg** [comment]
Also if you want decriptions for PhoneProfilesPlusExtender and PPPPutSettings permissions, I can send it in this issue.

**Comment by henrichg** [comment]
Izzy please.

**Comment by IzzySoft** [comment]
Sorry Henrich – I have no idea what is eating half my Github notifications. Only your last ping reached me… Looking now…

* I can confirm `DEPENDENCY_INFO_BLOCK` is gone from the APK at GDrive, looks fine to me, thanks!
* And yes, I gladly take the other permission explanations here and add them to the apps.

**Comment by henrichg** [comment]
Good, DependenciesInfo added also into PhoneProflesPlusExtender and PPPPutSettings gradle.

Permissions:

PhoneProfilesPlusExtender:
- android.permission.RECEIVE_SMS -> for read SMS, required for PPP event ""SMS/MMS sensor"
- android.permission.RECEIVE_MMS -> for rwad MMS, required for PPP event ""SMS/MMS sensor"
- android.permission.READ_PHONE_STATE -> for check incomming calls, required for PPP event "Call sensor"
- android.permission.PROCESS_OUTGOING_CALLS -> for check of outgoing calls, required for PPP event "Call sensor"
- android.permission.READ_CALL_LOG ->  for check outgoing calls, required for PPP event "Call sensor"
- android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS -> for set "Ignore battery optimization" for Extender.

- sk.henrichg.phoneprofilesplusextender.ACCESSIBILITY_SERVICE_PERMISSION" -> Extender own permission. PPP must use it, when send command to Extender.

PPPPutSettings:
- android.permission.WRITE_SETTINGS -> for change device Settings

- sk.henrichg.pppputsettings.PPP_PUT_SETTINGS_PERMISSION -> PPPPS own permission. PPP must use it, when send command to PPPPS.

**Comment by IzzySoft** [comment]
I thank you! And I'd say "issue solved", so feel free to close unless you need it as reminder for something else?

**Comment by henrichg** [comment]
You can flag this issue as "Solved". 

But what if permissions will be added/removed in the future? Because it will. :-)
And those pngs with the permission list, where will they appear? In IzzyOnDroid repository in PPP, PPPE, PPPPS page?

**Comment by IzzySoft** [comment]
> But what if permissions will be added/removed in the future? Because it will. :-)

My scanner will alert me. Those alerts happen when a "allow-listed" permission is no longer requested – or when a not-yet-covered "sensible permission" was found. For new, non-sensitive permissions (or any other adjustments you'd like), you can always ping me (in the hope nobody's eating notifications again; currently I've simply left the tab open in the browser to make sure, but that's just today :wink:).

> And those pngs with the permission list, where will they appear? In IzzyOnDroid repository in PPP, PPPE, PPPPS page?

Exactly, e.g. [here](https://apt.izzysoft.de/packages/sk.henrichg.phoneprofilesplus/) (scroll down to the "packages" and expand the permissions :smiley:) I've just sync'ed those 3 manually now so you can see them right away (would have happened with the next regular sync around 7 pm UTC otherwise). Unfortunately I have no means to transfer that to the index for F-Droid clients on device; all requests for such in the past have been blocked by the F-Droid tech lead.

**Comment by IzzySoft** [comment]
Oops, missed the "close" button :see_no_evil:

**Comment by henrichg** [comment]
Good, thanks. Permissions are in web version and also in Droid-ify, which I recommend for users.
