### ISSUE TITLE
Airplane Mode

### ISSUE THREAD

**Issue by androiddev16** [henrichg/PhoneProfilesPlus#122]
Hello sir ! can you help me to separate the logic of airplane mode by using default assistant. I tried but i failed. my scene is this that i want that there will be a button on which i clicked and the airplane mode will toggle.

**Comment by androiddev16** [comment]
Hello sir ! I need your help. Actually i was creating my own app to toggle airplane mode which will be connect to my Python script which will be running in Termux apk. I will toggle airplane mode from my script. i will handle it. the main problem is that i was unable to implement the logic of airplane mode toggle using assistant as your app is doing, Can you please help me about this? this is very important for me

**Comment by henrichg** [comment]
- https://github.com/henrichg/PhoneProfilesPlus/blob/master/phoneProfilesPlus/src/main/res/xml/assist_metadata.xml
- https://github.com/henrichg/PhoneProfilesPlus/blob/master/phoneProfilesPlus/src/main/java/sk/henrichg/phoneprofilesplus/PPVoiceInteractionSession.java
- https://github.com/henrichg/PhoneProfilesPlus/blob/master/phoneProfilesPlus/src/main/java/sk/henrichg/phoneprofilesplus/PPVoiceServiceBroadcastReceiver.java
- https://github.com/henrichg/PhoneProfilesPlus/blob/master/phoneProfilesPlus/src/main/java/sk/henrichg/phoneprofilesplus/PPVoiceServiceBroadcastReceiver.java
- https://github.com/henrichg/PhoneProfilesPlus/blob/master/phoneProfilesPlus/src/main/java/sk/henrichg/phoneprofilesplus/PPVoiceSessionService.java

How to use it is in ActivateProfileHelper.setAirplaneMode():
- PPP must be set as default assistant
        if (isPPPSetAsDefaultAssistant(context)) {
                Intent intent = new Intent(PPVoiceService.ACTION_ASSISTANT);
                intent.putExtra("ACTION", Settings.ACTION_VOICE_CONTROL_AIRPLANE_MODE);
                intent.putExtra(Settings.EXTRA_AIRPLANE_MODE_ENABLED, mode);
                context.sendBroadcast(intent);
        }

ActivateProfileHelper.isPPPSetAsDefaultAssistant()
```
static boolean isPPPSetAsDefaultAssistant(Context context) {
    boolean assistIsSet = false;

    ComponentName compName = null;
    try {
        Method declaredMethod = UserHandle.class.getDeclaredMethod("myUserId", new Class[0]);
        declaredMethod.setAccessible(true);
        Integer num = (Integer) declaredMethod.invoke(null, new Object[0]);
        if (num != null) {
            @SuppressLint("PrivateApi")
            Object newInstance = Class.forName("com.android.internal.app.AssistUtils").getConstructor(new Class[]{Context.class}).newInstance(new Object[]{context});
            Method declaredMethod2 = newInstance.getClass().getDeclaredMethod("getAssistComponentForUser", new Class[]{Integer.TYPE});
            declaredMethod2.setAccessible(true);
            compName = (ComponentName) declaredMethod2.invoke(newInstance, new Object[]{num});
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    if (compName != null && compName.getPackageName().equals(context.getPackageName())) {
        assistIsSet = true;
    }
    if (!assistIsSet) {
        String string = Settings.Secure.getString(context.getContentResolver(), "assistant");
        if ((string != null) && (string.startsWith(context.getPackageName()))) {
            assistIsSet = true;
        }
    }

    return assistIsSet;
}

```

**Comment by henrichg** [comment]
By me is better using Shizuku (replaces root calls = root is ot required):

```
if (ShizukuUtils.hasShizukuPermission()) {
    synchronized (PPApplication.rootMutex) {
        if (Build.VERSION.SDK_INT <= 27) {
            String command1;
            String command2;
            final String AIRPLANE_MODE_ON = "airplane_mode_on ";
            if (mode) {
                command1 = COMMAND_SETTINGS_PUT_GLOBAL + AIRPLANE_MODE_ON + "1";
                command2 = COMMAND_AM_AIRPLANE_MODE + StringConstants.TRUE_STRING;
            } else {
                command1 = COMMAND_SETTINGS_PUT_GLOBAL + AIRPLANE_MODE_ON + "0";
                command2 = COMMAND_AM_AIRPLANE_MODE + StringConstants.FALSE_STRING;
            }
            try {
                ShizukuUtils.executeCommand(command1);
                ShizukuUtils.executeCommand(command2);
            } catch (Exception e) {
                //Log.e("ActivateProfileHelper.setAirplaneMode", Log.getStackTraceString(e));
            }
        } else {
            String command1;
            if (mode) {
                command1 = COMMAND_AIRPLANE_MODE + " enable";
            } else {
                command1 = COMMAND_AIRPLANE_MODE + " disable";
            }
            try {
                ShizukuUtils.executeCommand(command1);
            } catch (Exception e) {
                //Log.e("ActivateProfileHelper.setAirplaneMode", Log.getStackTraceString(e));
            }
        }
    }
}

```

**Comment by androiddev16** [comment]
@henrichg thank you soo much sir. Let me try this approach . Actually i did this approach but my app was not working. Its screen keeps blinking all the time when i set it to default assistant. Let me try your approach again today . I will let you know about the progress. Thanks for your kind reply !

**Comment by androiddev16** [comment]
@henrichg Hello sir ! i created the app as you provide me the settings. but my app have no effect. Can i send you my app to debug ??? Please this is very important to me .

**Comment by henrichg** [comment]
Debug it yourself in Android emulator or in physical device. I debug my
applications in physical device.

Dňa ne 18. 2. 2024, 17:57 androiddev16 ***@***.***>
napísal(a):

**Comment by androiddev16** [comment]
@henrichg Thanks sir i have successfully created the app. Thanks for your kind reply and help....
