### ISSUE TITLE
OxygenOS 14 screen time out doesn't change

### ISSUE THREAD

**Issue by spart0n654** [henrichg/PhoneProfilesPlus#123]
This is not a deal breaker by any means, just wanted to let you know. I have both apps and all permissions including root but any profile that changes the screen time out doesn't give any errors it just doesn't change the settings.

**Comment by henrichg** [comment]
Tested in OxigenOS 14, Required is root, Shizuku.

If you want, install this beta version:
https://drive.google.com/file/d/1upFu_8QJrlmHVqHA7lGg7fjzwuNMEwBz/view?usp=drivesdk

**Comment by spart0n654** [comment]
That beta fixed it! You rock my dude
