### ISSUE TITLE
[Feature Request] Call management

### ISSUE THREAD

**Issue by N1N74** [henrichg/PhoneProfilesPlus#124]
Option to automatically decline calls and send SMS message about unavailability would greatly enhance the app's usability. It would be cool if the app could also decide on letting a call ring based on contacts of if the same caller called twice. Even automatically declining after set period of time would be very useful.

**Comment by henrichg** [comment]
What you means automatically decline call? After detection of incomming call PPP must end it and sensd sms?
And yes is better to add "Decline after (sec)" with seconds as parameter. Will be added.

PPP supports only tel. numbers in phone Contacts.

Calling twice? Hm, maybe. :-)

(For me: use this for decline call: https://stackoverflow.com/questions/48614042/perfectly-blocking-incoming-calls-in-android)

**Comment by N1N74** [comment]
Yup, would be nice if the app can end calls and send SMS like "Hey, I'm busy at work. If it is urgent, call me again to get connected." 
We can also use this when sick or sleeping so we can still get urgent calls without disturbance.

**Comment by henrichg** [comment]
OK, I will implemeted it. But still without "calling twice".

**Comment by henrichg** [comment]
Sorry, but is not possible to end call when PPP is not set as default dialer. But PPP is not dialer. :-(

**Comment by N1N74** [comment]
:-(
Thanks for looking into this, anyway ^^
Well, SMS to numbers with missed calls can still be very useful.

**Comment by henrichg** [comment]
Maybe will be possible to end ringing call with this:
https://developer.android.com/reference/android/telecom/CallScreeningService

But with this is not possible to use ringing duration. Application must end call (reject it) max. 5 seconds after incomming call detection by this service. :-(

**Comment by henrichg** [comment]
CallScreeningService is not good. Because it won't starts PPP event. It does not generate a ringing state and a call end state when the service rejects the call. :-(

**Comment by henrichg** [comment]
Then? How about sending SMS? 
Send it in background?
Or interactive? For blocked calls generating notification and you must click it to send sms?

**Comment by N1N74** [comment]
I think background because missed calls means user is not near phone. 
Reject call with SMS button is already there in some phone apps.

**Comment by henrichg** [comment]
Please write me examples of sms texts you want to send. Thanks.

**Comment by N1N74** [comment]
Sure, could be like 
- hey, I'm asleep now but I'll call back later
- hey, I'm in classroom right now, I'll call back later
- hey, do-not-disturb is turned on but I'll call back later

**Comment by henrichg** [comment]
OK, then not tel. number, contact name in sms texts. Good, will not be impleneted. Maybe in future.
Implemented is sms send, will be tested and then releaased beta. Please wait.

**Comment by henrichg** [comment]
Please test this beta version:
https://drive.google.com/file/d/1upFu_8QJrlmHVqHA7lGg7fjzwuNMEwBz/view?usp=drivesdk

Added is into Profile, parameter "Phone call".

**Comment by N1N74** [comment]
Hello, sorry, I'd love to test it but I won't be able to in this month.

Thank you for trying to implement this feature, I will definitely test it if I can find the time but I may not be able to.
