### ISSUE TITLE
Low volume repeating caller's name

### ISSUE THREAD

**Issue by orlproi** [henrichg/PhoneProfilesPlus#126]
Good morning.
On 'Samsung' phones when earphones are connected the repetition of the caller's name is heard softly, probably linked to the volume of the music. Can't the alert volume be increased if earphones are plugged in even if the music volume is low?

**Comment by henrichg** [comment]
Maybe low volume is System or Accesibility prompts in profile.

**Comment by orlproi** [comment]
All maxed out minus 'media' set to 7/15.
And the audio profile set to 'Vibration'.
I also tried setting to other modes.
It's probably a factory setting thing.
If I raise the volume of 'Media' the volume of the alert also increases.
You should separate the volume of the music and that of the caller name announcement.
Or connect it to the alarm volume.

**Comment by henrichg** [comment]
Wait, wait, wait. 😀

You using any application for play caller name? Or it is in-system feature?

PPP only change channel volumes in system. Is not possible to change volume channel in applications. 

If you using for this third-party application and is possible to change channel in it, change it in application.

**Comment by henrichg** [comment]
Wait, wait, wait. 😀

You using any application for play caller name? Or it is in-system feature?

PPP only change channel volumes in system. Is not possible to change volume channel in applications. 

If you using for this third-party application and is possible to change channel in it, change it in application.

Edit: Check "Sound assistant", maybe this helps you. It is module of Good Lock app.

**Comment by orlproi** [comment]
You are using the system application.
But I also use 'Free Notification Reader' so it's this that limits my volume.
Now I'll check, I have to find the right settings... Thanks

**Comment by orlproi** [comment]
Having found balance with the earphones, I had set it to 'vibration' while I still have to set 'sound' as the announcement is given through the ringtone channel.
