### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by HomemadeAdvanced** [henrichg/PhoneProfilesPlus#127]
According to ExodusPrivacy there are the Trackers Google CrashLytics and Google Firebase Analytics included in the app. I have not found an option in the settings of the app to disable these trackers. Are they disabled by default or only for debug purposes?
Thanks in advance.

**Comment by henrichg** [comment]
In PPP is not used Crashlytics and Firebase. 
Crashlytics is not used since version 5.0. And Firebase never been used.

PPP was removed form Google Play when 5.0 was released. And from this version was removed also: Google Play Services, Google Maps, Craslytics. Was replaced with osmdroid, ACRA.

Upgrade to latest version (6.4.1.1).

**Comment by HomemadeAdvanced** [comment]
Allright thanks, good to know. Is there an option to disable ACRA?

**Comment by henrichg** [comment]
No, why you need it? ACRA is only for send e-mail, when PPP crashes.
Generated is notification and when user click it, opened is e-mail app a user can send crash report to me. Crash report attachment is txt file.

**Comment by HomemadeAdvanced** [comment]
Okay, so I am glad to hear that there is no automatic communication that can cause a privacy issue. I'm concerned about that because the app has a lot of privileges.

**Comment by henrichg** [comment]
In PPP is not any communication with other servers. With one exception: 
- ACRA library works in device only. Detects crasi in PPP (is Andrid API for this) and opens enami application. Thats all
- osmodroid: yes this communicate with osmdroid server, read from it map data and displays map from these data. But only read, not write to osmdrod servers.

Yes more, more permissions. But similar as Tasker, Macrodroid, Automate,... PPP is automate application. It must using these permissions.

**Comment by HomemadeAdvanced** [comment]
Allright thanks for the detailed explanation!
