### ISSUE TITLE
[Feature Request]: Activate tile with profile

### ISSUE THREAD

**Issue by Rathmox** [henrichg/PhoneProfilesPlus#129]
Feature:

Allow a profile to interact with a quick settings tile and click on it multiple times until it reaches a certain state.

Context:

I use syncthing to share my files between my devices.

To save battery, it does not run 100% of the time.

What I want is to activate it automatically when I'm home and disable it when I'm not home

It can do that with a quick settings tile.

**Comment by henrichg** [comment]
Sorry, by me this is not possible. Direct call of tile is not possible. It is special service and this is used by system, not possibe to call it from third-party applicaitons. 
Maybe only with click to tile. For this, check Tasker plugin AutoInput for simulating clicks to gui.

**Comment by Rathmox** [comment]
Ok thanks
