### ISSUE TITLE
[bug fix] Wifi sensor fix

### ISSUE THREAD

**Issue by Pankovea** [henrichg/PhoneProfilesPlus#132]
The Wi-Fi connection search sensor only works if geolocation is enabled. 

I have an Honor X8b Currently configured with a Wi-Fi sensor that is not connected to an access point. But when geolocation is disabled, the sensor still works. Although it should not have worked because he does not have access to this data.

**Comment by Pankovea** [comment]
I'm trying on another device and the behavior is exactly the same.
The sensor settings are as follows
![Screenshot_20240612_233332](https://github.com/henrichg/PhoneProfilesPlus/assets/114323250/7b346246-c21f-4158-98e8-8e5436248603)
The result of the work is as follows:
1. 
![01](https://github.com/henrichg/PhoneProfilesPlus/assets/114323250/bf8ebbf2-f189-4284-bb4e-bbb05e420d0a)
2. 
![02](https://github.com/henrichg/PhoneProfilesPlus/assets/114323250/614560e8-a77d-4b71-8f18-8642ab8e2867)

**Comment by henrichg** [comment]
You do not using Wi-Fi scanning. In "Connection type" is configured "Not connected". This do not use wifi scanner, only check for connect/disconnect from  wifi.

And this "Connection type" working only when Loaction is enabled?

**Comment by Pankovea** [comment]
I've tried both ways.: Connected to Wi-Fi and located nearby. It's just that in this case it's more revealing.

My device is Honor X8b (Android 13), Xiaomi_74A6 is my router.
My second device in the same behaviour is Redmi 9 pro (Android 12). 
But my third device works correctly - Redmi Note 5 (Android 9). Moreover, it works correctly even without turning on geolocation. And even in scan mode.

What could be the problem?

**Comment by henrichg** [comment]
Hm yes, if Location is disabled, sensor is passed. OK I must fix it.
Tested in my Huawei P40.

**Comment by Pankovea** [comment]
Thanks.

**Comment by henrichg** [comment]
Ok, problem is with security in Android.

1. Is not possible to get connected SSID. It returns: SSID=<unknown ssid>
2. Also is not possible to get configured SSID List from device Settings. It returns empty list.

Result: Location MUST be enabled to get proper connected SSID.

**Comment by Pankovea** [comment]
In case when location is turned off, the sensor must not be triggered.

**Comment by henrichg** [comment]
Hm "workaround" implemented. But your wifi sensor will be not passed (green), when Location is dislabled. In both Connection types: "Connected", "Not connected".
Is this as you want it?

**Comment by Pankovea** [comment]
I think it will be correct behaviour. Because if the sensor does't know about the actual state of the Wi-Fi module, then it should not do anything by default.
Perhaps this is my special case. Maybe you can add a setting for this?

**Comment by henrichg** [comment]
Exists parameter notAllowedWifi. If is true, sensor will do nothing, pass status is not changed.
By me this not good, because if sensor is passed and you disable Location, sensor pass status do not change. Stays passed.

For this reason I'm impleneted: if Location is disabled, force set pass status to false.

**Comment by Pankovea** [comment]
Awesome!
I see you've already made a commit. Can I get the apk and test it?

**Comment by henrichg** [comment]
OK. If ypu want, install and test this beta version:
https://drive.google.com/file/d/13V2Zkb5W4VxNdMiXfsRs5iuWflt2xasY/view?usp=drivesdk

**Comment by Pankovea** [comment]
I have tested the behaviour and now it doesn't work correctly in that place.
![03](https://github.com/henrichg/PhoneProfilesPlus/assets/114323250/7abf0ff1-18a3-47cb-b61d-84e05f2f05ca)
You also need to mark that you need access to geolocation like here
![Screenshot_20240614_093340](https://github.com/henrichg/PhoneProfilesPlus/assets/114323250/a19a2e13-2904-4a66-88c0-5f6f4c6ba32c)

**Comment by henrichg** [comment]
1. No, this is correct. Because if Location is disabled, sensor pass status is forced to false.

2. Information about disabled Location will be added in next beta.

**Comment by Pankovea** [comment]
Now it works good. 
But it may be necessary to make the sensor's status red. As well as other parts where the incorrect settings.
Thus, it will be clear that the sensor is inoperable.

**Comment by Pankovea** [comment]
> 1. No, this is correct. Because if Location is disabled, sensor pass status is forced to false.

I meant that the behavior is expected for us, but not for the user. There were no notes.

**Comment by henrichg** [comment]
But if Location is disabled, is not possible to get connected SSID.

Again:
Problem is with security in Android.

- Is not possible to get connected SSID. It returns: SSID="<unknown ssid>"
- Also is not possible to get configured SSID List from device Settings. It returns empty list.

Result: Location MUST be enabled to get proper connected SSID.

**Comment by Pankovea** [comment]
I understand that. that's why I'm saying that the user needs to highlight it in red.

**Comment by Pankovea** [comment]
We have been using your application for many years. and these settings were good for turning on the profile "outdoors". and there were problems with the new device. Thank you for your efforts and for your prompt response.

**Comment by henrichg** [comment]
OK, added also generaiton of error notificaton + redo color, when Location is required, ut not enabed.
If you want, install this beta:
https://drive.google.com/file/d/13V2Zkb5W4VxNdMiXfsRs5iuWflt2xasY/view?usp=drivesdk

**Comment by Pankovea** [comment]
Great! Thanks. 🤝

**Comment by xkonglong** [comment]
This fix caused Profile to be deactivated in some cases.

**Comment by Pankovea** [comment]
> This fix caused Profile to be deactivated in some cases.

What do you mean?
