### ISSUE TITLE
Play protect reporting PPP 6.5 as dangerous

### ISSUE THREAD

**Issue by ScratMan** [henrichg/PhoneProfilesPlus#133]
I upgraded my Google phone from Pixel 6 Pro to Pixel 8 Pro, and reinstalled PhoneProfilesPlus 6.5 on my phone, but the Play Protect detects the app as malicious.

![Screenshot_20240715-213936](https://github.com/user-attachments/assets/ccc5244a-dd60-45f0-8d18-c35c1408398e)

I tried to install the application via Droid-ify and by ADB, but it's always the same issue in the end. The two settings and extender apps are not detected as malicious.

How to fix that ? I never saw this on my Pixel 6 Pro.
Thanks

**Comment by henrichg** [comment]
In Pixel 8 is which Android? 15 beta? If yes, maybe this is problem. I will testing it in my Pixel 6 with 15 beta.

**Comment by henrichg** [comment]
Hm, not good. Also in my Pixel 6 with Android 15 beta is this problem. But is possible to click "Install anyway" and will be installed.

**Comment by henrichg** [comment]
In your device was PPP activated and you upgraded it to 6.5? Because in your screenshot is not "Install anyway", only button "Uninstall".

**Comment by ScratMan** [comment]
> In Pixel 8 is which Android? 15 beta? If yes, maybe this is problem. I will testing it in my Pixel 6 with 15 beta.

No, it's still on Android 14. 

> In your device was PPP activated and you upgraded it to 6.5? Because in your screenshot is not "Install anyway", only button "Uninstall".

I received a message when installing PhoneProfilesPlus (same for extender and settings apps), saying the app may be malicious and recommending not to install it. I could select "Install anyway", as you mention, and the app is installed and working. But when I go to Play Store app, click on my profile icon on the top right corner and select "Manage applications" to see the available updates, I can see the message shared above saying my phone's security is compromised because PhoneProfilePlus is malicious.

**Comment by henrichg** [comment]
Ok. Android 14.

PPP uses functionalities, which may by malicious for Google Play Protect. Uses root/Shiziku, must be in target 28, configure protected settings in system...
And, if you use "Install anyway",  Google Play will always displaying it as malicious.

Maybe it is Pixel exclusive, because in my  Galaxy S23, Android 14, latest One UI, is not PPP displayed as malicious and is installable without "Install anyway". Even when is installed apk from device storage.

**Comment by henrichg** [comment]
Maybe in 6.5 apk is bug and for Google Play Protect in Pixel is marked as malicious.
Soon will be released 6.5.1. And in it are new versions of some libraries, new version on Android Studio with upgraded Gradle. 
Maybe this will not be malicious. I will testing it.

**Comment by henrichg** [comment]
OK tested latest 6.5.1b. Must be istalled with "Install anyway", but Google Play Protect do not mark is as malicious.
But: not allowed to set "Draw over apss" perission. :-( Because of financial apps. Android beta? Maybe.

**Comment by henrichg** [comment]
Released new version 6.5.1. Installed with Droid-ify.

Currently is marked as malware, in my S23, PhoneProfilesPlusExtender (PPPE), not PhoneProfilesPlus (PPP). 
And yes, released is also new version of PPPE, installed in my S23 with Drodid-ify. And used is in it latest gradle plugin, as in PPP

Maybe I found why. In PPPE is used old gradle plugin. will be fixed.

**Comment by ScratMan** [comment]
I confirm, after installing the updates, PPP is now seen as safe, and PPPE is seen as potentially malicious.

**Comment by henrichg** [comment]
In GitHub is new version of PPPE. Download and install it.
https://github.com/henrichg/PhoneProfilesPlusExtender/releases/tag/8.1.7

**Comment by ScratMan** [comment]
I confirm the fix
