### ISSUE TITLE
[Feature request] Wallpaper smoothing

### ISSUE THREAD

**Issue by edricus** [henrichg/PhoneProfilesPlus#136]
By default when a profile set a wallpaper it doesn't smooth it.
The wallpaper appear very pixelated when it's too large and downscaled.

**Comment by henrichg** [comment]
Pleae e-mail me wallpaper and write mobile type, Android version. Thank you.

**Comment by henrichg** [comment]
And: you changed wallpaper for:
1. home + lock screen
2. home screen only
3. lock screen only
?

**Comment by edricus** [comment]
> And: you changed wallpaper for:
> 
>     1. home + lock screen
> 
>     2. home screen only
> 
>     3. lock screen only
>        ?

Home+Lock screen
Phone is a Sony Xperia 10VI on Android 14
I can post some screenshots :
Wallpaper set from wallpaper and style
![base](https://github.com/user-attachments/assets/b80095f0-ec67-4b76-8d4b-c6a3b6e9117a)
Wallpaper set from ppp
![ppp](https://github.com/user-attachments/assets/db166a0b-718e-4f99-a9f2-bced3c24dd82)
It look the same from lock screen

**Comment by henrichg** [comment]
OK, please send me your wallpaper. I'm tested mine in Pixel 3a and is not pixelated.

**Comment by edricus** [comment]
> OK, please send me your wallpaper. I'm tested mine in Pixel 3a and is not pixelated. Also in Pixel 6, Android 15 beta.

![HD-wallpaper-minimalism-simple-background-landscape-mountains](https://github.com/user-attachments/assets/7739248f-6452-42d0-9c32-8b2b96a3de12)

**Comment by henrichg** [comment]
Tested in Pixel 6, and is not pixelated. 
![Screenshot_20241003-095739](https://github.com/user-attachments/assets/7b7cf610-aabe-4d3f-a543-3e80fe18575c)

**Comment by henrichg** [comment]
PPP uses:

1. converts Uri (your wallpaper.jpg) to Bitmap:
`decodedSampleBitmap = ImageDecoder.decodeBitmap(ImageDecoder.createSource(appContext.getContentResolver(), uri));
`
2. sets wallpaper into system:
`wallpaperManager.setBitmap(decodedSampleBitmap, null, true, flags);`

Where is problem then? In conversion from Uri to Bitmap? Or in WallpaperManager.setBitmap()? 

Maybe using for ImageDecoder some conversion parameters. I will looking on it.

**Comment by henrichg** [comment]
Test this PPP beta. Maybe wallpaper will be better:
https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

**Comment by henrichg** [comment]
OK this is better: https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

Interesting. 
- In Samsung Galaxy S21 is wallapaper centered both in home and lock screen.
- In Pixel 6 is scrollable in home screen (OK), but not centered in lock screen :-(.

**Comment by henrichg** [comment]
New version. Fixed also lock screen:
https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

**Comment by edricus** [comment]
> New version. Fixed also lock screen: https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

The issue is fixed for me ! Thanks you
