### ISSUE TITLE
[BUG] Call sensor do NOT detects call from contact from selected GROUP 

### ISSUE THREAD

**Issue by StanTody** [henrichg/PhoneProfilesPlus#137]
Version: 6.5.1.1, Android 14, OneUI 6.0
Steps to reproduce:
* An event has set up call sensor with 2 selected contact GROUPS (groups are in phone contacts, not in Google contacts).
* When a contact from selected groups is calling, event does NOT executes.
* When for the same event call sensor is set up for exact CONTACT (the same as above), the event executes SUCCESSFULLY.

**Comment by henrichg** [comment]
Hm, I must test it. 
How you setup contact group only in phone (not synced with Google)? Thanks.

**Comment by henrichg** [comment]
I'm configured one group in One UI Contacts application. Group exists, is possible to cadd it in PPP Call sensor, but in it are not contacts. PPP displays 0 contacts in it. By me, One UI Contacts application do not proprely working with Android SDK API for managing Contacts. Hm.

**Comment by StanTody** [comment]
I am using TruePhone for managing contacts and PPP shows actual count of contacts in the groups (14 in my case). And yes, I have 2 versions of groups too - Phone and Google. It is normal, AIK.

**Comment by just-Nob** [comment]
To set up contact group in phone only:

I think that TruePhone adds a new local account (which isn't synchronized with Google) where the user is able to store contacts.
I'm using MyLocalAccount for that (although MyLocalAccount is also closed source like TruePhone, I consider MyLocalAccount trustworthy; it's from the same author like there well known MyPhoneExplorer app).

I don't have much time at the moment, but if I can manage it, I will try to reproduce the issue with MyLocalAccount.

Anyway, MyPhoneExplorer could be a good countercheck to test whether the described issue is caused by TruePhone or PPP.

**Comment by StanTody** [comment]
Here are some more tests:
  " I have created a new group with built-in Contacts app and added one contact to it (again with built-in app) - same result, the event does NOT executed.
   " I have uninstalled PPP (with Clear data) and installed a old version (4.2.0.3) with same settings, profiles and events - same result.
   * I have done same test on another phone with A14 and Hyper OS - same result.
   * On my old Mi5 (A7) above old version DOES work CORRECTLY with same settings and with same contacts (again managed with TruePhone).

Conclusion: may be the problem is in A14 ?

**Comment by henrichg** [comment]
Checked again group created yesterday. And is synced with Google account.
PPP displays for Google account added contact. In mobile, Samsung account stays 0.
Galaxy S23, Android 14.

Result: problem is, by me, changed format of data in mobile, Samsung account.

Next test tomorrow: Galaxy S10, Android 11.

**Comment by henrichg** [comment]
Galaxy S10:

PPP uses this DB query:
String[] projection = new String[]{
        ContactsContract.Groups._ID,
        ContactsContract.Groups.TITLE,
        ContactsContract.Groups.SUMMARY_COUNT,
        ContactsContract.Groups.ACCOUNT_TYPE
};
String selection = ContactsContract.Groups.DELETED + "=0";
Cursor mCursor = context.getContentResolver().query(ContactsContract.Groups.CONTENT_SUMMARY_URI, projection, selection, null, null);

And return is:

2024-10-04 13:37:13.667 18282-18844 ContactGro...tGroupList sk.henrichg.phoneprofilesplus        E  count=0
2024-10-04 13:37:13.667 18282-18844 ContactGro...tGroupList sk.henrichg.phoneprofilesplus        E  accountType=com.osp.app.signin

2024-10-04 13:37:13.667 18282-18844 ContactGro...tGroupList sk.henrichg.phoneprofilesplus        E  count=0
2024-10-04 13:37:13.667 18282-18844 ContactGro...tGroupList sk.henrichg.phoneprofilesplus        E  accountType=vnd.sec.contact.phone

2024-10-04 13:37:13.667 18282-18844 ContactGro...tGroupList sk.henrichg.phoneprofilesplus        E  count=1
2024-10-04 13:37:13.667 18282-18844 ContactGro...tGroupList sk.henrichg.phoneprofilesplus        E  accountType=com.google

Only for ACCOUNT_TYPE="com.google" is returned 1 contacit. For "com.osp.app.signin" and "vnd.sec.contact.phone" is returned 0.

I do not know, why. Maybe for account types with count = 0 is are not contacts added count of contacts. One UI bug? Maybe.
Then, maybe I must rewrite, how to get contacts in groups. I will looking on it.

**Comment by henrichg** [comment]
Hm, changed, how to get count of contacts in group (SUMMARY_COUNT is not used), but my contact added to group is only in accountType=com.google. One UI Contacts app do not add it into 2 other accountTypes. Then bug is in Contacts app.

Then use in PPP Google accountType, if your contacts app adds contact to this accountType.

And: Contacts app do not displays groups: "My contacts" but PPP yes (exists Samsung and Google accoutType). Next bug in Contacts? Hm, intersting.

**Comment by henrichg** [comment]
Intersting. Group added in S10 is synced with S21 and in S21 is 1 contact in it. This is OK.
But group in S21 is only with accountType=Samsung and is empty. How Samsung syncing contacts, I do not know. :-)

**Comment by StanTody** [comment]
As I know, different accounts are separate "containers" - so contact, added to group "Family" in Google account is NOT visible in group "Family" in Samsung account. I.e., the two above groups are different, regardless equal names.

So, may be groups must be kept and handled as name+account ?

**Comment by henrichg** [comment]
Hm, fixed is filling contacts with groups. One contact may by in several groups (group_id), but name of group may be the same for several group_id.
For example my own contact has 3 tel. numbers and after this fix is displayed 3 tel. numbers in "Starred" Google group.

Problem persists: All contacts are in "Coogle" actionType. "Samsung" and "Phone" stays empty, even when also these actionTypes are filled with contacts.

If you want, install this fix:
https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

**Comment by StanTody** [comment]
Unfortunately, the test version requires newer version of the Extender

**Comment by henrichg** [comment]
8.1.6 is required. You have older version? In Droid-idy, GitHub is 8.1.7.
Install it from Droid-ify (recommended) or GitHub.

GitHub: https://github.com/henrichg/PhoneProfilesPlusExtender/releases

**Comment by StanTody** [comment]
Unfortunately, the call sensor still does NOT detects call from selected (local) group :'(
 
Samsung S23, A14, One UI 6.0

**Comment by henrichg** [comment]
Check "Contact groups" parameter. In it is displayed count of contacts in each group.
In my S23, only "Restored from device Samsung..." are in "Phone application" group. All others are in "Google account".

**Comment by henrichg** [comment]
Which application you using? I will test it. Write me download link, name. Thanks.

**Comment by StanTody** [comment]
"Check "Contact groups" parameter" - in PPP 6.5.1.1 and in 6.6b when I setting up the parameter I CAN see CORRECT count of the contacts in each group incl. these from Phone account (BTW, I don't use Google for storing and syncing contacts, so ALL my contacts are in Phone account, separated by groups -see attachment). I use True Phone for managing contacts, as I described before. 
![Screenshot_20241005_110413_PhoneProfilesPlus](https://github.com/user-attachments/assets/899046e5-6033-4c1d-a0c4-03a75ae4ed4a)
![Screenshot_20241005_110403_PhoneProfilesPlus](https://github.com/user-attachments/assets/9ccc99d2-821c-4eb2-9c80-58ada885cf8e)
https://play.google.com/store/apps/details?id=com.hb.dialer.free

**Comment by henrichg** [comment]
Installed True caller.
1. Which application is set as default dialer in your device? In mine is True caller.
2. Created group is in "Phone" accountType? I'm created  it in "Phone".
3. You tested incomming or outgoing call?

True caller do not allow add into group contacts, which not are in Phone accountType. Ok added new contact to Phone accountType, then is possible to add it to Phone accountType group.

One UI Contacts application display also contact and group from True caller. Good.

Will be tested. Pleae wait.

**Comment by henrichg** [comment]
Hm, not working. I must debugging it.

**Comment by StanTody** [comment]
On my device I use True Phone and it is default call app. (not True caller - they are different, see link above).

I am testing incoming call.

**Comment by henrichg** [comment]
Then write mi link to true caller. Because your link is for true phone. 😀

**Comment by henrichg** [comment]
Please test this: Do Exit in PPP menu and start PPP again. It fixes the contact and contact group cache used in PPP.
Because I had a problem too. The cache was not updated after the changes in True Phone. And quitting and starting PPP fixed the cache.

I will debugging create/update of these caches (must be used cache, and generate is in background, because contacts BD is very slow).

**Comment by StanTody** [comment]
In my case contacts are in the corresponding groups till stone age ;) , so cache is not of importance

**Comment by henrichg** [comment]
Cache is importance. Events use only cache.
I added logging into PPP. Will be tested by me and then send you new beta version. Stay tuned. :-)

**Comment by henrichg** [comment]
OK, test this beta:
https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

After end of tests do this:
In Editor menu use: "Support"/"E-mail debug log files to author".

Thanks.

**Comment by StanTody** [comment]
"In Editor menu use: "Support"/"E-mail debug log files to author"" -> done.

**Comment by henrichg** [comment]
And where is the email with the log file :-)

**Comment by StanTody** [comment]
I thought it will be sent automatically from the menu.... Now I have found and sent the log file.

**Comment by henrichg** [comment]
"E-mail debug log files to author" opens your mail app send screen with created e-mail and added log.txt And you must only send it. :-)

**Comment by henrichg** [comment]
In group are only these phones:
found in group _phoneNumber=+359898694948
found in group _phoneNumber=+35986752696
found in group _phoneNumber=+359882383835
found in group _phoneNumber=+359885304908
found in group _phoneNumber=+359889970193
found in group _phoneNumber=+359 87 766 7186
found in group _phoneNumber=+359888584029
found in group _phoneNumber=+359876375284
found in group _phoneNumber=+359888703653
found in group _phoneNumber=+359 87 801 0464
found in group _phoneNumber=+359888230652
found in group _phoneNumber=+359893483181
found in group _phoneNumber=+359887857993
found in group _phoneNumber=+359 89 583 0128
found in group _phoneNumber=+359 88 770 0913
found in group _phoneNumber=+359894242781
found in group _phoneNumber=+359885838360

+359899977917 in not in this group.

**Comment by henrichg** [comment]
Read e-mail. 
For security reason (phone numbers in it) is better to send email with tel. numbers. Comments from GitHub are removed.
