### ISSUE TITLE
[Version 7.0] Call screening event takes action even when other events are yet to be processed

### ISSUE THREAD

**Issue by Penaz91** [henrichg/PhoneProfilesPlus#138]
Greetings,

First of all, thanks for developing this great app, it's really saving me a lot of headaches.

In the previous version, I had a configuration that does something like the following:

```
From 5.30pm to 9.30am -> Enable "Out of work" profile -> Block incoming calls coming from "Work" group
```

Since version 7.0 removed the "Phone call" profile parameter to the "Call Screening" event, I changed configuration as follows:

```
Call Screening Sensor -> Block Incoming Calls from Work Group
Profile Sensor -> "Out of work" profile active
```

On the same event.

Problem is that calls are blocked even when other profiles are active.

This is showed by the "events" tab, where when a call is received the "Call Sensor" writing becomes green, but the "Profile sensor" stays blue."

Hopefully my explanation is clear enough, and thank you again for your attention.

**Comment by henrichg** [comment]
Call screening from profile is moved into event as Call screening sensor.
Use it. 😏

Dňa so 2. 11. 2024, 14:27 Daniele Penazzo ***@***.***>
napísal(a):

**Comment by henrichg** [comment]
And yes, if event is running, call will be blocked,even when another profile is activated.
But in event is "Start of event"/"Other parameters"/"Start only when following profile is active". In it you can configure profile, in which has been "Phone call" parameter configured.

**Comment by henrichg** [comment]
Not Call Sensor, but Call screening sensor. Yes?
If event with this sensor is not running, are calls still blocked?
Hm, not good. I must looking on it.

**Comment by henrichg** [comment]
Hm, yes, is bug in service for this.
Fixed ion this version. If you want, istall it:
https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

**Comment by Penaz91** [comment]
> Not Call Sensor, but Call screening sensor. Yes?

Yes, I fixed the original post to reflect this.

> If event with this sensor is not running, are calls still blocked?

Exactly. The only way to avoid calls being blocked was disabling the sensor.

> Hm, yes, is bug in service for this. Fixed in this version. If you want, install it: https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

I just tested this version but it does not seem to work correctly. Opposite problem is happening now: the event is running (play symbol on event) but calls are not being blocked at all.

**Comment by henrichg** [comment]
Added is this test into call screening service:
event.getStatus() == Event.ESTATUS_RUNNING

-> event must be running

How is configured "Call screening" sensor? Especially "Duration" and "Permanent run"?

**Comment by Penaz91** [comment]
This was the configuration.

![Screenshot_2024-11-02-17-52-59-654_sk henrichg phoneprofilesplus](https://github.com/user-attachments/assets/21836b4a-363a-4080-9583-4deb61f82e38)

Tests done so far:

- Configuration as above: calls are not blocked
- Permanent run enabled:
    - First call goes through
    - Second call and subsequent ones get blocked
-  Permanent run enabled + profile sensor:
    - First call after changing to profile that should block the call goes through
    - Subsequent calls get blocked
    - Manually forcing the profile that should block calls doesn't activate the event (pause symbol on the event)

**Comment by henrichg** [comment]
OK, fixed (tested by me). Permanent run is not needed. Please test it:
https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

**Comment by henrichg** [comment]
Hm not good, not good. Problem is with duration of handling all sensors in all events. When is greather then 4 seconds, then call will not be blocked. By SDK documentation. Hm, hm. You must wait for fix. Sorry.

**Comment by henrichg** [comment]
OK test this: https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk

**Comment by Penaz91** [comment]
> OK test this: https://drive.google.com/file/d/1Hd788By6Te58HMOeIsyA0H0Q1eB2ivLA/view?usp=drivesdk Permanent run is not needed.

"Permanent Run" has been disabled and everything seems to be working great.

I would say this issue is fixed successfully. Thank you!

**Comment by henrichg** [comment]
Great. 😀

**Comment by henrichg** [comment]
.
