### ISSUE TITLE
Lock Screen Control Stopped Working on my Nexus 5X

### ISSUE THREAD

**Issue by landry314** [henrichg/PhoneProfilesPlus#14]
It was working for a while but then stopped. Maybe I changed a setting somewhere?

Does PhoneProfilesPlus support turning off the lock screen on a Nexus 5X? I swear it used to. If it does, can you explain how I would go about giving the app the proper permissions? I am thinking that is the issue.

Nexus 5X on Android 6.0.1.

**Comment by henrichg** [comment]
It is supported, but only for non-secure lockscreen (not supported is pattern PIN, password).

**Comment by landry314** [comment]
what if i have a rooted phone? is it not possible then? i'd love to see a root option to disable lock screen on PIN lock.

**Comment by henrichg** [comment]
I'm found root method. Will be implemented. ;-)

**Comment by hamamoko** [comment]
Is this feature implemented already? On my phone this option is greyed out (it says "unsupported lock") - I'm using pattern.

My details:
Phone: Samsung S5 neo (SM-G903W) rooted
Android version: 7.0
Samsung Experience version: 8.1
Build number: Zapryanovv ROM N[v2.1]
Android security patch level: August 1, 2017

**Comment by henrichg** [comment]
Sorry, no.
