### ISSUE TITLE
Switch profiles directly from widget?

### ISSUE THREAD

**Issue by tuftsanti** [henrichg/PhoneProfilesPlus#140]
I have 2 profiles active and working. When I press the 1x1 widget, it brings up the Activator, which I assume is by design. Is there a way to bypass the activator such that pressing the widget instantly switches profiles? I feel as if I had this action on older phones, but not in the past few years.

**Comment by henrichg** [comment]
Widget is for start Activator or Editor. If you want to directly activate profile, use Shortcut to profile. Is also supported by PPP.

**Comment by tuftsanti** [comment]
But then I would need 2 shortcuts to switch between profiles as opposed to 1 widget. Is there no way to use a widget to simply cycle through the profiles?

**Comment by henrichg** [comment]
And which profile you want to activate at click of widget? You do not have 2 profile, but several profiles. 
Is possible to dissble question didplayed when you click profile in Activator. After that click to profile activate it directly without question.

**Comment by henrichg** [comment]
PPP Settings/Profile activation/Confirm activating profile.

**Comment by tuftsanti** [comment]
I have already disabled Confirm Activating Profile, this is not the extra step I wish to avoid. I wish to avoid the Activator step, choosing the profile. I have a Day profile and a Night profile, I deleted the rest as I only use 2. Because I only have 2 profiles, I'd like to be able to switch between them by pressing the widget. This is how a similar app works, Night Screen, though it has far fewer options than PPP!

**Comment by henrichg** [comment]
You want to implement switch between these 2 profiles? You have problem click true profile in Activator? Hm, interesting. 
Not, this switch functionality  will not be implemented. Sorry.

**Comment by henrichg** [comment]
Write me, which applications have switch functionality. Thank you.

**Comment by tuftsanti** [comment]
I'm not sure i understand. There are many widgets that can perform simple tasks, I don't know if your widget CAN do a profile switch, but it doesn't. If you don't want to take on the request, I'll have to continue to activate manually in Activator.

**Comment by henrichg** [comment]
You write: "This is how a similar app works, Night Screen, though it has far fewer options than PPP".
Night screen is application? But this is only for switch night screen. It is not the same as PPP.

 More users has more then 2 profiles. For 2 profiles you want only switch, for more then 2 Activator?
But what when you click widget by mistake? By me is for this reason better Activator.

**Comment by tuftsanti** [comment]
You're not going to convince me that what I'm requesting isn't right for me. If you don't want to implement it, it's your code, you don't have to. This is the action I'd prefer in a widget as opposed to an icon, I understand it's not for everybody. I've never accidentally pressed a widget either, and it's not like doing so would be unrecoverable.

**Comment by henrichg** [comment]
Ok,
Yes is possible to implement it abd add also configuration. Is already implemented. Currently 2 options: Activator, Editor. Is not problem add third: "Switch". And if user add 3. profile, will be automatically switched to Activator.
Is this ok for you?

**Comment by tuftsanti** [comment]
Yes that sounds like exactly what I need! I really thought I remember this being an option previously, but thanks for considering now!

**Comment by henrichg** [comment]
Implemented. But only for Icon widget.
If you want, install this beta:
https://drive.google.com/file/d/1dNvsCVxH_1Tlc5uFvQoA-Qm29j60ahFl/view?usp=drivesdk

**Comment by tuftsanti** [comment]
Fantastic! This works as expected! Would you implement this into the main app eventually? Why not make it available regardless of number of profiles? What if I have 3 profiles and want to cycle?

**Comment by henrichg** [comment]
If you have more then 2 profile, which profiles to switch?
Currently for 1 or more than 2 profiles, this opens Activator.

And yes, will by this in next version (7.0.1).

**Comment by henrichg** [comment]
And with which order? By configured order in Editor? But profiles must have enabled "Show in Activator".
Currently is not needed to be "Show in Activator" enabled.
