### ISSUE TITLE
[Bug] NFC does not toggle

### ISSUE THREAD

**Issue by akrois2** [henrichg/PhoneProfilesPlus#141]
App Version: 7.0
Android Version: 14

I have set an event for an app to activate a profile which should enable NFC.
The event detection works fine, however since v7.0 the app fails to actually enable (and disable) NFC. I double checked this with v6.5.1.1 on the same phone and Android Version, on that version it still works correctly.

**Comment by henrichg** [comment]
It was fixed 21.11.2024. Will be in 7.0.1 version.
