### ISSUE TITLE
WiFi unnecessary switched on while scanning

### ISSUE THREAD

**Issue by DavisNT** [henrichg/PhoneProfilesPlus#15]
WiFi is being temporary switched on during each Wifi scan (configurable in _Wi-fi scanning_) however [since Android 4.3 there is a system setting that allows scanning of Wifi networks while WiFi is switched off](https://developer.android.com/reference/android/net/wifi/WifiManager.html#isScanAlwaysAvailable()). 

Temporary enabling WiFi can cause various issues - like interruptions in internet connectivity, connections to unsecure WiFi networks etc.

**Comment by henrichg** [comment]
Implemented. Will be in next version.
If you want install this test version:

**Comment by DavisNT** [comment]
Thanks A LOT for fixing this so fast! 👍 :1st_place_medal: 

Will test the current version soon!

I saw this has been removed in commits 554f950ca60010557ce63cb3b9bdd5e4aac02760 and 31d6d3bd6efa91ee7ebb43c72627266a0572932e. 
Will test how this behaves after switching off Wifi Access Point (on Android 7.1) as well.

**Comment by DavisNT** [comment]
I have done some tests and wifi scanning looks working OK after switching off the AP.

**Comment by henrichg** [comment]
Yes, I also tested it. Maybe changes in wifi scanner fixed it. :-)

**Comment by DavisNT** [comment]
Or may be this was a bug in some versions of Android (or a device specific issue)... 
AFAIK many things including Google Location Services rely on Wifi scanning while Wifi is off, so if this was a device/Android bug then it broke many things and hopefully is fixed for most devices.

Anyway - I guess this should work in most cases. And I assume in worst case (if somebody would face the issue of broken Wifi scanning after using AP again) it would be possible to make a user configurable setting for workaround.

**Comment by henrichg** [comment]
Yes, I will tested this in another devices.

**Comment by henrichg** [comment]
3.5.1 is released in Google Play.
