### ISSUE TITLE
link to rawgit downloads a strange file type

### ISSUE THREAD

**Issue by landry314** [henrichg/PhoneProfilesPlus#18]
https://cdn.rawgit.com/henrichg/PhoneProfilesPlus/16c88ba1/GooglePlay_ChangeLog.md

this downloads a file which my mac doesn't know what to do with. my text editor reads it fine but why isn't this like just an HTML file or something that can be read in my browser?

**Comment by henrichg** [comment]
This is Markdown format. Look at attached picture.
![snimka obrazovky z 2017-05-08 10-05-51](https://cloud.githubusercontent.com/assets/4045914/25795536/099e304e-33d6-11e7-8d5a-835ab3c8d30d.png)

You can not read it in your browser?

**Comment by landry314** [comment]
Firefox tries to download it as a file.

**Comment by henrichg** [comment]
This link is OK?
[https://cdn.rawgit.com/henrichg/PhoneProfilesPlus/a9e351e3/GooglePlay_ChangeLog.html](url)

**Comment by landry314** [comment]
yes, that loads in firefox.

**Comment by henrichg** [comment]
Fixed in Google Play.
