### ISSUE TITLE
Issue with activator since v3.5.1.3 with Android KK

### ISSUE THREAD

**Issue by ziki77** [henrichg/PhoneProfilesPlus#19]
Last week I installed the app on a smartphone (Motorola RAZR I xt890) with Android KK 4.4.2 and it was working fine.
Today a reinstall the app on the same phone after a factory reset and I had the following issue: when I open the activator it is showed up, but it disappers after few seconds. After this the home screen is unresponsive, I cannot open app list or any other shortcut. If I press back button, activator is showed up again and now it does not disapper anymore and I can use it to set the profile and home screen is accessible as before.

Installing old apk I understood that the bug is present from version 3.5.1.3.
The bug is NOT present on my other smartphone running MM and latest version fo the app.

**Comment by henrichg** [comment]
Thank you. Fixed.
If you want install this and test it: 
[https://drive.google.com/file/d/0B5RwcWvhmm8RN3k0bDEtZzRXN2M/view?usp=drivesdk](https://drive.google.com/file/d/0B5RwcWvhmm8RN3k0bDEtZzRXN2M/view?usp=drivesdk)

**Comment by ziki77** [comment]
Tested: it works now! Thanks!

**Comment by henrichg** [comment]
Good.
