### ISSUE TITLE
Support Tethering (wi-fi hotspot) toggle

### ISSUE THREAD

**Issue by algritz** [henrichg/PhoneProfilesPlus#2]
It is currently not possible to toggle wi-fi hotspot using profiles.

I would really like to see that feature added.

**Comment by henrichg** [comment]
;-) http://stackoverflow.com/questions/6394599/android-turn-on-off-wifi-hotspot-programmatically

**Comment by henrichg** [comment]
Wifi Hotspot added in version 3.1
