### ISSUE TITLE
Quick screen off lock on Samsung S6

### ISSUE THREAD

**Issue by tommick** [henrichg/PhoneProfilesPlus#20]
Hi, 
my phone went to a profile wich turns on "quick screen off lock". I cannot start any application, invoke mobile setting - nothing. I can not even stop the application or even restart my phone -it behaves almost like frozen!!! Only soft reset ( “Power” and “Volume Down”) works to restart my phone!
Pleease check this bug I think is a very serious issue!

**Comment by henrichg** [comment]
Power button during "Quick screen off" lock not working? Only this button working and that's how it works. 
How "quick screen off" working:
1. temporaty is configured screen timeout to 15 seconds.
2. displayed is "qick screen off" view.
3. after 15 seconds or if you click power button, view is destroyed, devices is locked.
4. next power button click turns screen on.
