### ISSUE TITLE
Profile to return to previous setting after manual activation

### ISSUE THREAD

**Issue by phit42** [henrichg/PhoneProfilesPlus#21]
Hello, 
how would I be able to tell PPP to return the changed settings to previous state, after I manually activated the profile?
Easy example: I run into a meeting, and activate the meeting profile manually via the starter screen for exactly one hour. This profile only changes sound mode from "sound on" to "vibrate only". I would the profile to switch from "vibrate only" to "sound on" after it finishes.
(Note: I cannot use an automatic event against my calendar in this example, as my calendar is "hidden" in Samsung Knox by our company.)

**Comment by henrichg** [comment]
Use profile parameter "Activation duration".

**Comment by phit42** [comment]
Thank you. Unfortunately that does not revert any settings performed during profile activation. So in above example, the sound mode stays in "vibrate only". Am I missing sth?

**Comment by henrichg** [comment]
When duration expires = Undo the profile not working? I'm using it and working.

**Comment by phit42** [comment]
Sorry didn't find it in profiles at first. My bad.
Now I am trying it, however when the duration expires, PPP does not stop the profile. Only way to "remove" the profile is by running "Ereignisse neu starten", which then kills the profile but leaves the settings changed.

**Comment by henrichg** [comment]
1. Activated is profile A
2. Manually activated is profile B with duration (for example) 10 seconds. Parameter "When duration expires" = "Undo".
3. After duration expiration activated is back profile A.

This must working. I'm using it.

Is not possible to revert back profile parameters. Only activating another profile is possible. And is not planned adding it, Sorry.
