### ISSUE TITLE
Events start when in manual mode

### ISSUE THREAD

**Issue by frangau** [henrichg/PhoneProfilesPlus#22]
Hello,

First, I'd like to say that I really appreciate your app. Thank you for that.

Now, the issue that I have on my Samsung A5 is that when I manually activate a profil, after a while the events start up again and the time frame for that seems to be random. I've had your app on my One M8 and it worked flawlessly. Manual mode stayed manual. I haven't set up anything else but time schedules for my profiles and I do not have set a time limit on manual activations.

**Comment by henrichg** [comment]
What PPP version?

1. Check if any event has enabled "Ignore manual activation".
2. Check if any profile has "Duration" > 00:00:00 and "When duration expires"="Restart events".

**Comment by frangau** [comment]
1. Version 3.5.4.3 (3290)
2. All profiles are set at 0 and restart. 

I'll try to change "restart" to "nothing". Maybe that will solve my problem. 

⁣

Le 2 oct. 2017 12:56, à 12:56, Henrich Gron <notifications@github.com> a écrit:

**Comment by frangau** [comment]
Tested yesterday and was able to hold on to a manually activated profile all evening. That seems to have solve my problem. I don't know if "restart" is the default setting in your app. I certainly don't remember tinkering in that settings page.

Thanks for pointing me in the right direction !

**Comment by frangau** [comment]
Well it seems I've spoken too soon. I got out during lunch hour and activated my home profil and within 20 minutes, it turned back to automatic mode and switched back to my work profil.

**Comment by henrichg** [comment]
Please update to newest version from Google Play (3.5.4.5).

**Comment by frangau** [comment]
Problem seems resolved. Left phone on manually activated profile for a whole day without incident.
