### ISSUE TITLE
Add option to event Wi-Fi parameters sensor: stop event immediately when SSID is no longer available

### ISSUE THREAD

**Issue by CodeAmai** [henrichg/PhoneProfilesPlus#23]
Hi, I'd like to start of by saying I really like your app, it has definitely made my life better through the automation it provides. However, there's one thing which keeps annoying me: 
I have 3 main profiles in PhoneProfilePlus: Home, Work and Outdoor. Home and Work are (mainly) activated by being in range of an SSID and this works great, my phone switfly swaps from Outdoor to Work when I enter my workplace and my phone pick ups any of the work-networks. And the same goes for Home profile. The problem appears when I leave any of these places, because even though these SSIDs are no longer reachable, Android keeps 'hoping' that this SSID will reappear soon and stays 'connected' to this SSID, thus PhoneProfilesPlus stays in previous Home or Work profile, even though I've been outside for 5, sometimes even 10 minutes.
This puts me constantly in a position where I have to manually activate events or change volume/turn on mobile data etc., but all of that just goes against what this app was created for. Please add an option to switch profiles immediately when SSID isn't available anymore.

**Comment by henrichg** [comment]
In Android API is not broadcast for this. Only Wi-Fi scanner. And scanner is delayed, when screen is off. This is Android "feature" used for battery saving.
In PPP is option for rescan Wi-Fi when screen is switched on. In latest version it is permanent. Each switch to screen on, starts Wi-Fi scan. This is not working?
Maybe new "Connection Type" = "Nearby" and/or "Connected" may help. For (dis)connection, broadcast exists and is used in PPP.

**Comment by CodeAmai** [comment]
I already am using "Connection Type" = "Nearby", but I don't want to use "Connection Type" = "Connected" for a lot of reasons (one of them being that my cell data is simply better than the wifi in my workplace). And there's also the fact that I am using "Connected" for my home network, and the problem appears there too.
Problem is, when android goes into this 'lost SSID but still hoping it'll reappear' mode, rescanning does nothing, it seems android doesn't clear such SSID from its list and just scans for new ones. So turning screen off and on doesn't work here.
I assume you have no possibility of 'pinging' a Wi-Fi network from your app? Doing that and checking if there's an answer would be one solution, assuming it is possible.
Or how about 'calculateSignalLevel' from https://developer.android.com/reference/android/net/wifi/WifiManager.html?
Or perhaps 'getConnectionInfo' and then 'getDetailedStateOf' or 'getSupplicantState'?
These are all just wild guesses, since I'm not familiar with Android environment and I have no emulator or anything to test it out.

**Comment by henrichg** [comment]
SSID scan result list is never cleared. Is rewrited during each scan.
PPP using broadcasts for switch wi-fi on/off, connect/disconnect wi-fi, get scan results.

Pinging wi-fi network increase battery consumption. 
Booth pinging wi-fi and calculating signal level requires new job for this. Again: battery. :-/

Maybe solution is remove from SSID list disconnected SSID when broadcast for wifi disconnect is received.

**Comment by henrichg** [comment]
I'm using in my device Wi-Fi sensor with "Connection type"="Nearby". Scanning interval is set to 15 minutes. Device disconnection != SSID is not nearby. Android API function startScan() can returns disconneced SSID, because is in nearby of device. And important is also scanning interval. Scan result is changed in this interval.
By me, in this issued situation is better "Connection type"="Connected".

**Comment by CodeAmai** [comment]
What's the point of app for automation of profile switching if I have to manually pull out my phone and connect to a network by hand? Not to mention even a very weak signal (like 20%) is still considered "Connected", while in reality we are moving away from said network and need our profile to be changed?
There's a need to either know the signal level or measure network response time in order to have a more precise version of discovering when a user is in or out of SSID's range so that a new event can be triggered. If barred behind an additional, not-default option, there shouldn't be any issue with increased battery drain (cause user chose so willingly and consciously).

**Comment by henrichg** [comment]
Sorry, but this is not fault of PPP. If device disconnects from Wi-Fi, SSID may be in nearby (in result set of startScan()). Even when signal of Wi-Fi is low for connection.
And when in PPP will be mixed option "Connected + Nearby", this may cause another problem. PPP detects dsconnection, but scanning detect SSID in nearby. In this situation will be event ended and again started. Not good.
In PPP not exists parameter for check signal strench of Wi-Fi. It will be good parameter for "Nearby". But I must search for this in Android API (how to get signal strench of Wi-Fi for specfied SSID). If not exists, then it is not possible to implemet this.
