### ISSUE TITLE
Application parameters don't work on my S7

### ISSUE THREAD

**Issue by Urs281** [henrichg/PhoneProfilesPlus#24]
PhoneProfilesPlus is very helpful and I like this app. But I struggel to use the application parameters function. I installed the PhoneProfilesPlusExtender and I allow PPPExtender to detect which application is in the foreground. But nevertheless PPP doesn't recognise any running apps. I use a Samsung Galaxy S7. How can I fix this issue?
Thanks
Urs

**Comment by henrichg** [comment]
- Fixed in version 3.5.6.1. Also is required upgrade PhoneProfilesPlusExtender.
