### ISSUE TITLE
Modifying volume no longer works

### ISSUE THREAD

**Issue by cowwoc** [henrichg/PhoneProfilesPlus#25]
Version 3.5.7

In the latest version of PhoneProfilesPlus, changing the volume in a profile does not work. For example, if a profile is meant to set the system volume to 0, nothing happens when the profile is activated. This used to work in previous releases.

**Comment by henrichg** [comment]
1. Your device has merged ringing and notification volumes?
2. Device and Android version?
3. In Nexus devices is system volume merged with ringing+notification volume. Your device has separated system volume in system Settings?

PPP sets volumes in order:
1. system
2. ringing
3. notification

If you have merged volumes, PPP notification volume value is set in all volumes.

**Comment by cowwoc** [comment]
When I change volumes manually with the physical buttons, I have separate volume controls for Ringtone, Media, Notifications and System. So I don't think any of them are merged.

Device: Galaxy Note 4
Android Version: 6.0.1

For the profile in question, I have the following settings:

Ringtone volume = 0
Media volume = 0
Alarm volume = 2
System volume = 0
Voice volume = do not change
Speakerphone = do not change

What I am seeing is that I activate the profile, wait 30 seconds, hit the down-volume physical button and see that all the volume levels are the same as before I activated the profile. Again though, this used to work 2-3 weeks ago so I'm not sure what changed. I don't remember changing any profile configuration.

**Comment by henrichg** [comment]
Please write me also "Sound profile" configuration. This configuration is important because:
If "Ringer mode"="Vibrate","Silent" or "Do not disturb" and "Do not disturb type"="Total silence","Off with vibration","Priority with vibration","Alams only", volumes "Ringtone","Notification","System" is ignored, not changed in system.

**Comment by henrichg** [comment]
And when I tested your configuration, volume System is muted in system settings. Tested in Samsung S8.

**Comment by cowwoc** [comment]
In "Sound profile", I have "Ringer mode" set to "do not disturb" and "Do not disturb type" set to "Alarms only - Interrupt only with alarms".

Why would Ringtone/Notification/System volumes get ignored in this mode? Doesn't "Alarms only" imply that all other volumes are set to zero?

How do I achieve the desired behavior? Thank you.

**Comment by henrichg** [comment]
No, not set to zero. Muted. Value of volumes are not changed in system settings.
Sysrem tones are heard during "Only alarms" in your device?

**Comment by cowwoc** [comment]
Yes. What happens is I activate the profile, then hit the power button and I hear "screen shutdown" tone. When I unlock the phone, I hear another sound. Based on this I conclude system sounds are enabled.

Further, if I go into Android's system configuration, sounds and vibrations, volume, I see the only thing that is muted is Media. I see Ringtone, Notifications and Systems are all non-muted.

**Comment by henrichg** [comment]
Problem is with Android. PPP configure ringer mode. And then volumes. If ringer mode is vibrate and silent and ringing volume > 0, vibrate/silent is disabled by volume change. :-(
By me fixed. If you want, test this version: https://drive.google.com/file/d/0B5RwcWvhmm8RYVJ1cFdpVFpxWjQ/view?usp=drivesdk

**Comment by cowwoc** [comment]
@henrichg Yay. That fixed it. Thank you!

**Comment by henrichg** [comment]
Good. :-)

**Comment by cowwoc** [comment]
@henrichg This bug is still present in version 3.5.8.3. Is it supposed to be fixed or maybe it came back?

**Comment by cowwoc** [comment]
Hmm. This is a new bug. I recently flashed my note 4 with the dr. keytan m12 build. The bug I'm seeing is the ringer volume getting set to 1 when my profile actually says 0. All other volumes seem to getting set correctly. How do we debug this?
