### ISSUE TITLE
Hotspot toggle not available on Oreo?

### ISSUE THREAD

**Issue by jtothe4n** [henrichg/PhoneProfilesPlus#26]
Hey,

in one of the last updates the hotspot option is grayed out with the explanation that it is not supported on Oreo.

I'm running Oreo 8.0 on my HTC U11 and it worked fine before.
Installed an older version from December 3.5.6.2 and it works fine here for me on Oreo.
Any chance you can enable that option again? Using it to tether to my car when it connected to my phone via BT.

**Comment by henrichg** [comment]
And Internet vorking? In Nexus 5x, Oreo 8.1, internet not working. Wifi hotspot in 8.1 working only in local network. :-(

**Comment by jtothe4n** [comment]
Yeah, I tried it in my car about 3 hours ago..and a few minutes ago on with my laptop.
I'm on 8.0 though on my U11.
Running Oreo for quite a few months already, never had issues.
Maybe it is a HTC thing that it is working, probably they removed the android.permission.OVERRIDE_WIFI_CONFIG with protectionLevel="signature|privileged"
...or it is because I run my own custom rom and "broke" it.

Just compiled your latest sources and it still works.

you can probably add a userhint to people that have issues.
They could use adb shell to "pm grant" that permission?

**Comment by henrichg** [comment]
1. With root not working.
2. adb shell pm grant sk.henrichg.phoneprofilesplus android.permission.OVERRIDE_WIFI_CONFIG
Operation not allowed: java.lang.SecurityException: Permission android.permission.OVERRIDE_WIFI_CONFIG is not a changeable permission type
Not working. 
:-(

**Comment by henrichg** [comment]
Also not working with added permission to manifest file and using pre-Oreo method. Wi-Fi AP enabled in system, but other device can not obtain IP adress. :-(

**Comment by henrichg** [comment]
For you, I'm enabling this for rooted devices and added hint "Maybe not working in your device". OK?
Tomorrow. :-)

**Comment by jtothe4n** [comment]
mhhh, crap.

Well, then I'll just keep my own compiled version, or compile an app with two activities to toggle the Wi-Fi AP state and use the "start application" action. That way I can use your play store version.

**Comment by henrichg** [comment]
Thank you for donation.

**Comment by henrichg** [comment]
Test version for you: enabled wi-fi hotspot toggle for Android 8+ rooted.
https://drive.google.com/file/d/0B5RwcWvhmm8RYVJ1cFdpVFpxWjQ/view?usp=drivesdk
Please test it.
Thank you.

**Comment by jtothe4n** [comment]
It works, thanks (:
