### ISSUE TITLE
Profile activation for time does not work

### ISSUE THREAD

**Issue by DavisNT** [henrichg/PhoneProfilesPlus#29]
When I choose to activate certain Profile for duration (configurable during activation with _Undo the profile_ as _When duration expires_) the widget shows it is activated until configured duration expires. 
However when the duration expires the previous profile is not activated. Instead the duration is started again (most likely profile is switched back and forth). 
This seems to be a regression (this issue wasn't present on April last year when I started using PhoneProfilesPlus), but I am not sure when it started (I have noticed it in last few days). 
The issue is reproducible with very short duration (e.g. 5 seconds) configured.

**Comment by henrichg** [comment]
Yes, yes. :-(
Thank you.

**Comment by henrichg** [comment]
Fixed. In this beta version: https://drive.google.com/file/d/0B5RwcWvhmm8RYVJ1cFdpVFpxWjQ/view?usp=drivesdk
Please test it.

**Comment by DavisNT** [comment]
Looks like the test version is working.
