### ISSUE TITLE
jfltexx events don't trigger 

### ISSUE THREAD

**Issue by centoasa** [henrichg/PhoneProfilesPlus#3]
I've try many times but on my s4 jfltexx events don't trigger profiles and remain always default home.

**Comment by henrichg** [comment]
Please send me by e-mail application data.

1. In Editor in menu is item "Export app.data"
2. Exported data will by saved to sdcard to folder PhoneProfilesPlus
3. Send me all files in this folder.

Thank you.


Dňa ne 24. 5. 2015 o 1:05 Remigio <notifications@github.com> napísal(a):
