### ISSUE TITLE
Notification is still shown when "Show in status bar and locksreen" is disabled on Android 8.0

### ISSUE THREAD

**Issue by VeryCrazyDog** [henrichg/PhoneProfilesPlus#30]
Even I have disabled `Settings` > `Notifications` > `Show in status bar and lockscreen` in Android 8.0 on my Sony Xperia XZ1, the notification is still shown in status bar and lockscreen. However, the Resilio Sync which I am using on the same phone is able to correctly not showing in status bar in the icon but still running in the background.

Version using: 3.5.8.3 (3960)

**Comment by henrichg** [comment]
Google Play version (3.5.8.3) is not fully compatible with Android O. 
New version will be fully compatible. And for notifications will be used notification channel. User can change importance of notification channel. 
Form PPP will be "Show status bar notification" and also "Show in status bar and lockscreen".
