### ISSUE TITLE
Add "Cell Name" as selection criteria in addition to Cell ID

### ISSUE THREAD

**Issue by VeryCrazyDog** [henrichg/PhoneProfilesPlus#31]
Right now, the `Mobile cell parameters` in "event" support cell ID selection only. It can be more user friendly to support cell name selection.

For example, we have defined a cell name called "Home" which has 3 cell ID. In "At Home" event, we can choose the 3 cell ID as `Mobile cell parameters`. However if we perform `Cell registration` function in `Settings`, new cell ID will be added with cell name "Home", but we still need to manually added the new cell ID to event "At Home", which is less convenient.

Background:
I was a happy user of [Llama](https://play.google.com/store/apps/details?id=com.kebab.Llama) but unfortunately the app is no longer in development and inevitability need a new replacement. PhoneProfilePlus is the most suitable replacement in my use case. I believe some of the concept in Llama can be put in PhoneProfilePlus to make PhoneProfilePlus better :smiley:

**Comment by henrichg** [comment]
In event sensor parameter "Mobile cell parameters"->"Cells" is "Change selection" button with options:
- "Unselect all"
- "Select by cell name"
-"Select all visible"

**Comment by VeryCrazyDog** [comment]
Yes, I aware we can "Select by cell name" in PPP, but the final selection on cell ID level, but cell name level.

What I would like to see is that under "Mobile cell parameters", after selection, it is not displaying `Selected 15` cells or `Selected 5` cells but something like `Selected "My Cell Name"`.

**Comment by henrichg** [comment]
Implemented.
