### ISSUE TITLE
Unable to mute ringtone volume

### ISSUE THREAD

**Issue by cowwoc** [henrichg/PhoneProfilesPlus#32]
Version 3.5.8.3

(This issue might be related to https://github.com/henrichg/PhoneProfilesPlus/issues/25)

I recently flashed my note 4 with the Dr. Ketan M12 build. I am now seeing a bug where a profile is supposed to set the ringtone volume to 0, but instead I see the volume getting set to 1. I am able to mute all other volumes correctly, with the exception of notification volume which is not getting set to zero either.

The UI says that "Notification volume is ignored [...] if the ringtone volume is set to 0" but in fact it is not. The UI grays out the notification volume, but in fact the volume is getting set to the grayed-out volume.

**Comment by cowwoc** [comment]
I just flashed the stock image of the Note 4 (Android 6.0.1 build N910W8VLS1DPK1) and I am getting the same bug. I no longer think the ROM is at fault. I think it is a genuine bug in the application.

**Comment by henrichg** [comment]
Ringtone volume = 0 in Android = vibrate ringer mode (tested in Samsung S8, Nexus 5x, Xiaomi Redmi 4x, ...). Therefore PPP set it to 1 and enable silent ringer mode.
In my Samsung S8, if silent mode is set, also notification and system volime is silent.

**Comment by henrichg** [comment]
After profile activation with ringer volume = 0, in Samsung S8 is in status bar silent icon.

**Comment by cowwoc** [comment]
The only thing I see in the status bar is that "Do not disturb" is enabled. Is that what you're referring to?

**Comment by henrichg** [comment]
![screenshot_20180424-183908_phoneprofilesplus](https://user-images.githubusercontent.com/4045914/39201492-829c77e8-47ef-11e8-8482-b786f9c88879.jpg)

**Comment by cowwoc** [comment]
Nope, I don't have that. The closest icon I've got is the one in the top left corner which is "do not disturb mode".
![screenshot_2018-04-24-14-34-23](https://user-images.githubusercontent.com/633348/39207019-e1f009bc-47cc-11e8-968f-7da13d1831dc.png)

**Comment by cowwoc** [comment]
@henrichg How do I export it?

**Comment by henrichg** [comment]
1. Editor menu -> Backup/Restore -> Backup
2. Internal storage/PhoneProfilesPlus -> send me all files in this folder.

**Comment by cowwoc** [comment]
Here you go: 

[settings.zip](https://github.com/henrichg/PhoneProfilesPlus/files/1944583/settings.zip)

**Comment by henrichg** [comment]
In profile is configured: 
Sound profile -> Ringer mode = Do not disturb
Sound profile -> "Do not disturb" type = Alarms only.
In this type, ringing and also notifications are mutted. Is inrelevant what is configured ringing volume.

**Comment by cowwoc** [comment]
@henrichg Okay, I get it now. So I have two questions and a comment:

Question 1: I can manually enable Do Not Disturb with ringer set to mute (not vibrate). Can't your app do the same (as opposed to setting volume to 1)? It would be weird for Google to let you configure this mode manually but not through the API.

Question 2: Once Do Not Disturb is enabled, do the volumes mean "if a call gets through, use this volume for the ringer"? Meaning, I shouldn't really set the volume to zero because them any calls that get through (e.g. in priority mode) won't be heard. Is that correct? If so, the UI needs to make this more obvious.

Comment: I read (and I agree) a comments in the Play Store that say your app is powerful but the UI difficult to understand. For example, users are asked to configure Do Not Disturb types without an explanation of what the different modes might mean (e.g. Priority vs Total silence). If I configure these same things through the Android Settings dialog the explanations are a lot more obvious. What's more, they let me configure Do Not Disturb combinations that your app does not.

I'm not sure how to solve this problem. One possibility would be for you to recreate all these dialogs, but I think a much easier and better solution would be to let users manually configure the phone how they want... then go back to your app and "capture" the current mode into a profile. This way you have to do much less work on your end, and users get exactly what they expect. What do you think?

**Comment by henrichg** [comment]
1. 
"I can manually enable Do Not Disturb with ringer set to mute (not vibrate)."
But you must configure:
  a) Sound and vibration -> Sound mode = Mute
  b) Sound and vibration -> Do not disturb = enable
  c) Sound and vibration -> Do not disturb -> Allowed exceptions = Alarms only

"Can't your app do the same (as opposed to setting volume to 1)?"
It is not implemented, but is possible.
------
2. If Do not disturb is enabled, and Allowed exception is:
    - No exceptions - ringing, notifications alarms are mutted (in PPP - Do not disturb type = Total silence)
    - Alarms only - ringing, notifications are mutted (in PPP - Do not disturb type = Alarms only)
    - Custom - only configured exceptions are not mutted, used is appropriate volume level  (in PPP - Do not disturb type = Priority)
------
Comment: I read (and I agree) a comments in the Play Store that say your app is powerful but the UI difficult to understand. For example, users are asked to configure Do Not Disturb types without an explanation of what the different modes might mean (e.g. Priority vs Total silence). If I configure these same things through the Android Settings dialog the explanations are a lot more obvious. What's more, they let me configure Do Not Disturb combinations that your app does not.

In Nexus/Pixel devices: Off, Priority, Alarms only, Total silence
In Samsung devices: Off, Custom, Alarms only, No exceptions

In PPP DND types are named by Nexus/Pixel devices (AOSP).

Only 3 DND types are supported by Android. Only Priority (Custom) is more configurable. But this is not supported by PPP and maybe API not exists for change Priority DND configuration.

**Comment by henrichg** [comment]
And is necessary to implement it? You can use DND Only alarms.

**Comment by henrichg** [comment]
Only for this? And if in profile is not configured ringing volume? In my Samsung S8, when enabled DND via quick settings, displayed is not changed volume (before DND on).

**Comment by henrichg** [comment]
Grayed is notification volume not ringing. And in this situation notification volume is ignored = not changed in system.
And another problem. In AOSP is not separated DND and ringer mode. Only in not AOSP roms are separated (Samsung). In AOSP is also grayed system volume slider in DND Only alarms.

**Comment by cowwoc** [comment]
@henrichg That's why I strongly suggest you reconsider the UI. If you let users set whatever they want using the ROM UI and your application just imports what's already there then you have less problems to deal with. Everyone will be happier for it.

**Comment by henrichg** [comment]
OK, implemented. For DND is changed ringer mode to silent, when ringing volume = 0.
If you want, install this beta: https://drive.google.com/file/d/0B5RwcWvhmm8RYVJ1cFdpVFpxWjQ/view?usp=drivesdk
If you also using PhoneProfilesPlusExtender, install this PPPE beta: https://drive.google.com/file/d/1GFX7fT4--DcCFeVyfMrf8XZ1sgO9E5B_/view?usp=drivesdk

**Comment by cowwoc** [comment]
The beta works as expected. Thank you.
