### ISSUE TITLE
Cannot set adaptive screen brightness

### ISSUE THREAD

**Issue by cowwoc** [henrichg/PhoneProfilesPlus#33]
Version 3.5.8.3
Samsung Galaxy Note 4

Profiles that set the screen brightness work, so long as "Adaptive" is unchecked. When I enable "Adaptive" the brightness is not changed at all.

**Comment by cowwoc** [comment]
See my "Outdoor" profile. It is supposed to set the brightness to 100% Adaptive. If I configure my phone to use the minimum brightness before, then enable this profile, the brightness remains unchanged.

[settings.zip](https://github.com/henrichg/PhoneProfilesPlus/files/1952541/settings.zip)

**Comment by cowwoc** [comment]
Yes, it is. I am using the stock ROM (6.0.1 build N910W8VLS1DPK1) with Magisk Manager (16.0).

**Comment by henrichg** [comment]
Sorry: Setting "screen_auto_brightness_adj" worked on CyanogenMod, but did not work on Samsung's devices.

**Comment by cowwoc** [comment]
@henrichg I think (but don't remember for sure) that this feature used to work in the past (on this same phone). Did you use an alternative approach in the past?

**Comment by henrichg** [comment]
Samsung do not use AOSP parameter "screen_auto_brightness_adj", using it's own parameter and I do not known which. :-(

**Comment by cowwoc** [comment]
@henrichg I searched Google and could not find the relevant key either :(

Consider graying out the Adaptive checkbox on Samsung phones I guess.

**Comment by henrichg** [comment]
Checkbox is OK, it is working, only level slider is not working.
Also in Samsung Customisation SDK is not API for this. :-(

**Comment by cowwoc** [comment]
Right, so is there a way to indicate this in the UI? Maybe on Samsung ROMs, gray out the slider with a note underneath saying "Functionality not exposed by Samsung" or something?

**Comment by henrichg** [comment]
Implemented.
