### ISSUE TITLE
Version shown in 'About applictaion'

### ISSUE THREAD

**Issue by bobi1024** [henrichg/PhoneProfilesPlus#34]
I have the latest version from the playstore and when I was going trough the github I've noticed that there is a difference in the major versions as you can see from the screenshot.
Is that correct?

![screenshot_2018-05-07-18-26-51](https://user-images.githubusercontent.com/15198625/39710364-4949eddc-5225-11e8-8c77-b84d223354c0.png)

**Comment by henrichg** [comment]
This is Google Play version. Current version in GitHub is 3.6b (3970).

Dňa po 7. 5. 2018, 17:36 bobi1024 <notifications@github.com> napísal(a):
