### ISSUE TITLE
Bluetooth scan

### ISSUE THREAD

**Issue by orlproi** [henrichg/PhoneProfilesPlus#38]
Each time the events are restarted, the Bluetooth scan is deactivated.
The 'Bluetooth Sensor' function can not be used.
Translated google sorry.

**Comment by henrichg** [comment]
Check if you do not have in any profile configured parameter: "Application functions"/"Disable Bluetooth scanning"="Scanning disabled".

**Comment by orlproi** [comment]
Yes, thank you

**Comment by orlproi** [comment]
Solved this problem.
On my device the scanning intervals do not work well.
Sometimes the scan does not take place according to the set time or after scanning the bluetooth remains enabled even if it is not provided by the activated profile and it is only deactivated when the event is restarted.
I attach images settings.
[IMG] http://i66.tinypic.com/ndtq4p.jpg [/IMG]
[IMG] http://i66.tinypic.com/6gybll.jpg [/IMG]
Asus zenfone2  laser
Android 5.0.2
Thank you

**Comment by henrichg** [comment]
What version you have installed? By screenshots you have old version.

**Comment by orlproi** [comment]
These versions
[IMG] http://i67.tinypic.com/fkadco.jpg [/IMG]
[IMG] http://i64.tinypic.com/xoif83.jpg [/IMG]
Bye!

**Comment by henrichg** [comment]
My mistake. They have the latest version.
Bluetooth must be temporary enabled for bluetooth scanning. But after scanning ends, is back disabled.
One scan duration is 25 seconds.

**Comment by orlproi** [comment]
Bluetooth scan:
Scan interval and scan duration do not respect the times
Asus zenfone2 laser
Android 5.0.2
Thank you

**Comment by henrichg** [comment]
Yes, this is problem, when PPP is running in background. AlarmManager and JobScheduler is used. Even when is used exact alarm, is not exact. This is "feature" in Android for battery saving.
