### ISSUE TITLE
Volume after BT connection established

### ISSUE THREAD

**Issue by SIRSteiner** [henrichg/PhoneProfilesPlus#4]
Hello! I use profiles for home, at work, silence and car. The car profile should establish a BT-connection and raise BT-volume to maximum. But I see that at first the volume raise up and after the connection established the BT-volume decrease to the level that was before. The same thing happens in the other direction. Tested on Y300 and BQ M5 (Stock and CM12.1). Thank you

PS: The reason is that volume is changing BEFORE the connection is on/off and Android seems to memorize the last volume. So if connection is on (car profile) and I change profile to home the volume decrease and this level is memorized for the next connection and then the connection goes off. If I change again to car profile volume raise up to maximum, connection goes on and then the memorized volume is set.

Therefore volume should be set AFTER connection goes on/off.

**Comment by henrichg** [comment]
Hello,
for BT connection detection use event:
1. setup profile for swith on/off BT
2. setup second profile for set volume, when BT is ON
3. setup event for BT connection detection
    a) Start of event
        aa) Activate profile - profile for set volume
        ab) Ignore manual activation - checked
    b) End of event
         ba) Activate profile - none
         bb) And do - Undo the profile
    c) Enable Bluetooth - checked
        ca) Connection type - Connected
        cb) Bluetooth name - BT car name

**Comment by SIRSteiner** [comment]
Thank you!
