### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by kchpub** [henrichg/PhoneProfilesPlus#40]
F-droid flags your app for tracking and reporting activity. I'd like to know why, and if you say debugging....

I've got no problem submitting a bug report, but it shouldnt require these agressive permissions.

**Comment by henrichg** [comment]
Is not possible to add PPP into F-Droid. 
PPP uses:
1. Google Play services
2. Google Maps
3. Crashlytics

**Comment by kchpub** [comment]
Holy crap you're fast!

I'm a bit confused, as there is PPP on Fdroid: https://f-droid.org/app/sk.henrichg.phoneprofilesplus

**Comment by henrichg** [comment]
404 Page Not Found
 :-D

**Comment by henrichg** [comment]
https://f-droid.org/en/docs/Inclusion_Policy/

This:

We cannot build apps using Google’s proprietary “play-services”. Please talk to upstream about an untainted build flavor (either using microg or removing non-free deps completely).
We cannot build apps using proprietary tracking/analytic dependencies like Crashlytics and Firebase. Please talk to upstream about an untainted build flavor (either using a FLOSS analytics software like ACRA or by removing non-free deps completely).
