### ISSUE TITLE
volumes don't adjust when in "do not disturb"

### ISSUE THREAD

**Issue by aneal** [henrichg/PhoneProfilesPlus#42]
version: 3.6.7.5 (4540)
phone:  Verizon Pixel 2

Might be related to #25 but when I have my profile set to "Do not Disturb" and my volume set to 3 for ringer and notification (I have a pixel 2 with combined volumes and use phoneprofilesplus to split them).  The profile does set "do not disturb" (priority interruptions), but does not adjust my volume.  The volumes stay at 7/7 as they are set on the "normal" profile.  I'd like my interruptions while at work to not be at full volume.

**Comment by henrichg** [comment]
Hm, yes, it is bug. Thank you.

**Comment by henrichg** [comment]
And fixed. If you want, install this beta: https://drive.google.com/file/d/1M37pKkrf3y3WubjMygfZiaZsR_fFQtsr/view?usp=drivesdk
Before installation, do backup of PPP data. Backup is in Editor menu.

**Comment by aneal** [comment]
This version is behaving as expected.  Thanks

Allan

--
Application Operations and Engineering
​​​Allan Neal
Lead Systems Engineer
(o) 404.827.1492 /​ (m) 404.754.2706
[ttp://collabext.turner.com/signatures/black/GTO-Global-Broadcast-Tech%20Logo.png]
