### ISSUE TITLE
no cell mobile found

### ISSUE THREAD

**Issue by kikibelux** [henrichg/PhoneProfilesPlus#44]
Hi, 
I use your app since  some month and since this saturday, an update cause some troubles
it's impossible to choose mobile cell. An event occur if i'm located near house but this location don't occur. If I ask to find mobile cell, any are found.

I don't see the actual cell connected. the time is not correct....

My phone is an Motorola g5s+

**Comment by henrichg** [comment]
Android 9? For this android version is required enabled Location in system settings.

**Comment by kikibelux** [comment]
no  Android 8.1.0

**Comment by henrichg** [comment]
In "Cell" dialog "Rescan" button not working? Is not displayed connected cell?

**Comment by kikibelux** [comment]
![Screenshot_20190313-193513](https://user-images.githubusercontent.com/36819904/54305350-6b266e80-45c7-11e9-9b62-6c8665e55cf0.png)
find a screen here
THANKS

**Comment by henrichg** [comment]
RESCANNER button not working? Device?

**Comment by kikibelux** [comment]
it seem work but any cell appear

**Comment by kikibelux** [comment]
my device is a motorola g5s+

**Comment by henrichg** [comment]
Please test this test version: https://drive.google.com/file/d/1oxUpsuSAGWh9uF-B-fKpFvcyiX4o3Cvj/view?usp=drivesdk

Before installation, backup PPP data. Backup is in Editor menu.
After installation, go into Cells dialog, use RESCAN button and then send me from folder PhoneProfilesPlus file log.txt. Thank you very much.

**Comment by kikibelux** [comment]
With this version,  I must on the location and cell appear !

**Comment by kikibelux** [comment]
And when I install the googleversion, I must open location to see cell !
I don't like really this think....:( but a lot of thanks for you help)

**Comment by henrichg** [comment]
This is equal to Google Play version + added is log into log.txt.
Ok, then please test this version: https://drive.google.com/file/d/1oxUpsuSAGWh9uF-B-fKpFvcyiX4o3Cvj/view?usp=drivesdk
Before installation disable Location in system settings. Thank you.

**Comment by kikibelux** [comment]
I come back in one hour...

**Comment by kikibelux** [comment]
No change,  same problem  ! :(

**Comment by henrichg** [comment]
Hm, hm. OK. Then location enabled is required also for Android < 9. Sorry, but is not possible to get back to old version. Google requires set Android 9 support for applications. At the latest in November.

**Comment by henrichg** [comment]
But it is not required to use GPS. You can configure Location settings to not use GPS. Only mobile cells and wifi. Check your Location configuration in system settings.

**Comment by HogoDorn** [comment]
On my device a Samsung S5 (Android 7.1.2, root) switching the  Location settings  to "High" doesn't fix the problem.
Going back to 3.6.7.5 and everything ist okay!

**Comment by henrichg** [comment]
Latest Google Play version? (3.6.8.5).
I'm tested it and in my S8, Android 8.0 is not needed to be location enabled.

**Comment by HogoDorn** [comment]
Tested latest Google Play version on my S5 and on an Huawei Tablet Android 5.1.1, on both no mobile cell where found.

**Comment by henrichg** [comment]
Hm, not working in Honor 7A, Amdroid 8.0. This is strange. 
By me, problem is increased support in PPP from Android 7 to 8.
But it must. Google requires this. :-/
