### ISSUE TITLE
Feature request: Possibility to disable "no profile activated" system notification.

### ISSUE THREAD

**Issue by dickerpulli** [henrichg/PhoneProfilesPlus#45]
I want to have the option to disable the system notification when no profile is active. I only want to see a notification if there is a profile active.

**Comment by henrichg** [comment]
Sorry, but this is not possible. Notification must be generated for PhoneProfilesService and visibility can not be changed by application, only by mobile user in notyfication system settings.

**Comment by dickerpulli** [comment]
Can't you provide an option that prevents sending notifications of type "No profile active"

**Comment by henrichg** [comment]
PhoneProfilesService is flagged as "foreground service". Each foreground service must have it's own notification. When service is not foreground, system kills it. Killed service = not working PPP.
