### ISSUE TITLE
Executing application -> direct call to contact

### ISSUE THREAD

**Issue by memphissk** [henrichg/PhoneProfilesPlus#46]
Hello, is there some bug or i do something wrong when i want to add running action. I add direct call to list of application which shoul be started. When i select direct call and then contact, this action is not starting. Other action are starting properly, but direct call not. In this case i need to setup call forwarding via **21#.... codes which are assigned and saved as contact. I need to apply call forwarding when i arrive to work. Is it possible to do it via this app? Thanks

**Comment by henrichg** [comment]
PPP do not have function for make call. Solution is using profile parameter "Run application, shortcut intent". Configure Intet ACTION_DIAL. Intent ACTION_CALL not working. This action requires permission CALL_PHONE. Sorry.
