### ISSUE TITLE
Request: Dual SIM phone, ringtone change of second SIM

### ISSUE THREAD

**Issue by 4oSmile** [henrichg/PhoneProfilesPlus#47]
Hello PhoneProfiles developers and fans :) 

Thanks for all the features you include and keep improving this priceless app! 

I use PhoneProfilesPlus on several Samsung dual sim phones and they have separate ringtone of both sims.

PhoneProfilesPlus can change only first sim ringtone.

Is it possible to include second sim ringtone setup/change in every profile settings?

Best regards to all and excuse me if this is right place for new features requests. 

Cho :)

**Comment by henrichg** [comment]
Maybe will be impleneted soon. But problem is with external tones (from storage). By my tests, external tones are reset to default internal tones. :-( I will testing this again.

**Comment by henrichg** [comment]
Ringtone for dual sim support added. Supported devices: Samsung, Xialomi, Huawei.

Tested change of ringtones for sim 1 a nd sim 2 in my Galaxy S21. Working, but problem is with testing. I'm waiting for third sim from my operator. :-) In next week will be tested ringtones also with call.

Supported is also notification tone, but this requires root (I do not know why, but by tests, is not possible to change notification tones without root. :-( ).

**Comment by henrichg** [comment]
Tested, fixed. Tested with third sim card from my operator. ;-)

**Comment by 4oSmile** [comment]
When we can expect new version with this dual sum feature?
Last version in PlayStore is 4.2.0.3 from 17.10.2020
Any beta available?

My phones: Samsung S21 Ultra 5G, Note 20 Ultra 5G, Note 10+, Note 8, Note 5

**Comment by henrichg** [comment]
All new version are ONLY in GitHub. New version will never be deployed in Google Play. Reason: all wifi functionality in Android 10 not working. Thanks to Google :-(
Version with dual sim support will be deplayed in GitHub soon. Currently I'm waiting for transaltions.
