### ISSUE TITLE
Scrollup events.

### ISSUE THREAD

**Issue by marekca** [henrichg/PhoneProfilesPlus#48]
Hello. On my two phones an tablet, I have problem when I scrollup events, the list are shaking up and down, and I can't see details, when I release finger from touch screen, the list goes up to lowest event position.

**Comment by henrichg** [comment]
Please send me screenshot or screen record. Via e-mail. Thank you.

**Comment by marekca** [comment]
Hello again. I think the problem is related to part of screen I marked red 
color, when I touch and scroll, that part of screen disappear and appear, 
You can see on recorded video. Thank You for any fix.
Marek M

**Comment by henrichg** [comment]
Please, where is video?

**Comment by marekca** [comment]
Recorded screen.
Marek M

**Comment by henrichg** [comment]
Sorry, but is not visible in GitHub.

**Comment by marekca** [comment]
I attached video file and screen shot to emails.
Marek M

**Comment by henrichg** [comment]
I'm received only email from github. And in it is not attachment.

Dňa ut 22. 10. 2019, 0:06 marekca <notifications@github.com> napísal(a):

**Comment by henrichg** [comment]
Please send me direct email: henrich.gron@gmail.com.

Dňa ut 22. 10. 2019, 0:10 Henrich Gron <henrich.gron@gmail.com> napísal(a):

**Comment by marekca** [comment]
I sent You directly to Your email screenshot and mp4 file. Did You get them?

**Comment by marekca** [comment]
All my settings in developer options are off, because I dont like animation. I played with those settings, and found, I changed "Animator duration scale" to 0.5x, and it helped. Thank You for advice, help.
