### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by scoute-dich** [henrichg/PhoneProfilesPlus#5]
Hi,

thanks for your great app. One Question: is it possible to implement a cell-tower based location trigger?

Thanks in advance
Gaukler Faun

**Comment by henrichg** [comment]
Is planned.

**Comment by scoute-dich** [comment]
Thanks a lot. I just can't wait. ;-)

**Comment by juston80** [comment]
hi, in future you can add an option to a notification sound to profile change ? Thank you so much for creating this unique application. David

**Comment by huferry** [comment]
Hi, 

Thanks, it's a great app. 
I have two problems with the event, though. Being connected to a particular bluetooth device doesn't trigger the event. And I have a calendar event that should be triggered for any title (%), ignore 'all day' and marked 'Busy'; this does not work either. I'm using One+ 1 with CyanogenMod 13. 

best regards, Ferry

**Comment by henrichg** [comment]
Hello,

1, You have enabled Events run (green semaphore)?
2. Or you have activated profile manually (orange semaphore)? Manual
profile activation pauses all events and not events will be started. Only
events with enabled "Ignore manual activation" will be started.

Read "Important info" (question mark icon in bootom bar).



Dňa po 6. 6. 2016 o 9:10 huferry <notifications@github.com> napísal(a):

> Hi,
>
> Thanks, it's a great app.
> I have two problems with the event, though. Being connected to a
> particular bluetooth device doesn't trigger the event. And I have a
> calendar event that should be triggered for any title (%), ignore 'all day'
> and marked 'Busy'; this does not work either. I'm using One+ 1 with
> CyanogenMod 13.
>
> best regards, Ferry
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/henrichg/PhoneProfilesPlus/issues/5#issuecomment-223883766>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD28Wl7bSnnn4VDoUBFdOeKOMMDcrgdRks5qI8f1gaJpZM4Hz6WI>
> .
>
-- 

           _     _
         o' |,=./ `o
            (o o)
--------ooO--(_)--Ooo----------

Henrich Gron

Tel:     +421915931555
e-mail:  work:        gron@solit.sk
                      henrich.gron@orange.sk
         mobile/home: henrich.gron@gmail.com
GitHub:  https://github.com/henrichg
Google+: +Henrich Gron
--------------------------------

**Comment by henrichg** [comment]
Mobile cells sensor parameters are added to events.

**Comment by scoute-dich** [comment]
Cool, thanks a lot! You are the best.  ;-)
