### ISSUE TITLE
Screenlock isn't set

### ISSUE THREAD

**Issue by Sander75** [henrichg/PhoneProfilesPlus#50]
PhoneProfilePlus is changing to another profile based on the conditions. 
That's working fine but the screenlock function isn't working. 
The phone stays unlocked.

By restarting the events manually this is fixed until te phone is switching to another profile (with other screen settings)

**Comment by henrichg** [comment]
What you menas screen lock? Which parameter you using for this?
Also write me device, Android version, PPP version.
Thank you.

**Comment by Sander75** [comment]
Sorry stupid from me.

I've a Samsung S8 completely  up to date
Androidversion: 9
Bestandversion: G950FXXS8DTC1
Kernelversion:  4.4.111-17263988 #1 Mon Mar 2 17:03:09 KST 2020

PPP version:  4.1.6.6 (5720)

The issue is that on profile level you can define screen settings like:
rotation, brightness and time-out.
The screentime-out is configured at 15 seconds. butthis seting is not working

**Comment by henrichg** [comment]
Ok, then, not screen lock but screen timeount is configured. Bud screen timoeut do not change lockscreen on/off, only setting in device abount screen timeout. 
In device Settings is not changed screen timeout to 15 seconds after profile activation?
Or how is configured not working profile?

**Comment by Sander75** [comment]
Oh yes I mean the option which controls the screen time out.
In my situation it should turn of the screen after 15 sec. Just like you press the on/off button on the right side of the Samsung s8.

This will also turn off the screen (and lock the phone).

This is not working anymore. 

The screen stays on unlimited.

**Comment by Sander75** [comment]
This was working perfect but since a few weeks now it stops working. 😖😖

**Comment by henrichg** [comment]
"In my situation it should turn of the screen after 15 sec. " Ok. How is configured screen timeount in device settings?
Maybe you not use screen timeout profile parameter, but "Lock device" parameter. With option "Use quick screen off". With this parameter, after profile activation. device was locked after few seconds, but before lock, is dislayed PPP dimmed black screen with text "PhoneProfilesPlus". But this must working only when profile with this parameter is activated.
