### ISSUE TITLE
android 10 can't choose ssid

### ISSUE THREAD

**Issue by Worper1997** [henrichg/PhoneProfilesPlus#52]
Hi
After upgrade to android 10 I cannot choose wifi ssid the only option is any ssid
Device is galaxy tab s6 
All permissions are granted and device is not rooted

**Comment by henrichg** [comment]
"Re-scan" button in SSID dialog not working? Location is enabled?

**Comment by Worper1997** [comment]
Yes the location had to be on to be able to select ssid
There is something else the galaxy tab s6 has a feature to turn on wifi and hotspot at the same time (and share the wifi to clients) 
Unfortunately your app doesn't allow that
1. If I enable hotspot wifi will be set to off or ignore
2. Even with wifi set to ignore,  if hotspot is on manually it won't turn on wifi

**Comment by henrichg** [comment]
Hm, not, not possible, because in other devices wifi hotspot switch not working when wi-fi is on. In my Galaxy S10 is also possible to enable wifi andalso hotspot. Hm. 
I will looking to wifi scanner, maybe is tested hotspot in it.

**Comment by henrichg** [comment]
Tested hotspot in Nexus5x with custom ROM, Android 10 and wi-fi gets off automatically when hotspot is enabled in Quick Settings (not via PPP).

**Comment by henrichg** [comment]
Hm, but in Pixel 3a, wifi stays on. Interesting.

**Comment by henrichg** [comment]
I will looking on it.

**Comment by Worper1997** [comment]
This needs hardware support
If you are looking for software it is not possible,  hardware should be able to connect to wifi and provide hotspot at the same time
Dd-wrt also has this feature but only some hardware support it

**Comment by henrichg** [comment]
Maybe it is possible for all devices with Android 10+.
In my Nexus 5x is Android 9, not 10. Sorry.
I'm changed code in scanner, for Android 10+ is wi-fi hotspot not tested. And scanning working. 
Also is possible to switch hotspot on without switching wifi off.

If you want, test this beta version: https://drive.google.com/file/d/1M37pKkrf3y3WubjMygfZiaZsR_fFQtsr/view?usp=drivesdk
Before installation do backup of PPP data. Backup is in Editor menu.

**Comment by Worper1997** [comment]
`Maybe it is possible for all devices with Android 10+.`
I still think it's hardware my galaxy tab had this with 9

Beta doesn't will at work
1.in ppp When I set hotspot on wifi turns grey
2. In android When hotspot is on it won't turn on wifi (in ppp hotspot is do not change wifi is ignore hotspot)

**Comment by henrichg** [comment]
Hm. Please test 4.1.10.2. Is in Google Play. After set hotspot on, wifi stays also on. Maybe you have configured wifi off in the same profile  as hotspot on.
Also in my S10 is possible to switch Wifi on/off when hotspot is on. Tested with Quick Tiles in S10.

**Comment by Worper1997** [comment]
4.1.10.2
1.After I set hotspot on wifi turns Gray and is do not change 
2.If I turn on hotspot manually, pull down the settings quick menu and turn hotspot on,  andmanually active a profile that says wifi on,  it will not turn the wifi on
I can turn on wifi and hotspot at the same time

**Comment by Worper1997** [comment]
However If the wifi is on ppp will turn on hotspot without changing wifi

**Comment by henrichg** [comment]
Yes and this is bug? Because it is as you want. You want:
1. switch hotspot on by PPP, keep wifi on.
2. switch wifi on/off by PPP, even when in system is hotspot on.

**Comment by Worper1997** [comment]
4.1.10.2
1.After I set hotspot on wifi turns Gray and is do not change
2.If I turn on hotspot manually, pull down the settings quick menu and turn hotspot on, andmanually active a profile that says wifi on, it will not turn the wifi on

**Comment by henrichg** [comment]
Write me, how is configured profile with hotspot on, because in my S10 wi-fi keeps on after hotspot on. But this working only for Android 10+.

**Comment by henrichg** [comment]
How to keep wi-fi on also for Android 9 is problematic, because all internet says: "switch wi-fi off for hotspot on". 
You write me "it is hardware specific", but how to check it? This is problem. 
Maybe only solution, for hotspot on an wi-fi also on, is checkin, if hotspot was changed to on and if not, disable wi-fi and set again hotspot on. :-(

**Comment by henrichg** [comment]
OK, I'm found solution. Added is option "On (do not change Wi-Fi)". Test it (version 4.1.10.3b).
https://drive.google.com/file/d/1M37pKkrf3y3WubjMygfZiaZsR_fFQtsr/view?usp=drivesdk

**Comment by henrichg** [comment]
Added it ability to wi-fi scanning when hotspot is on: Added is new option into Wi-fi scanning app Settings: "Ignore Wi-Fi hotspot".
https://drive.google.com/file/d/1M37pKkrf3y3WubjMygfZiaZsR_fFQtsr/view?usp=drivesdk

**Comment by Worper1997** [comment]
Hmm, I remember testing and answering you here but ...?
Anyway In 4.1.10.2 if I turn hotspot on wifi turns grey

**Comment by henrichg** [comment]
In 4.1.10.2 are not these changes.
