### ISSUE TITLE
Force stop on RealmeUI not working

### ISSUE THREAD

**Issue by Dre-OS** [henrichg/PhoneProfilesPlus#53]
They have moved the force stop button in the new update for Realme 5 and the app can't force stop any app automatically.

**Comment by henrichg** [comment]
Questions:
1. PhonePrfilesPlusExtender is installed? Which version?
2. If is installed, Accessibility service is enabled in it?
3. Send me any application App info screen. It must be screen with "Force stop" button.
Thank you.

**Comment by Dre-OS** [comment]
1.) 1. 5.1.3.1 (540) is the version of my PPP extension.

2.) Yes, it also prompted to the app info but didn't really press the force stop when it was there.

3.) Screenshots will be sent through email, thanks.
