### ISSUE TITLE
(feature request) Screen orientation sensor / light sensor current value preview

### ISSUE THREAD

**Issue by luszczyszenko** [henrichg/PhoneProfilesPlus#58]
Hi, 
I think that ability to preview current value of light sensor while setting thresholds might be useful feature.

**Comment by henrichg** [comment]
Added. If you want test this beta: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk
Before installation, do backup of PPP data. Backup is in Editor menu.
Current light sensor value is displayed in Orientation sensor parameters.

**Comment by luszczyszenko** [comment]
Seems to work as intended. 
2 more things
- if I not use screen orientation or display up/down parameter there should be "default" value of these parameters. 
- my light sensor shows values greater than 10000. So max sensor value parameter should not have 10k limit.

**Comment by henrichg** [comment]
1. What you means "default" parameter? If you using Light sensor,  and others as "None selected", "Don't check", then these are not used.
2. Light value is recomputed to 0-10000. PPP get max. sensor value (from system) and this value is used to recompute. In "Current light value" is displayed this recomputed value. And also in orientation sensor code.

**Comment by luszczyszenko** [comment]
Ad 1.  My misunderstanding. Sorry
Ad 2. 
![Uploading Screenshot_2020-10-13-06-55-23-067_sk.henrichg.phoneprofilesplus.jpg…]()

**Comment by henrichg** [comment]
You have installed beta version? In it is fixed display of current light value.

**Comment by henrichg** [comment]
Install this new beta. In it is fixed computation of light value. 
https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
OK, recomputation is removed. Used is native sensor value.
If you want, install this beta: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
How about this beta? You installed a tested it? Thank you.

**Comment by luszczyszenko** [comment]
Installed. I think it's ok
