### ISSUE TITLE
Request\Help?

### ISSUE THREAD

**Issue by sick13** [henrichg/PhoneProfilesPlus#59]
Does this app have Quick tile settings button (like samsung sound volume toggle for an example?) if not will you consider adding such a feature?

Say we crate several volume profiles High,Medium,Low,Vibrate and then we can add quick setting toggle and cycle trough them

**Comment by henrichg** [comment]
Quick tile is not impleneted, but is in todo list. ;-)
Will be possible to add profile as tile, for for his activation, also restart events, start, pause, stop event.

**Comment by henrichg** [comment]
Quick Tile is implented in version 5.0.1. But this version exists only in GitHub Releases or F-Droid.

**Comment by sick13** [comment]
Thank you
