### ISSUE TITLE
Standard added text/numbers to widgets

### ISSUE THREAD

**Issue by w-Oeps** [henrichg/PhoneProfilesPlus#6]
Hello
I use the widgets frequently to set my phone for a fixed time to silent when in a work meeting. I created widgets for different times. 
The app adds the number of seconds in front of the widget name I add. In practice I see 2 problems with the added number of seconds:
- It is the number of seconds. How many end-user calculate their life in seconds? :-) Number of minutes up to an hour and number of hours would be easier to understand. Seconds is a rather technical view on time in an end-user world.
- I add my own text (see screenshot) but the standard text takes almost al space for text.

Is it possible to let the end-user choose the complete text or make the generated number of second optional.
![screenshot](https://cloud.githubusercontent.com/assets/18118214/16667332/34c92dbc-448c-11e6-9463-29083f0477f3.png)

Great App BTW, I was an EasyProfiles user which was great but is not updated/available anymore. You app is better and most options easy to use!

Thanks,
Willem Oepkes
(one of the translators for Dutch)

**Comment by henrichg** [comment]
Fixed in this beta release: https://github.com/henrichg/PhoneProfilesPlus/releases/tag/3.3.9b

**Comment by w-Oeps** [comment]
Hi Henrich, Wonderful, looks much better!
Thanks, Willem
![screenshot](https://cloud.githubusercontent.com/assets/18118214/16963351/5ae6f2f4-4df6-11e6-9a4d-5b790028866f.png)
