### ISSUE TITLE
[bug] problem with adb command to grant permission

### ISSUE THREAD

**Issue by happyBOY78** [henrichg/PhoneProfilesPlus#64]
I have Realme C3, with ColorOS 7, Android 10,  latest github version of PPP, previously i was on GP version.
When i want to grant permission with command **adb shell pm grant sk.henrichg.phoneprofilesplus android.permission.WRITE_SECURE_SETTING**S

it will show me the following error : 

> Security exception: grantRuntimePermission: Neither user 2000 nor current process has android.permis
> 
> sion.GRANT_RUNTIME_PERMISSIONS.
> 
> java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has andro
> id.permission.GRANT_RUNTIME_PERMISSIONS.
>         at android.app.ContextImpl.enforce(ContextImpl.java:1955)
>         at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1983)
>         at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(Permissi
> onManagerService.java:2235)
>         at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerSer
> vice.java:133)
>         at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInterna
> lImpl.grantRuntimePermission(PermissionManagerService.java:3338)
>         at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.
> java:6587)
>         at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerS
> hellCommand.java:2015)
>         at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.jav
> a:234)
>         at android.os.ShellCommand.exec(ShellCommand.java:104)
>         at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:238
> 59)
>         at android.os.Binder.shellCommand(Binder.java:881)
>         at android.os.Binder.onTransact(Binder.java:765)
>         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5100)
>         at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4735)
>         at com.android.server.pm.OppoPackageManagerService.onTransact(OppoPackageManagerService.java
> :83)
>         at android.os.Binder.execTransactInternal(Binder.java:1021)
>         at android.os.Binder.execTransact(Binder.java:994)
> 
I see on PPP xda forum guy with the same problem, but i did not find solution.

In other app like Tiles or Tasker i don´t have problem with adb commands.
Please help

**Comment by henrichg** [comment]
Hm, hm. Maybe added is another security for this in Realme. Or maybe PPP is not running in secure mode of device?

Other permissions is possible to grant? For example Phone, Storage, Calendar, ...?
Group GRANT_RUNTIME_PERMISSIONS is for these runtime permissions.

Maybe restart of device helps?

Write here link for "I see on PPP xda forum guy with the same problem, but i did not find solution.".
Thank you.

**Comment by Dre-OS** [comment]
@happyBOY78 Try enabling "Disable Permission Monitoring" on Developer options while you do the adb  grant cause it works for me, hope this helps

**Comment by henrichg** [comment]
Thank you Dre-OS.
Another solution (maybe also for ColorOs, in Xiaomi it is) is:  Enable "Developer options"/"USB debuging (Security settings)".

**Comment by happyBOY78** [comment]
> @happyBOY78 Try enabling "Disable Permission Monitoring" on Developer options while you do the adb grant cause it works for me, hope this helps

**Comment by happyBOY78** [comment]
@Dre-OS Thank you for your tip to enabling "Disable Permission Monitoring". It works for me too. 
Thank you @henrichg for your time in this issue.
_Děkuji za super apku a posílám pozdravy na Slovensko :-)_

**Comment by henrichg** [comment]
Good. :-)
_Nie je zaco. ;-)_
