### ISSUE TITLE
Screen-off timeout not working

### ISSUE THREAD

**Issue by happyBOY78** [henrichg/PhoneProfilesPlus#65]
Hi,
if i set in profile screen-off timeout to other value than original setted by phone settings, it is not working for me.
In PPP is new value set for example to 5 minutes, profile activated, but nothing changed in phone settings, value remain original.
The same problem i have in app named Tiles [https://play.google.com/store/apps/details?id=com.rascarlo.quick.settings.tiles](url), in this app all tiles working for me, except Screen-off timeout, with the same error as in PPP.
Realme C3, ColorOS 7,Android 10, not rooted.

_Ahoj,
když v profilu změním čas do vypnutí obrazovky na hodnotu jinou, než mám nastavenou přes klasické nastavení telefonu, tak mi to v PPP nefunguje.
Čas vypnutí obrazovky nastavím např. na 5 minut, aktivuju profil, ale nestane se vůbec nic, v nastavení mobilu zůstane původní hodnota, ačkoliv v profilu PPP je těch 5 minut.
Stejný problém mám i v aplikaci Tiles, tam až nastavím čas vypnutí jaký chci, stejně mi zůstane ta původní.
Mám podezření, že za to může nadstavba ColorOS ale nevím, jak z toho ven..._

**Comment by henrichg** [comment]
By me, this is ColorOs issue. Because change of screen timeout working good, in Pixel 3a with Android 11, Galaxy S10 with Android 10. 
But this function requires permission "Modify system settings". Is granted? Look at PPP "Settings"/"Permissions".

**Comment by happyBOY78** [comment]
All required permissions i have granted (see attached pic). This problem i have only on Realme, on my previous phone it was OK.
Is any workaround, which will solve this ?
May i send some logs or something like that.

![Screenshot_2021-01-27-17-45-02-81](https://user-images.githubusercontent.com/6315249/106024216-d8fab700-60c7-11eb-87db-a351c5778e78.jpg)

**Comment by henrichg** [comment]
Then I do not know. This must be problem with ColorOs.
Excepton is catched and when occurs, will be invocked send it via e-mail. 
By me this is ignored by ColorOs:
`Settings.System.putInt(appContext.getContentResolver(), Settings.System.SCREEN_OFF_TIMEOUT, value);`

**Comment by happyBOY78** [comment]
And is any way, how can i test, if ColorOS ignore it  or how can i find the correct syntax on ColorOS ? (via ADB SHELL for example).

**Comment by happyBOY78** [comment]
I try i with this command `adb shell settings put system screen_off_timeout 600000` and it works.
Checked in phone settings and with `adb shell settings get system screen_off_timeout` too.

**Comment by henrichg** [comment]
Hm, maybe this will working for ColorOs. But I must develp it for ColorOs.
Your device is rooted?

**Comment by happyBOY78** [comment]
No, it is not rooted. 
I found some links, I'm not sure,if it will help you..
```
https://stackoverflow.com/questions/13696891/programmatically-set-screen-to-off-in-android
https://stackoverflow.com/questions/44691810/how-to-get-default-screen-timeout-time-from-settings-programmatically
https://stackoverflow.com/questions/10748861/how-to-change-screen-timeout-programmatically
```

**Comment by henrichg** [comment]
OK, test this beta, if you want: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk
In it is called 'settings' command line utility in non-rooted shell. But only for Oppo and Realme devices.
Enabled is also log to file. After test, send me it. For this use in Editor menu "Support/E-mali debug log files to author".

**Comment by happyBOY78** [comment]
So I just try to change timeout in PPP and after it send you logs ? Nothing else?

**Comment by henrichg** [comment]
1. Install beta.
2. Test screen timeout change with profile activation.
3. Send me log.

**Comment by happyBOY78** [comment]
Done.

**Comment by henrichg** [comment]
Hm? You have installed beta? Because you send me backup of PPP data, but from 4.3.1. Beta is 4.3.2b (6359).
You must install beta. Link is: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk
And send me log, not PPP data backup: Editor menu "Support/E-mali debug log files to author".

**Comment by happyBOY78** [comment]
Dorty, my mistake, i reinstaled it with beta, activate profil and send you mail again.

**Comment by henrichg** [comment]
Read e-mail. ;-)

**Comment by henrichg** [comment]
OK, tested by you and call of 'settings' command not working. By me, without root not working at all. Not good, not good.
