### ISSUE TITLE
Restart events doesn't work

### ISSUE THREAD

**Issue by lotfixyz** [henrichg/PhoneProfilesPlus#66]
"Event preferences » End of event » More actions » Restart events" doesn't work.

**Comment by henrichg** [comment]
Restart events is not in "Other parameters" it is directly in "End of event" in "More actions". This not working? In my all devices working. You are first user, which report this bug.

**Comment by Retrodynen** [comment]
I'm getting the same. Last log entry is "restart events" then nothing, almost as if it hangs.

**Comment by henrichg** [comment]
@Retrodynen please, send me PPP version. I do not have this problem. Tested in several mobiles, currently daily mobile is Galaxy S21. 
In my PPP configuration is this parameter configured. Working good each day.
After restart of events, all events are paused, then started by its sensors, profiles are activated. All is visible in Activity log.

**Comment by Retrodynen** [comment]
Hello,

Sorry, I've managed to resolve the issue now. It seems my phone had set PPP to use "only allow location when all is open", it wasn't that before but I assume I messed up some time ago
:)

I changed it to always allow and now the Wi-Fi sensor works properly (my most used one).

No issue for me now.

Sorry to waste your time



*From: *Henrich Gron <notifications@github.com>
*To: *henrichg/PhoneProfilesPlus <PhoneProfilesPlus@noreply.github.com>
*CC: *Retrodynen <gh@milktr.uk>, Mention <mention@noreply.github.com>
*Received: *25 Feb 2021 13:32:26
*Subject: *Re: [henrichg/PhoneProfilesPlus] Restart events doesn't work (#66)

**Comment by henrichg** [comment]
OK. ;-)
