### ISSUE TITLE
Rovoking of profiles (managed by sensor event) ends up in manual activation of the same profile

### ISSUE THREAD

**Issue by florian-rabis** [henrichg/PhoneProfilesPlus#68]
Hey,
I think there is a bug when my `disconnect` profile should revoke if the screen comes on again it get a [M] status. This happens only when the previous profile was activated manually. In case of a fully event managed profile activation everything works as expected.

expected behavior:
- 3 Profiles:
    - `default` (on in all other cases)
    - `night` (managed by timeevent from 22 h to 6 h)
    - `disconnect` (managed by sensorevent: screen off)
- sensor event:
    - when the screen goes off the `disconnect` profile should deactivate all connections, delayed by 10 seconds
    - when the screen goes on again the previous activated profile should continue regardless of the previous profile was activated by event or manual

observed behavior:
example:
- after 22 h the `night` profile will activated automatically and starts the airplane mode
- when I want to be still connected I activate the `default` profile manually
- then when I turn the screen off and switch back on after more then 10 seconds the profiles had changed from `default` to `disconnect [>> screen off]` and then to `disconnect [M]`

I dont think that it's caused by my system. Recently I changed to test purposes from lineage 17.1 opengapps to lineage 17.1 microg on my OnePlus 3T without any impact.
Or is it maybe a configuration problem?

Best regards

**Comment by henrichg** [comment]
Your device is rooted? Because airplane mode switch working only in rooted device.

Profiles:
"Default" is configured as Default profile? This will activated when not any event is runing. And this switch airplane mode off?
"Night"  this switch airplane mode on?
"Disconnect" - what is configured in this profile?

Events (give me names of events):
- At 22h starts event, which activates profile "Night". Yes?
- "Disconnect" profile is activated manually after 22h. Yes? And event "Night" stays running? Is in this event enabled parameter "Ignore manual activation"?
- Event for screen on/offf exists? Which profile is activated from this event? What is configured at end of this event?

**Comment by florian-rabis** [comment]
Yes my device is rooted.
Yes the `default` profile is set as default and starts successfull when no other profile is activated manually instead.
Yes the `night` profile switches successfully into airplane mode in any case (by event or manually).

The `disconnect` profile has the task of saving energy by disconnecting all connections. This profile should be activated 10 seconds after the screen is switched off by the event `screen off`.

> At 22h starts event, which activates profile "Night". Yes?

Right. This time event is also called `night`.

> "Disconnect" profile is activated manually after 22h. Yes?

No. It should actually never be neccessary to activate the `disconnect` profile manually. This profile is only managed automatically when the screen goes off. The events have priorities and the `night`-event has a higher priority (5). The disconnect event has the priority 4. If the `night` event takes place then the airplane mode already disconnect everything. So then there is no need to activate the `disconnect` profile too.
In the `screen off` event the parameter "Ignore manual activation" is set. Because it should disconnect undependend from the activated profile except at night when airplane mode is already activated.

> And event "Night" stays running? Is in this event enabled parameter "Ignore manual activation"?

It's a bit confusing I see. OK the scenario is that in normal case my profiles should managed by events automatically. But sometimes I want to stay connected for example at night between 22 and 6 h. Then I need to activate the default profile manually.
But when I turn off the screen my phone should disconnect never the less what happen otherwise. To this point everything works fine. But when I switch my screen on then the `disconnect` profile goes not back to the previous activated profile rather it keeps activated. It only switches from `[>> screen off]` to `[M]`. But this happen only when the previous profile (for example the the `default` profile) was activated *manually*.

> Event for screen on/offf exists? Which profile is activated from this event? What is configured at end of this event?

See above.

> What is configured at end of this event?

All events should revoke their linked profile to fallback to the previous activated profile when it ends.

I hope I could describe it a bit better now. Thank's for the very fast response.

**Comment by henrichg** [comment]
1. At 22:00 - starts "night" event, this activates profile with airplane on
2. After 22:00 - manuall profile activation of profile "default" - this set airplane off? Is this configured in it?
3. At screen off (is event for this?) is activated profile "disconnect" - this disconnect from wifi, mobile data, bt, ... but not set back airplane mode? And event has at it's end what?

By me, better will be send me your PPP data. For this is function in Editor menu in "Support".

**Comment by florian-rabis** [comment]
Sorry for the late response. I tried several combinations in my configuration but the described problem still remains.

Here is my configuration. I'm german. So the names of profiles and events are in german.

[PhoneProfilesPlus.zip](https://github.com/henrichg/PhoneProfilesPlus/files/6252672/PhoneProfilesPlus.zip)

**Comment by florian-rabis** [comment]
>     1. At 22:00 - starts "night" event, this activates profile with airplane on
Yes.

>     2. After 22:00 - manuall profile activation of profile "default" - this set airplane off? Is this configured in it?
Yes but that is not the point. This works perfectly.

>     3. At screen off (is event for this?) is activated profile "disconnect" - this disconnect from wifi, mobile data, bt, ... but not set back airplane mode? And event has at it's end what?
Yes the `disconnect` profile does not activate airplane mode but only disconnect all conncetions instead gsm for phone calls.
The Event has no end it's still an event. The profile `disconnect` should end when the screen goes on. Alternatively I could configure another event which deactivtes the `disconnect` profile when the screen goes on. But it is not possible to deactivate a profile by an event, or?

The night scenario is obviously a bad example. It only goes about the point to saving energy by disabling all connections when the screen is off but I want to be reachable by phone calls.

It works partly when I configure the `screen off` event to restart all events or when it activate another profile like the `default` profile when it ends

But that is not suitable for some situations like a meeting where I need to activate another profile manually which is not configured in the events maybe `quiet` or what else. Then it would not return to this previously activated profile (`quiet`) rather to `default` or it restarts all events which will start `loud` depending on daytime.

**Comment by henrichg** [comment]
In all your profiles is Airplane mode off, only Nacht set it On. OK.

Nacht event is ended at manual actiation of "disconnect" profile, because Nacht event do not have configured paramrter "Ignore manual activation". Maybe this is your problem.

Also: In all your events is at its End is used "Undo". And this not working? Undo not working? By me working, because Undo gets back profile activated before start of event Nacht. Maybe event Bildschirm aus is good to use Undo. But not for others.

But by me is usage of Undo not good in your situations. More better is using restart events.

**Comment by florian-rabis** [comment]
Your suggestion has no effect. Please forget the night profile. It was just an example to describe the problem.

> In all your events is at its End is used "Undo". And this not working? Undo not working?

Yes. Undo works not as expected I think!

I did some screenshots to illustrate my problem.

### 1. case: night profile is activated manually:

![Screenshot_20210404-225708_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114033427-8be05180-987d-11eb-87b4-43e4a930e7a8.png)

- screen goes off and on again, `disconnect` profile is active as expected. (it takes a short while till the app reacts)

![Screenshot_20210404-225924_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034373-6b64c700-987e-11eb-8ecd-7745c2a92ebd.png)

- now the problem takes place. The `disconnect` profile or event does not undo. It still keeps activated manually as shown in the brackets.

![Screenshot_20210404-225934_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034217-4708ea80-987e-11eb-84a2-cdc6376975d0.png)

### 2. case: default profile is activated by default. No event is running. And everything works well.

![Screenshot_20210404-230003_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034218-47a18100-987e-11eb-903a-635012b3a254.png)

![Screenshot_20210404-230040_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034220-47a18100-987e-11eb-9fb5-5891cf381d2c.png)

![Screenshot_20210404-230053_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034221-483a1780-987e-11eb-8c1f-3c5dd09a429e.png)

### 3. case: `loud` profile is activated manually

![Screenshot_20210404-230112_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034224-483a1780-987e-11eb-885e-8ccadac921a7.png)

![Screenshot_20210404-230142_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034226-48d2ae00-987e-11eb-8867-1454c8f24431.png)

- When the screen goes on again the `disconnect` profile keeps activated:

![Screenshot_20210404-230151_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034227-48d2ae00-987e-11eb-90f8-afac9f290ff6.png)

### 4. case: `night` profile is activated by `night` event and has a higher priority as the `screen off` event so it works as expected

![Screenshot_20210404-230324_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034229-496b4480-987e-11eb-928b-c418abd045ce.png)

- screen goes off and on again:

![Screenshot_20210404-230409_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114034232-4a03db00-987e-11eb-871c-6259eb53420f.png)

### 5. case: `loud` profile is activated by `loud` event

![Screenshot_20210408-154018_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114037771-91d83180-9881-11eb-8761-ed097c5b06b7.png)

![Screenshot_20210408-154038_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114037774-9270c800-9881-11eb-9571-ddf94b06afe4.png)

- The `disconnect` event does not undo. It keeps activated by the `loud` event. The `loud` event has a lower priority as the `screen off` event

![Screenshot_20210408-154045_Trebuchet_1](https://user-images.githubusercontent.com/15198883/114037776-9270c800-9881-11eb-979d-dfac3a043591.png)

**Comment by henrichg** [comment]
I'm testing your data in my Pixel 3a. 

After screen off, started was event Bildschim aus, activated profile Getrennt.
At screen on Bildschim aus was ended, activated was previous activated profile Laut with running event Laut.

Next test. Laut activated manually, screen off. After screen on, Laut was activated again manually. Also during screen off was running event Bildschim aus, activated profile Getrennt.

In my Pixel 3a all working good.

You testing which PPP version? In Pixel 3a I have installed latest 4.4b

**Comment by florian-rabis** [comment]
Wow. Ok it works now. I had installed version 4.2.0.3 from the Aurora-Store, which is the most recent there. So I did not check if there is a newer one.
Now I use release 4.3.2 of this repository.

Everything works as expected now without changing any configuration. It is amazingly fast now. Sorry for that inconvenience. Great work and thank you for your patience.
