### ISSUE TITLE
Select Multiple Cells for delete

### ISSUE THREAD

**Issue by scrunchy** [henrichg/PhoneProfilesPlus#71]
I end up getting a large number of 'new' cells that build up and appear to impact the response of the app when editing profiles.

To clean out all the unwanted cells takes a long time with single select-then-delete actions.

Is it possible to allow for multiple selections to be made and offer a 'delete' option?

**Comment by henrichg** [comment]
Maybe add into popup menu for cell "Delete all selected". Into each cell popup menu. Is this OK for you?
Because is not space in dialog to add new icon for delete all selected cells.

**Comment by henrichg** [comment]
Functionality added. Will be in next release.
