### ISSUE TITLE
Grouping profiles and events

### ISSUE THREAD

**Issue by Dre-OS** [henrichg/PhoneProfilesPlus#72]
It would be easier to edit profiles and events if there is an option to group them into drop-down folders that can be renamed. Make it an option in the drop-down menu located near the text title "editor". thank you man, appreciate it!

**Comment by henrichg** [comment]
Sorry, but I do not understand correctly. Grouping profiles and events? 
How to use it? Display only profiles and events in selected group? And add all groups to "Filter" spinner (it is at top bar)?

**Comment by Dre-OS** [comment]
I'll edit a photo soon as an example, I'll send it when its done
