### ISSUE TITLE
Auto connect vpn

### ISSUE THREAD

**Issue by J4gQBqqR** [henrichg/PhoneProfilesPlus#73]
Automatically connect to VPN under specific profile.

Is this feature even possible to implement with current Android API?

**Comment by henrichg** [comment]
I do not know. Maybe. I will looking on it.

**Comment by henrichg** [comment]
Added. But only parameter of type (I). Is in profile preferences Radios as "(I) VPN Settings" at bottom of this section.
It opens device VPV setings screen. From this scree you can add, enable/disalbe VPN profile.
If you want, install this beta: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
Or exists this: https://play.google.com/store/apps/details?id=de.blinkt.openvpn
GitHub: https://github.com/schwabe/ics-openvpn

And with it is possible to connect/disconnect profile from any Androoid application.
Example: https://github.com/schwabe/ics-openvpn/tree/master/remoteExample

Information about this open-source version is from: https://openvpn.net/vpn-server-resources/connecting-to-access-server-with-android/

**Comment by J4gQBqqR** [comment]
Thank you so much for this awesome app! Could you point me to a place where I can make a donation?

**Comment by henrichg** [comment]
IN PPP Editor menu is "Please donate". Also in "Abount application" is button "Please donate".
Thank you very much.
