### ISSUE TITLE
"When duration expires" from Activator applied after automatic activation

### ISSUE THREAD

**Issue by mpr0st** [henrichg/PhoneProfilesPlus#74]
Hi.

First of all, thank you for this great piece of software, best app I've ever seen to manage profiles by a great distance.

I'm having an issue, hope you can help me with it.

**Steps to reproduce**

1. In PPP, 3-dots menu, Stop events (don't know if this is necessary, but that's what I did).
2. Manually activate a profile using the Activator, using these settings and pressing OK:

![Screenshot_20210801-104634_PhoneProfilesPlus](https://user-images.githubusercontent.com/49242687/127766171-965cc9cc-3323-45ed-8007-04f4833e5a54.png)

(This part works well, "sleep" is activated and, after 10 minutes, "home" is activated).

3. After a few hours, Enable run events.

**Expected behaviour**

Automatic activation ignores previous manual activations via Activator.

**Actual behaviour**

Previous manual activation via Activator is taken into account:

![Image 3](https://user-images.githubusercontent.com/49242687/127766326-a03879ed-9aed-4261-8eb5-20f32d454a33.png)

Note how exactly 10 minutes after "sleep" activation via an event at 22:00, "home" is activated again (that's not expected).

The event is pretty simple:

![Image 4](https://user-images.githubusercontent.com/49242687/127766707-3a2bb0e1-ebcf-4091-8e8b-959fd24dfee2.png)

Thank you.

Note: I'm using version 5.0.1 (6620), Android 11 (LineageOS 18.1), root privileges granted to PPP.

**Comment by henrichg** [comment]
"Stop events" stops global run of events. Not any event will be started and all running are ended.
"Enabe events run" starts events. Internally this invoke Restart events.

In your Activity log is:
1. start of events "overnight".
2. activation of profile "sleep" - it is with duration with activation of profile "home".This type of duration end has exception. It do not pause event, thus, event "overnight" stays running. It is also visible in Activity log. "overnight" was not ended in log.

In your log is not manual activation of sleep, but by event "overnight". 22:00:16 is activation from event "overnight" not from Activator.

**Comment by henrichg** [comment]
Look at parameter in profile "When duration expires":
"[M] Restart events"
"[M] Undo the profile"
"[M] Activate Default profile"
"Activate specific profile"
"Do nothing"

All types marked with "[M]" will be invoked only when profile is activated manually (not form event). Only "Activate specific profile" has exception from this (is not marked with "[M]").

**Comment by mpr0st** [comment]
Thank you for your quick answer.

If I'm understanding correctly, you're telling me that, given that "Activate specific profile" doesn't have a "[M]", when I choose that option, the duration and profile I choose (10 minutes and "home" in my case) is going to get saved in the profile:

![Image 5](https://user-images.githubusercontent.com/49242687/127776533-19c9de90-f845-4ebd-b9fd-4f6867b24e1f.png)

And all subsequent automatic activations (i.e. via event), day after day, will apply that duration, correct?

If this is the case:

1. How do I get rid of that 10 minutes? As you can see in the screenshot, it's greyed out, so I can't edit it there.
2. Could you please consider making "Activate specific profile" from Activator independent from the settings in my screenshot? I think it would be useful to be able to use Activator for this, activate a profile for 10 minutes and, after that, resuming the normal processing of events (i.e., forget that 10 minutes) as soon as I Enable run events.

Thank you.

**Comment by henrichg** [comment]
"[M] Ask for duration" is used ONLY when profile is activated manually (has [M] indicator). Is not used when profile is activated by event. And yes, duration parameters from "Ask for duration" dialog are saved for next usage by "Ask for duration". If profile is activated by event, "Ask for duration" is ignored, profile is activated WITHOUT duration.

**Comment by henrichg** [comment]
By me, in your first screenshot you have disabled "[M] Ask for duration". I'm tested event with profile which has enabled "[M] Ask for duration" with duration 15 seconds and "After duration do"="Activate specific profile" and profile is activated permanently, not for 15 seconds. Duration is not used.

**Comment by mpr0st** [comment]
Hi, and thank you again for your answer.

I've installed the app in a clean Memu emulator and performed the following steps:

1. Install app and open.
2. Allow “Do not disturb access” in system settings. Select “Don’t optimize” battery for PPP.
3. As I am executing this steps at 18:00-18:30, modify Time sensor of Overnight profile to start at 18:55. Enable run the profile.
4. In Sleep profile, enable “[M] Ask for duration”.
5. In Activator, activate profile Sleep, duration 10 minutes, When duration expires: Activate specific profile. Profile to activate: Home. (de: 18:43:51, see log).
6. Home profile is correctly activated at 18:43 (see log).
7. Open PPP, press "Restart events" button (see log).
8. At 18:55 event overnight fires and profile Sleep [Overnight] gets activated (see log).
9. At 19:05 the profile Home gets activated (see log).

So my question is, is step 9 above by design or is it a bug?

Thank you.

Note: here's is the full log:

![Screenshot_20210802-190739](https://user-images.githubusercontent.com/49242687/127902140-e2920cfb-ac1e-4ce5-a0e2-add9c6a24872.png)

![Screenshot_20210802-190724](https://user-images.githubusercontent.com/49242687/127902151-53d0249a-9655-4450-9645-4894ff648782.png)

And here a backup of the configuration:
[PPP backup.zip](https://github.com/henrichg/PhoneProfilesPlus/files/6918740/PPP.backup.zip)

**Comment by henrichg** [comment]
What is "'Memu emulator"?

Please send me PPP data from emulator. Use for this in Editor menu: Support/E-mail settings to autohor.
Because thi si not good.  "Ask for duration" is ignored for activation from event. I'm tested this yesterday.

Or use (if e-mail client not working in emulator) in Editor Backup/Restore -> Backup settings. Then copy both .backup files from emulator to PC and send me both via e-mail.

**Comment by henrichg** [comment]
Hohoho. You are right. Used is duration even when is profile activated from event. Tested in my Galaxy S10, latest beta version of PPP. :-( I must fix it. Thank you.

**Comment by henrichg** [comment]
Fixed. If you want, install this beta version: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by mpr0st** [comment]
Thank you very much for fixing it. I tested it and it appears to be working well.

**Comment by henrichg** [comment]
Good! ;-)
