### ISSUE TITLE
Widget not working correctly as of 5.1.0.1

### ISSUE THREAD

**Issue by stantastick** [henrichg/PhoneProfilesPlus#76]
I can't be exactly sure when this occurred, but 5.1.0.1 was released about 4 days ago, and I noticed within the last 3 days that tapping on the PhoneProfilesPlus Widget on my Home Page (Galaxy S10 running Android 11) no longer gives me the Yes/No option to turn a profile on or off, but IMMEDIATELY sends me to the PhoneProfilesPlus Editor page. I can choose the profile I want there and activate it using the 3-dot menu on the right side, but that's not as simple as it was when the widget was working just 4 or 5 days ago. Is this reproducible by anyone else? Or did another update to another application cause the problem? Thanx...

**Comment by henrichg** [comment]
Widget detects this profile as "red". In it are some errors. Also in Editor is not possible to activate it. Profile in Editor must be displayed its name with red color. You must fix these errors. Click profile. At top of preferences are displayed errors (red texts). Fix it. Also parameters with errors are displayed with red color. Fix it.

**Comment by henrichg** [comment]
I'm fond bug for profile and event parameters which uses PPPExtender. Maybe your profile use one of theses parameters. Fixed. If you want install this beta: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by stantastick** [comment]
Hi, Henrich -- installed the beta but didn't fix the problem :-(The "Shortcut 1x1" and the "List 4x4" widgets both work as expected. The "Icon 1x1" and the "Single Row 4x1" both have the issue described -- tapping on them immediately displays what I think they should display, then in a blink of an eye take me to the Editor.I was able to place the List 4x4 in a 1-row space and adjust the bottom to bring it up to only take up one row, but it looks cramped on my opening Home Screen. I liked using the Single Row 4x1, tapping on it, then choosing from the pop-up list. But, that no longer wants to work.StanSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Henrich Gron ***@***.***> Date: 8/20/21  11:45 PM  (GMT-08:00) To: henrichg/PhoneProfilesPlus ***@***.***> Cc: stantastick ***@***.***>, Author ***@***.***> Subject: Re: [henrichg/PhoneProfilesPlus] Widget not working correctly as of 5.1.0.1 (#76) 
I'm fond bug for profile and event parameters which uses PPPExtender. Maybe your profile use one of theses parameters. Fixed. If you want install this beta: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by henrichg** [comment]
Shortcut activates profile. Widget 1x1 (icon), 4x1 (row) opens Activator (or Editor, when it is configured in Settings/Application interface). Widget 4x4 (list) is special. Click to header opens Activator/Editor (again by configuration), click to profile in grid/list activates profile.

Installl and test this beta 5.1.0.2b (6643). In it is again enabled click to all profiles in Activator. Also activation in Editor is enabled for all profiles: https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by stantastick** [comment]
Hi, Henrich —

That beta update 5.1.0.2b (6643) link you just sent fixed it!! Yay!

Thanks,

Stan

**Comment by henrichg** [comment]
Good! Soon will be released new version. 😏 Thank you for testing it.
