### ISSUE TITLE
Mode airplane

### ISSUE THREAD

**Issue by orlproi** [henrichg/PhoneProfilesPlus#79]
I don't have root and airplane mode doesn't work. Can't implement like with Macrodroid or similar that work even without root? Thanks

**Comment by henrichg** [comment]
In Macrodroid is possible to set airplane mode? By me it is not possible for several years.
Please write me, how to configure it in Macrodorid. I will test it.
And write me your device type/name and Android version.

**Comment by orlproi** [comment]
Samsung A600FN with Android 10. With Macrodroid just set the event and it works. But it is more complicated to put various events together.

**Comment by henrichg** [comment]
Official Macrodroid wiki :
https://macrodroidforum.com/wiki/index.php?title=Action:_Airplane_Mode_On/Off&mobileaction=toggle_view_desktop
Not possible without root.

Maybe with AutoInput? In PPP is not this fuctionality.

"You can use the AutoInput plugin on non root devices to automate the button presses needed to toggle airplane mode on and off."

https://www.tapatalk.com/groups/macrodroid/flight-mode-without-root-t1875.html

**Comment by henrichg** [comment]
Maybe this? "... or you must make MacroDroid the default assist app on your device (Android 7+)"
But this require set PPP as default Assist app. But then is not possible to use Google Assistant, Bixby, ...

**Comment by orlproi** [comment]
Indeed: By making MacroDroid the default assist app it has access to control the device's airplane mode (which is impossible without it).

Yes I had to enable the Macrodroid assistant instead of Google.

**Comment by henrichg** [comment]
Hm hm, I must check it.

**Comment by henrichg** [comment]
I'm found, how to set application as assistant. It is from Google:
https://developer.android.com/training/articles/assistant#implementing_your_own_assistant

In Macrodroid source I'm found:

android.settings.VOICE_CONTROL_AIRPLANE_MODE
android.settings.VOICE_CONTROL_DO_NOT_DISTURB_MODE -- why? This working good in PPP, hm, hm
android.settings.VOICE_CONTROL_BATTERY_SAVER_MODE -- not needed, requires grant of write_secure_settings (G1)

Next: implentation. ;-)

**Comment by henrichg** [comment]
Please write me, how to working airplane mode on/off  in Macrodorid, when is set as assistant? By inspection of its source code, user rmust long press home button. Is this correct?

**Comment by henrichg** [comment]
Ok, ignore last question. Macrodroid supports home button long click, but is possible to use also action. ;-)

**Comment by henrichg** [comment]
Done. 
If you want, test it:
https://drive.google.com/file/d/1KMasYeFp47knvOJkmQyvuXbcFPNwyF43/view?usp=drivesdk

**Comment by orlproi** [comment]
It works .... thanks. In the 'Radio' section once 'Airplane Mode' has been activated, perhaps it is useful to make the other options inactive. Will other users like to turn off the google assistant? But it is the only means if the phone is not rooted.
Sorry Google Translation

**Comment by henrichg** [comment]
1. Disabling other parameters (moble data, wi-fi, bluetooth) is not good. Because is possible also in device settngs enable these parameters also when airplane mode is set ON.
2. Change default assistant is user choice. In Samsung devices exists also Samsung assistant. User choice.
3. If device is rooted, "Assistant settings" parameter is disabled.
