### ISSUE TITLE
Please support custom number of steps for volume

### ISSUE THREAD

**Issue by Forever-Young** [henrichg/PhoneProfilesPlus#8]
Number of steps can be changed by some xposed modules. 
Right now profile editor shows me e.g. 10/7

**Comment by henrichg** [comment]
Max volume is from Android API AudioManager.getStreamMaxVolume().
And set volume is by AudioManager.setStreamVolume().
By me xposed module do not change these functions to get/set volumes.

**Comment by Forever-Young** [comment]
Changed from GravityBox to VolumeSteps+ for that feature helped me, thanks.
