### ISSUE TITLE
Bug - Mobile data does not turn on/off automatically under profiles

### ISSUE THREAD

**Issue by andyxo-xo** [henrichg/PhoneProfilesPlus#82]
Hi, I have the mobile data "radio" set to turn on automatially under a profile called "Out" and to shut off automatically under a profile called "Home". But it doesn't work, it doesn't turn on nor will it shut off. On the other hand, the wifi settings I have set up to automatically turn on/off when I change profiles works great, it's only the mobile data that I can't get to work. In other words, setting wifi on/off under profiles works fine but setting mobile data to turn on/off under profiles does not work at all for me. What further troubleshooting would you like me to perform? Cheers...

Android 11, Pixel 4a, PhoneProfilesPlus v5.2

**Comment by henrichg** [comment]
Is your Pixel rooted? Switch mobile data on/off requires root. All profile parameters marked with (R) requires root.

**Comment by andyxo-xo** [comment]
Yes, my phone is rooted with Magisk... how can I get it to work? Are special settings that I don't know about needed? Thanks...

**Comment by andyxo-xo** [comment]
Yes, my phone is rooted with Magisk... how can I get it to work? Are special settings that I don't know about needed? Thanks...

**Comment by henrichg** [comment]
PPP uses for switch mobile data commands:

- svc data enable
- svc data disable

In my Pixel 3a is supported one hw. SIM card and one eSIM. How about Pixel 4?
PPP do not supports eSIM.

You can test commands in your device.

How to use adb is in this md: https://github.com/henrichg/PhoneProfilesPlus/blob/master/docs/grant_g1_permission.md

But instead "adb shell pm grant..." use 
- adb shell svc data enable
- adb shell svc data disable

Thanks for test.

**Comment by henrichg** [comment]
Please check also, if root for PPP is granted. Look in Magisk Manager for this.

And please send me url link, how to grant Pixel device. I want to root my Pixel 3a. Thank you very much.

**Comment by andyxo-xo** [comment]
Sorry if I wasn't clear in my last post... I had to grant "PhoneProfilesPlus" root access in Magisk. After I did that mobile data is now turning on/off as it should. It was my mistake.

As far as your Pixel 3a root... sorry but I have a Pixel 4a. If you wish to root your 3a might I suggest taking a look at the XDA forum to see if somebody there has posted on how to do that...

**Comment by henrichg** [comment]
OK Thank you. ;-)
