### ISSUE TITLE
Check WLAN state before change

### ISSUE THREAD

**Issue by chris-asdf** [henrichg/PhoneProfilesPlus#83]
Hi,

I just noticed, that a profile which should enable the WLAN radio, turns it first off and then on again. Even when the radio was active beforehand. 
Is that intentional? I assumed, that PPP checks the state before doing anything to the radio...

Thanks, and all the best
Chris

**Comment by henrichg** [comment]
This is checked. Mobile data switch requires root and called is "svc data on", "svc data off". and checked is with TelephonyService.getDataEnabled().

Maybe another parameter in profile switch it off, before call of mobile data on. By me "Change network type". "Change network type" is called before switch of mobile data.

**Comment by chris-asdf** [comment]
So to check if WLAN is enabled or not requires also root (my phone isn't rooted)?
Do I understand this correctly, the state can be checked via the radio sensor? But if I want the profile to be started when the phone is connected to a specific network, how can that accomplished w/o root and w/o turning the radio off and on again?

**Comment by henrichg** [comment]
If your device is not rooted switch mobile data on/off is not possible. Also change network type requires root.
Check if mobile data is on/off do not require root. All radios in event Radio sensor do not require root.
Check if device is connected to specific network is not implemented in PPP.

**Comment by chris-asdf** [comment]
Sorry for the delay.
I know, the mobile radio needs root, but I'm interested in the WLAN/WiFi radio. As I understand it, for that purpose no root is needed.

**Comment by henrichg** [comment]
Staus tested also for Wi-Fi on/off.
Called is: WifiManager.getWifiState();

You tested manual profile activation? Why do you think Wi-Fi will turn off and on?

Maybe it is problem in events and profiles configuration,

**Comment by chris-asdf** [comment]
The profile config gave me the hint! My bad, I configured it to connect to a specific SSID which will of course cause the observed behaviour!

Thanks a lot, it's working now as expected.

**Comment by henrichg** [comment]
If device is connected to Wi-Fi and actuls connected SSID from system is not in profile configured SSID, then SSID is changed. This is as you want.

But problem is with this:
Wi-Fi must be diconnected from actual connected SSID. Without this, connection to another SSID not working. :-(

**Comment by chris-asdf** [comment]
Yes, your described problem is what I was seeing there.

So from my point of view, since I had the forced connect to a specific SSID mis-configured in my profile, you can close this issue.
