### ISSUE TITLE
[Feature request] Add support for toggling WireGuard tunnels

### ISSUE THREAD

**Issue by balporig** [henrichg/PhoneProfilesPlus#87]
The WireGuard VPN android app exposes toggling ON/OFF tunnels from external apps. An example implementation can be seen by [Easer](https://github.com/renyuneyun/Easer). Options to include:

- Tunnel name: Which tunnel to toggle
- State: On/Off

**Comment by henrichg** [comment]
In source code of Easer:
(https://github.com/renyuneyun/Easer/blob/master/app/src/main/java/ryey/easer/skills/operation/wireguard/WireguardLoader.java)
https://github.com/renyuneyun/Easer/blob/master/app/src/main/java/ryey/easer/skills/operation/wireguard/WireguardOperationSkill.java

I'm found also this: 
https://www.reddit.com/r/tasker/comments/fn6wou/wireguard_now_supports_control_by_remote_apps/

Result: will be implemented.
Will be added new profile parameter "VPN". In it will be OpenVPN support (currently in "Run application, shortcut, intent" as predefined intents) and added WireGuard. ;-)

**Comment by henrichg** [comment]
Impleneted. If you want, install and test it. Added is profile parameter "VPN" in "Radios" section.
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by henrichg** [comment]
- You granted permission for WireGuard? It is required. PPP notifies it, when you activate profile. Tunnel name is correct?
- "OpenVPN profile name" is disabled, when you set WireGuard in "VPN apllication:".
- Activity log is only for information, not for detailed llog, waht was wrong. And in Activity log are only some errors loged. Not all.
- Beta releases in izzyDroid repo: sorry not. Beta release is not by all users, only by users, which send me e-mail with errors, suggestions, ...

**Comment by henrichg** [comment]
- I will be loking on it.
- Is disabled, color of OpenVPN label and edit text is changed. And is not clickable. It is by system. Is not good to dynamically change dialog layout. Not good for users. Disabling views is standard in Android.
- sorry, not, end of this discussion
- sorry, not, end of this discussion.

**Comment by henrichg** [comment]
I'm found bug. Mixed call of activaty and broadcast. :-( Fixed.
Fixed version: https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by henrichg** [comment]
But "Enable VPN" does not setup tunnel configuration. It only set it ON. You must configure tunnel in WireGuard.

From Easer:

    static final String INTENT_STATE_UP = "com.wireguard.android.action.SET_TUNNEL_UP";
    static final String INTENT_STATE_DOWN = "com.wireguard.android.action.SET_TUNNEL_DOWN";

    static final String EXTRA_TUNNEL_NAME = "tunnel";

    static final String WIREGUARD_APP = "com.wireguard.android";

public void _load(@NonNull WireguardOperationData data, @NonNull OnResultCallback callback) {
        Intent intent = new Intent(data.tunnel_state ? INTENT_STATE_UP : INTENT_STATE_DOWN);
        intent.setPackage(WireguardOperationSkill.WIREGUARD_APP);
        intent.putExtra(EXTRA_TUNNEL_NAME, data.tunnel_name);
        context.sendBroadcast(intent);
        callback.onResult(true);
    }

The samo code is in PPP. 

Code from PPP is similar:

intent = new Intent(enableVPN ? "com.wireguard.android.action.SET_TUNNEL_UP" : "com.wireguard.android.action.SET_TUNNEL_DOWN");
intent.setPackage("com.wireguard.android");
intent.putExtra("tunnel", tunnelName);

**Comment by henrichg** [comment]
Ach so! Currently I uderstand. PPP do not detect changes in VPN parameter configuration. OK will be fixed soon. Thanks.

**Comment by henrichg** [comment]
Fixed: https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by henrichg** [comment]
;-)

**Comment by henrichg** [comment]
Implemented.
