### ISSUE TITLE
Consider using Weblate as localization tool instead Crowdin

### ISSUE THREAD

**Issue by balporig** [henrichg/PhoneProfilesPlus#88]
Weblate is free, opensource and more private localization tool. The hosted version https://hosted.weblate.org/ is free for libre projects.  It is a home for many well known open source projects like F-Droid, OsmAnd, KOReader, Tasks.org, AndrOBD, Minetest, Orbot, Freedombox, and many, many others. It also provides a better tool with more features and better user experience for the translators. After configured, can automatically push changes to a given branch.

**Comment by henrichg** [comment]
PPP uses crowdin several years. Is free of charge for open-source projects. Has Android support, e-mail notifications about changes to all translators.
PPP has in crowdin 63 translators for 47 languages.
For this, is not good to move to another service.

**Comment by henrichg** [comment]
My problem is with translators. Not mine. Is not problem to change translation service, but how about translators?
Sorry, but crowdin is good service for translation of PPP.

**Comment by henrichg** [comment]
Sorry, not. 63 Translators. Again: 63 Transators.
End of this discussion.
