### ISSUE TITLE
Going back from system settings goes to home screen

### ISSUE THREAD

**Issue by Forever-Young** [henrichg/PhoneProfilesPlus#9]
Like permissions and so on. I press back - it goes to the home screen. 
If I open program again from shortcut - main screen opens, not that I moved from (in application interface - open from home screen - editor)

**Comment by henrichg** [comment]
Only Permissions. By me it is OK, beacause permissions are changed, application must be closed.

**Comment by Forever-Young** [comment]
Or, so it is intentionally closed? I thought some problem with opening from shortcut, since it has some setting, open this or that way.
About permissions - is this only for these special permissions? (I'm talking about dynamic permissions on Android 6)

**Comment by henrichg** [comment]
Yes t is intentionally closed. And for all permissions:
1. Modify system settings -> for change values in Settings.System parameters.
2. Do not disturb access -> for change Do not disturb. In Android 7 is this required.
3. Application permissions -> "dynamic permissions on Android 6"
