### ISSUE TITLE
Notification in dark mode

### ISSUE THREAD

**Issue by RuboGubo** [henrichg/PhoneProfilesPlus#90]
When in dark mode, the background of the notificarion does not go dark, which is anoying. (Not a big deal though)
![Screenshot_20220827-223131_Firefox](https://user-images.githubusercontent.com/73720453/187048741-e32ba9c2-5190-496d-be6e-865dfd0f7144.jpg)

**Comment by henrichg** [comment]
Uff, not good. How is configured PPP Settings/"Application notification"/"Background color"? "Native"? And in device is set Dark mode? 
Write me also, Androide version, device name.
Thanks.

**Comment by RuboGubo** [comment]
Hi, the "background colour" is set to native, and the device is set to 
native via the system setting. In regards to the other information; I 
am on android version 9 and am using a  Samsung Galaxy S8.

**Comment by henrichg** [comment]
> ...the device is set to native via the system setting...

Native? What is "native"? In your device is not Dark mode? Maybe it is named as "Device theme"?
Hm, PPP uses transparent background color for "Background color"="Native", but this is white color.  Not good.
Then change "Background color" to "Dark" or "Black" or "Custom color" and set "Custom background color".
Or you can set "Notification style" to "Native".

This must be "bug" in Android 9. In source code of PPP I have comment:
```
// In 28 (Android 9) exists Dark theme, but not working in emulator,
// must be tested in device (for example Nexus 5x).
```
Dark theme not working also in your device :-(

**Comment by RuboGubo** [comment]
Sorry, i meant dark mode. Also, i have just discovered that the 
generated notification when set in a profile does have the correct 
background colour.

**Comment by henrichg** [comment]
Then all is OK? Notification background is dark?

**Comment by RuboGubo** [comment]
Yes, this should all work, not ideal for new users though.

**Comment by henrichg** [comment]
Yes, I will looing on it.
Which PPP version you have installed? Latest is 6.0.1.

**Comment by RuboGubo** [comment]
Yes i am currently on 6.0.1

**Comment by henrichg** [comment]
I'm tested it in Nexus 5x with Android 9 and working good. Background was changed by Dark theme. Maybe bug is in Samsung Android. Not good.

**Comment by RuboGubo** [comment]
For some reason the normal notifications gen from profiles work fine.
![Screenshot_20220828-113948_Firefox](https://user-images.githubusercontent.com/73720453/187069805-292bc3d1-cd51-4998-af75-6c29fbcec02d.jpg)

**Comment by henrichg** [comment]
Up is "Activated profile" notification. It is main notification of PPP. In PPP Settings "Application notification" are settings for it. If in thhese settings, "Notification style"="Native", used is system notification and background is set by system. If "Notification style"="Custom", used is custom layout from PPP and for it this must be configured correct "Background color".
Next is, by me, notification generated by profile activation, parameter "Others"/"Generate notification". It uses system notification, background is set by system.
