### ISSUE TITLE
Changing screen brightness issue

### ISSUE THREAD

**Issue by AlgebraTheBard** [henrichg/PhoneProfilesPlus#91]
The changeing of brightness in PhoneProfilePlus is not working properly with Android 12, please check.

**Comment by AlgebraTheBard** [comment]
My device is Doogee S98, in latest android 12, PPP is the latest one., V6.0.1(6810)

Sent from MailDroid

-----Original Message-----

**Comment by henrichg** [comment]
Problem with brightness is:
- max brighness value may be > 255
- brightness level may be exponencial

In source code is tested Doogee. And for it is not used exponecial brightness. And max. value is 255.
Check for Doogee was added, because was reported by another user.

Question: you using adaptive brightness?

**Comment by AlgebraTheBard** [comment]
Dear Sir The result is the same either adaptive brightness is selected. Regards, Leo Yan From: Henrich GronSent: Monday, 3 October 2022 17:04To: henrichg/PhoneProfilesPlusCc: AlgebraTheBard; AuthorSubject: Re: [henrichg/PhoneProfilesPlus] Changing screen brightness issue (Issue #91) Problem with brightness is:max brighness value may be > 255brightness level may be exponencialIn source code is tested Doogee. And for it is not used exponecial brightness. And max. value is 255.Check for Doogee was added, because was reported by another user.Question: you using adaptive brightness?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by henrichg** [comment]
Please fix your last post. Is not readable.

**Comment by AlgebraTheBard** [comment]
NO custom ROM or unlock bootloader either

**Comment by AlgebraTheBard** [comment]
The brightness level would change some times, may be 1 in 10.

**Comment by AlgebraTheBard** [comment]
Just sent the log, please check.

**Comment by henrichg** [comment]
Yes but: ypu changed brightness in device XSettings? And:
1. minimal value
2. half value
3. maximal value
?

Because in log are not these values.

In log is:

Tehi si half? This value is form start of PPP:
6.10.22 17:25:40:7 [ E ] [ SettingsContentObserver.onChange ]: savedBrightnessMode=0
6.10.22 17:25:40:8 [ E ] [ SettingsContentObserver.onChange ]: savedBrightness=51
6.10.22 17:25:40:8 [ E ] [ SettingsContentObserver.onChange ]: savedAdaptiveBrightness=-1.0

This is minimum?
6.10.22 17:25:43:7 [ E ] [ SettingsContentObserver.onChange ]: savedBrightnessMode=1
6.10.22 17:25:43:7 [ E ] [ SettingsContentObserver.onChange ]: savedBrightness=6
6.10.22 17:25:43:7 [ E ] [ SettingsContentObserver.onChange ]: savedAdaptiveBrightness=-1.0

And this is which value?
6.10.22 17:25:52:2 [ E ] [ SettingsContentObserver.onChange ]: savedBrightnessMode=0
6.10.22 17:25:52:2 [ E ] [ SettingsContentObserver.onChange ]: savedBrightness=11
6.10.22 17:25:52:2 [ E ] [ SettingsContentObserver.onChange ]: savedAdaptiveBrightness=-1.0

Maxumim value must be >= 255 not 51

Again: do not activate profile. Change brightness in DEVICE SETTINGS. This is important!

**Comment by henrichg** [comment]
In progress bar in device settings is possible to set min (start of bar), max (end of bar), half (center of bar). Use it.

**Comment by AlgebraTheBard** [comment]
I redo the process, and sent the log.

**Comment by henrichg** [comment]
In your data. All in profiles is configured: "Screen"/"Screen brightness".
When you manually activate profile. Brightness is not changed? Or changed but not as you want?

- "Entertainments" - 60%
- "Entertainments_Bluetooth" - 60%
- "Factory" - 0%
- "gaming" - 30%
- "Home" - 0%
- "Home_charging" - 0%
- "Low battery" - 0%
- "Night" - 0%
- "Night_charging" - 0%
- "Outdoor_charging" - 80%
- "Outdoor_day" - 100%
- "Outdoor_night" - 20%
- "Photo Shooting" - 100%
- "Room_Night_charging" - 0%
- "Roaming_daytime" - 0%
- "Roaming_night" - 0%

All is configured as manual brightness.

Test brightness change with manula profile activation.

**Comment by AlgebraTheBard** [comment]
Correct, the brightness of screen not changing most of the time, either manually or automatic.

**Comment by AlgebraTheBard** [comment]
My default profile is Outdoor_Day, the screen would truned to max brightness at the most beginning, but the screen brightness not changing at all (most of the time), even manually switch profile or by PPP itself.

**Comment by AlgebraTheBard** [comment]
Even the brightness change, e.g. 0% from the setting, it always goes to 20%.

**Comment by henrichg** [comment]
OK, test this.

1. Do backup of your data. Use Editor menu "Backup/restore"/"Backup settings".

2. Remove from all profiles "Keep screen on". Set it to "Do not change".

3. Add profile with "Keep screen on"="Off" and activate it. This dislables "keep screen on", when is activated.

4. Test brightness by profile activations. Maybe will be working, when "keep screen on" is disabled.

**Comment by henrichg** [comment]
In this version is fixed not worked brightness = 0%. Not worked also in Pixel 6.
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by henrichg** [comment]
"Even the brightness change, e.g. 0% from the setting, it always goes to 20%."
I do not understand this.
You have in device Settings brightnes to minimum (0%) and profile activation do not change it to 20%? Profile "Outdoor_night" has this configuration.

**Comment by AlgebraTheBard** [comment]
I mean the brightness change to 20%, when the profile (0% brightness) is activated by PPP or manual.

Let me try the other version of the app

**Comment by AlgebraTheBard** [comment]
> In this version is fixed not worked brightness = 0%. Not worked also in Pixel 6. https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

This one seems worked for my phone

**Comment by henrichg** [comment]
"I mean the brightness change to 20%, when the profile (0% brightness) is activated by PPP or manual."
Hm, interesting.
OK, check brightness changes, when "Keep screen on" is disabled. For disabling it, activate profile with "Keep screen on"="Off".

**Comment by AlgebraTheBard** [comment]
I re-set the brightness level with 0 or 50, tried with adaptive on or off, the results are the same. Regards, Leo Yan From: Henrich GronSent: Monday, 3 October 2022 17:04To: henrichg/PhoneProfilesPlusCc: AlgebraTheBard; AuthorSubject: Re: [henrichg/PhoneProfilesPlus] Changing screen brightness issue (Issue #91) Problem with brightness is:max brighness value may be > 255brightness level may be exponencialIn source code is tested Doogee. And for it is not used exponecial brightness. And max. value is 255.Check for Doogee was added, because was reported by another user.Question: you using adaptive brightness?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by henrichg** [comment]
"re-set the brightness level with 0 or 50, tried with adaptive on or off, the results are the same."
I do not understand.

My questions:
1. Set brightness to 0 or 50 is by profile activation? And this do not change brightness? After profile activation, what is configured in device Settings?
2. Or set brightness by profile activation working, but after activation not working change of level by device Settings? Or you change it with slider in notification panel? And this not working?

**Comment by henrichg** [comment]
"1. I did the brightness change manually for the log, I have adaptive de-select for all profiles."
Please answer me: Is profile activated from PPP? And this working, brightness is changed, when in profile is configured brightness 0, 50? Manual = manual profile activation (from Activator, Editor, widget, ...), not from event.

"The brightnesses change as per the profile set after using the seccond version of the app."
This is oposite of first quesation. Brightness change form device Settings or notification slider working?

**Comment by AlgebraTheBard** [comment]
1. Activated by manually selected in Activator, brightness change as per profile values; brightness values in Setting is same as the profiles. 
2. Brightness changes with PPP automatically, brightness values change same as profile setting.

**Comment by henrichg** [comment]
Then working. When in device Settings is the same value as in activated profile, then all working good.
So what is the problem?

**Comment by AlgebraTheBard** [comment]
> Then working. When in device Settings is the same value as in activated profile, then all working good. So what is the problem?

I am answering your question 22 hours ago, no problem now.

**Comment by henrichg** [comment]
OK then. Thank you.
