### ISSUE TITLE
[Feature Request]  Option to automatically delete un-named Mobile Cells after a user defined period of time

### ISSUE THREAD

**Issue by scrunchy** [henrichg/PhoneProfilesPlus#92]
Hi, This feature would make it much easier to avoid the situation when (for instance on a long drive / train ride) many mobile cells get added to the database due to a brief connection.  I have had situations where the management of the Mobile Cells becomes very sluggish and I need to manually delete many unnamed and unwanted cells before I can use the app without lags again.

If the user could set a time period (for instance 4 weeks or similar) that a mobile cell would be automatically deleted if it had not been named then this would not happen.

If I haven't named a cell in a few weeks I never will, and likely will never want to use it.

Thanks for all the work on this app, it really is fantastic!

**Comment by henrichg** [comment]
Two functions exists to add new cells:
1. "Cell registration" in "Mobile cells sensor". In it must be configured "Cell name".
2. In "Mobile cells scanner", parameter "Show notificaton for detection of not used mobile cells". In it is set cell name by event which is running when is detected new cell.

Do you use these functions?

I found one situation where a mobile cell is added to the database without a cell name.
This is in functionality 2. "Show notificaton for detection of not used mobile cells".
That is not good. I have to fix it.

**Comment by henrichg** [comment]
OK, by me, will be good to add into "Cells" dialog, option to delete all un-named cells.
But only non-selected, because is not good to delete cell used in any event.

**Comment by scrunchy** [comment]
That sounds great, much appreciated.  I checked and I did have "Mobile cells scanner", parameter "Show notificaton for detection of not used mobile cells" set so I ahve unchecked that in the meantime.  Thanks!

**Comment by henrichg** [comment]
Added is functionality: Delete all non-named, not used mobile cells at start of new PPP release. Also will be removed at restore of settings from beckup.

Also fixed are add of new cells. Is not possible to add non-named mobile cell:
1. At mobile cells registration.
2. At automatic detection of not used mobile cells.
3. In Mobile cells parameter.

It is in this link: https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

Before of installation, do backup of PPP data. For this use in Editor menu "Backup/restore"/"Backup settigs".

**Comment by scrunchy** [comment]
Fantastic! Thanks for this, I'll give it a spin and report back.
