### ISSUE TITLE
No Samsung Edge Panel on Samsung Galaxy Tab S8 Ultra 5G

### ISSUE THREAD

**Issue by Chrys000** [henrichg/PhoneProfilesPlus#95]
There is no PhoneProfilePlus panel for this device. Android 13 One UI 5.0
It works on Samsung Galaxy S22 Ultra mobile phone. Android 13 One UI 5.0

**Comment by henrichg** [comment]
Bacause Smasung do not supports custom panels in its tablets. Supports only panels included in system. Also in my Samsung Tab is not support for this. Not exists button "Galaxy Store" = not possible to install panels from store. :-(

**Comment by Chrys000** [comment]
I see, thx for the clarification. I just added the PhoneProfilePlus starter icon to the app-panel, this is more than nothing.
