### ISSUE TITLE
Media volume should remain unchanged if playing media even when profiles switch

### ISSUE THREAD

**Issue by auto-generate** [henrichg/PhoneProfilesPlus#96]
Scenario: I have a daytime and nighttime profile and they set the ringer/notification/media volumes.  If I'm playing media, then that should mean the media volume is at the correct level.  When the time for daytime or nighttime profile comes it will change the media volume making it too loud or too soft.

Request: To have the option for media volume only, to keep the volume unchanged if media is currently playing.  This is not required for ringer/notification or other volume.

**Comment by henrichg** [comment]
Implemented.
If you want, install and test this beta version:
https://drive.google.com/file/d/1CR4y2u3V8PCwQK9sw1P88JrlpSdA2Ou4/view?usp=drivesdk

**Comment by auto-generate** [comment]
Thank you, that was quick!  I tested it and it works properly.  Manual profile switching when nothing is playing updates all the volume and when media is playing the media volume stays the same while the other volumes change.  Also tested time and wifi sensor triggering the profile and it works as well.  Have a beer/coffee on me!

**Comment by henrichg** [comment]
Good. :-)
