### ISSUE TITLE
Not available in edge panels for Galaxy Z Fold4

### ISSUE THREAD

**Issue by v-aravind** [henrichg/PhoneProfilesPlus#97]
Hi, 
I recently switched to a Galaxy Z Fold4 running One UI 5.1 Android 13. PPP doesn't seem to be available as an option for edge panels. Please can you look into this.
Thanks

**Comment by henrichg** [comment]
In Edge panel settings is doslayed also button "Galaxy Store"? If not, then this is problem. Supported are only internal panels.
Similar problem is in Samsung tablets.

**Comment by v-aravind** [comment]
I'm not sure where exact you mean I should see the "galaxy store" button. I am able to see and select Galaxy Store under apps. But do you mean somewhere else? 
![Screenshot_20230129_161902_Apps](https://user-images.githubusercontent.com/69113302/215339761-f404a32a-0e98-4a5c-b285-35490b83780d.jpg)

**Comment by henrichg** [comment]
Display/Edge panels/Panles:
![Screenshot_20230129_172554_Edge panels](https://user-images.githubusercontent.com/4045914/215340299-c6ad59e6-d21c-4a2a-ae78-cd770ad5c302.png)

**Comment by v-aravind** [comment]
No 😭
![Screenshot_20230129_164635_Edge panels.jpg](https://user-images.githubusercontent.com/69113302/215341180-06031aa5-854c-4ffa-8ae8-9d29e61d127f.jpg)

**Comment by henrichg** [comment]
Maybe because your 5.1 i in beta? Or for Z Fold 4 is official 5.1, released?

**Comment by v-aravind** [comment]
Sorry I'm still on 5.0, not 5.1, it is the stable release

**Comment by henrichg** [comment]
Ok, then the Z Fold devices have the same limitation as the Samsung tablets. :-(
Not bug in PPP, but Samsung "feature".
