### ISSUE TITLE
only work on ringtone volume

### ISSUE THREAD

**Issue by elsns** [henrichg/PhoneProfilesPlus#98]
I set all the levels of each kind volume, but only work good on ringtone, dose not work on notification, media and alarm clock.  my phone is iqoo11 with Android13.
![Uploading 2023-02-28-10-00-51.png…]()

**Comment by henrichg** [comment]
Please send me PPP settings. For this use in Editor menu "Support"/"E-mail settings to author"

**Comment by henrichg** [comment]
Your data are ok.
Set volume not working at all or only is bad value set?
And it not working for all profiles? 
When is profile activated manually (from Activator, Editor, Shortcut, ...), also not working?

**Comment by elsns** [comment]
I tried manually to active different profiles in each way (Activator, Editor, Shortcut, ...), still not working. Only can set the ringtong volume. the profile 'mute' and 'meeting' I created works ok can change every kind of volume to 0, but other profiles can only change the rington. the app works well on my other phone with android10, I backup the profiles from it and copy to this new phone. so I try to creat a new empty profile and set&nbsp;parameters manually, not working.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "henrichg/PhoneProfilesPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 凌晨1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [henrichg/PhoneProfilesPlus] only work on ringtone volume (Issue #98)





 
Your data are ok.
 Set volume not working at all or only is bad value set?
 And it not working for all profiles?
 When is profile activated manually (from Activator, Editor, Shortcut, ...), also not working?

**Comment by henrichg** [comment]
You have granted in Editor menu "Permissions"/"Modify system settings"?
Also test another application, for example Marcodroid. For it working change volumes?

Also check (serarch in internet) if in your device Settings is any parameter for enable volumes change from applications.
