### ISSUE TITLE
Sound profile Do Not Disturb - Priority not applying system settings for "who can interrupt"

### ISSUE THREAD

**Issue by jeremyrichard87** [henrichg/PhoneProfilesPlus#99]
First of all, thanks for this extremely useful app, using it on a daily basis.

There is a bug when enabling a profile with a sound profile with "Do Not Disturb" type setting on "Priority" mode.
When enabled, instead of using the system "Do Not Disturb" settings for "Who can interrupt", it overwrite with blank.
This behavior DON'T happen with a profile with a sound profile with "Do Not Disturb" type setting on "Priority with vibration" mode, it works as expected.
See screen recording of the issue [here](https://drive.google.com/file/d/1FBCNNBjWxoWhFNos63o6mh9nxX2m5Hhv/view?usp=drivesdk).

Pixel 6 Pro, Android 13, not rooted.

Feel free to reach out if you have any questions.

**Comment by henrichg** [comment]
In my Pixel 6, Android 13, latest beta, 5.3.2023, is not this problem. All is enabled in DND - Priority.

Please send me your PPP Settings. It is in Editor menu Support/"E-mail settings to author"

**Comment by henrichg** [comment]
And write me, how you have configured DND in device Settings.
